lem-project/lem

lem.asd

sbcl --load lem.asd --load build.lisp
でlemの実行ファイルが出来るので個人的には便利です。

make lem.asd loadable.

---

lem.lisp

add describe bindings though not yet bound any key

---

bufed.lisp
key.lisp
search.lisp

ちょっとリハビリ兼ねて。
キーの名前を整理しないといけない…と思いますがなかなか。

add '[del]' and bind.

---

lem-core/comp.lisp

patch for users who use [up]/[down] rather than C-n/C-p.

---

lem-core/comp.lisp
lem-core/isearch.lisp
lem-core/keymap.lisp
lem-core/mode.lisp
lem-lisp-mode/lisp-mode.lisp

just tweak.
ところで``*keymaps*``って今後使う予定ありますか？

define keymap print function.

---

lem-base/lem-base.asd
lem-base/syntax-highlight-tm.lisp
lem-base/syntax-highlight.lisp
lem-base/syntax.lisp
lem-core/go-mode.lisp
lem-core/lem.lisp
lem-lisp-mode/lisp-mode.lisp
lem-lisp-syntax/syntax-table.lisp

機能的にはtmLanguageの一部だけですが以前の方法と同じ事が出来るくらいにはなったので
早めにマージしておきます

Tmlanguage

---

lem-core/file-command.lisp
lem-core/grep.lisp

trivial as well.
I think dired-mode's keybind "g" should be ``revert-buffer``

override revert-buffer using buffer-value.

---

lem-core/lem.lisp
lem.asd

バージョン1.0おめでとうございます。
自分のインストールしているlemのバージョンを確認したかったためこの機能を実装しました。
ご検討よろしくお願い申し上げます。

バージョン表示機能の追加

---

README.md

screencast

---

README.md

update on vision, installation, and usage

---

README.md

I added some more information for beginners.

installation guide for beginners

---

README.md

README fixed

---

lem-vi-mode/ex-command.lisp

Added ex command :e

---

README.md

Readme updated: added the statement about nodejs version

added the statement about nodejs version

---

roswell/lem

edit script to support unknown frontend

---

.travis.yml
contrib/modeline-battery/lem-modeline-battery.asd

We might need better way to test all of contribs automatically.

fix contrib/modeline-battery

---

lem-frontend-xcb/Readme.md
lem-frontend-xcb/global.lisp
lem-frontend-xcb/lem-xcb.asd
lem-frontend-xcb/test.lisp
lem-frontend-xcb/xcb-app/lemwin.lisp
lem-frontend-xcb/xcb-app/xcb-system.lisp
lem-frontend-xcb/xcb/keys.lisp

XCB cleanup

---

lem-frontend-xcb/global.lisp
lem-frontend-xcb/xcb-app/attributes.lisp
lem-frontend-xcb/xcb-app/lemwin.lisp

Fixed bold and underline attributes (typo prevented them from working)

XCB bugfix

---

README.md

readme: note about rasberry pi added

readme: note about rasberry pi added

---

roswell/lem

A bit lessen memory consumption.

exec frontend.

---

roswell/lem

$LEM_DEFAULT_FRONTEND to set default.

---

lem-base/file.lisp
lem-base/fileutil.lisp

prepare for tramp like facility.

prepare extensible path facility.

---

lem-js-mode/js-mode.lisp
lem-js-mode/lem-js-mode.asd
lem.asd

* syntax highlighet for JavaScript
* keywords, operators, string and numeric literals

add js-mode

---

lem-core/interp.lisp

pop-up-typeout-window from pop-up-backtrace.

---

lem-lisp-mode/lisp-mode.lisp

slime-self-connect to open repl buffer.

---

lem-lisp-mode/lisp-mode.lisp

prompt-for-impl and support-qlot

---

lem-lisp-mode/lisp-mode.lisp

lisp-scratch command to prepare scratch buffer.

---

lem-base/fileutil.lisp
lem-core/comp.lisp
lem-core/completion-mode.lisp
lem-core/file-command.lisp
lem-core/minibuffer.lisp

preparation for implement ,change-directory at lisp-repl.

prepare prompt-for-directory

---

lem-vi-mode/binds.lisp
lem-vi-mode/commands.lisp

Those are similar to 'd' and 'D' except enabling INSERT mode after deleting.

[vi-mode] Add 'c' & 'C' for deleting and enabling INSERT mode

---

lem-vi-mode/commands.lisp

Vim's **word** is different from Emacs -- it's a sequence of alphanumeric or underscores.
This is fixing the position to move with `e` and `b`.

[vi-mode] Fix the position to move with 'e' and 'b'.

---

lem-css-mode/css-mode.lisp

Change the regular expression so that both spaces are not included in keywords.

fix: blank both ends

---

lem-vi-mode/commands.lisp

[vi-mode] Fix visual line deletion not to remain an empty line

---

lem-vi-mode/commands.lisp

With like 'dk', 'dj' and 'd3j'.

[vi-mode] Allow to delete multiple lines

---

lem-core/command.lisp
lem-vi-mode/binds.lisp
lem-vi-mode/commands.lisp

- Add `next-logical-line` and `previous-logical-line`
- Change vi-mode `g` / `k` to use them
- Add `gj` and `gk` for vi-mode

Add next-logical-line/previous-logical-line and add keybinds for vi-mode

---

lem-vi-mode/ex-command.lisp
lem-vi-mode/ex-core.lisp

```
Shell command exection with :!
```
#205  related.

[vi-mode] define-ex-command to take regex ... and define :!

---

lem-frontend-electron/lem-editor/keyevent.js
lem-jsonrpc/jsonrpc.lisp
package.json

I fixed 2 points.
1. lem-frontend-electron has unnecessary code causing error (related with dependent library).
2. couldn't use `#rrggbb` style color code in option.js. 
please check. 
Thank you.

Frontend electron

---

lem-base/package.lisp
lem-core/abbrev.lisp
lem-core/auto-save.lisp
lem-core/button.lisp
lem-core/completion-mode.lisp
lem-core/defcommand.lisp
lem-core/directory-mode.lisp
lem-core/fundamental-mode.lisp
lem-core/go-back.lisp
lem-core/grep.lisp
lem-core/gtags.lisp
lem-core/history.lisp
lem-core/isearch.lisp
lem-core/kbdmacro.lisp
lem-core/language-mode.lisp
lem-core/line-numbers.lisp
lem-core/list-buffers.lisp
lem-core/listener-mode.lisp
lem-core/menu-mode.lisp
lem-core/package.lisp
lem-core/popup-window.lisp
lem-core/rectangle.lisp
lem-core/showparen.lisp
lem-core/sourcelist.lisp
lem-core/tmlanguage.lisp
lem-core/universal-argument.lisp
lem-vi-mode/commands.lisp

Revert "Retry export via define command"

---

lem-xml-mode/lem-xml-mode.asd
lem-xml-mode/xml-mode.lisp

[WIP] Auto indentation for xml-mode

---

lem-base/buffer.lisp
lem-core/file-command.lisp

change buffer name if the file name changed.

change buffer name on write-file(C-x C-w)

---

lem-core/window-command.lisp

window command which is executed in another window
find-file-other-window(C-x 4 f)
read-file-other-window(C-x 4 r)
select-buffer-other-window(C-x 4 b)

Other window command

---

lem-lisp-mode/lisp-mode.lisp

fix: move-over-\)

---

lem-frontend-electron/lem-editor/lem-editor.js
lem-frontend-electron/lem-editor/option.js
lem-frontend-electron/lem-electron-backend/main.lisp

I try to modifier code to input with IME (For example, we want to input 日本語 sometime).
However, lem-frontend-electron have not yet completely deal with multi-byte characters. 
e.g. we can't open files having multi-byte characters name from GUI.

mod: input with ime

---

lem-base/buffer.lisp
lem-core/file-command.lisp

use rename-buffer instead of setf.

---

lem-nim-mode/lem-nim-mode.asd
lem-nim-mode/nim-mode.lisp

This PR add a major mode for [Nim](https://nim-lang.org/) language to lem.

Major mode for Nim

---

frontends/ncurses/term.lisp
frontends/pdcurses/ncurses-pdcurseswin32.lisp

Move variables from term.lisp to pdcurses

---

lem.asd
modes/scheme-mode/grammer.lisp
modes/scheme-mode/lem-scheme-mode.asd
modes/scheme-mode/lem-scheme-syntax.lisp
modes/scheme-mode/package.lisp
modes/scheme-mode/scheme-mode.lisp
modes/scheme-mode/syntax-indent.lisp
modes/scheme-mode/syntax-misc.lisp
modes/scheme-mode/syntax-syntax-table.lisp

Scheme モードを追加してみました。
現状、ハイライトとインデントのみの対応です。
lisp-mode と lisp-syntax をベースに、リネームしたり削ったりして作成しました。
(よく分からずに流用している部分があります。。。)
lisp-syntax がベースのファイルは、先頭に syntax- を付加しました。

Add scheme mode

---

frontends/pdcurses/ncurses-pdcurseswin32.lisp

lem-pdcurses で、
Shift+クリックでテキストを貼り付けたときに、
1文字ごとに sleep して遅くなっていたため対策しました。
コンソールに入力がたまっているときは、sleep しないようにしました。
(元々この sleep は、C-x C-c でうまく終了できなかったために、
試行錯誤で入れたものです。。。)
あと、windows api の dll 名を修正しました。
(ロードしなくても動くようですが。。。)

Reduce sleep count in event loop of lem-pdcurses

---

frontends/pdcurses/ncurses-pdcurseswin32.lisp

lem-pdcurses で C-j を使えるようにしました。

Make C-j work on lem-pdcurses

---

modes/nim-mode/nim-mode.lisp

[nim-mode] Fix an wrong function name for indent calculation

---

document/text-english.md

ran text.md through google translate and got this.

text.md for english users

---

frontends/pdcurses/ncurses-pdcurseswin32.lisp

lem-pdcurses ですが、C-x C-c で終了しないという問題 (次に何かキーを押すと終了する) があり、
これまでは、input-loop に sleep を入れることで 対策していました。
当時の調査では、editor-thread は終わろうとしているが、
input-thread が PDCurses 内の ReadConsoleInput (Windows API) のところで
待ったままになっているようでした。
(試行錯誤であちこちに sleep を入れてみた記憶があります)
しかし、sleep による回避法には、以下の問題がありました。
(1) たまに C-x C-c で終了しないことがある (次に何かキーを押すと終了する)
(2) lem-if:invoke に bt:join-thread が必要になった
(理由は分からない。ないと次のエラーが出る 'compilation unit aborted caught 1 fatal ERROR condition')
(3) クリップボードからのペースト時に、1文字ごとに sleep して遅くなるため、対策が必要になった (#338)
それで今回、PDCurses の getch にタイムアウトを設定することで、sleep を削除しました。
これで (2) (3) が不要となり、終了も安定するようです。
特に速度やCPU負荷も変わらないようなので、これで様子をみたいと思います。
(ただ、swank server がしばしば終了しない件については、別件としてまだあります。。。)

Remove sleep in input-loop on lem-pdcurses

---

lib/core/command.lisp

Now lem-version command output a git hash if it is available.

---

frontends/pdcurses/ncurses-pdcurseswin32.lisp

#379 で、画面右下に何かしら表示することで、表示の乱れを回避したのですが、
ミニバッファにワイド文字を入力すると、
右下の座標がずれて、画面全体がスクロールしてしまうという
新バグが出てしまったため、対処しました。。。
修正できていると思いますが、
基本的にミニバッファの表示領域と #379 のワークアラウンドが競合しているので、
念のため以下の設定を init.lisp に書くと、最下行を1行空けられるようにしました。
```
#+(and win32 lem-ncurses)
(setf (lem-ncurses::reserved-last-lines lem-ncurses::*windows-term-setting*) 1)
```

Fix workaround of last line on lem-pdcurses

---

modes/lisp-mode/lisp-mode.lisp

以下の変更をしました。
1. lem-mode.lisp 内の start-thread について、
change-connection 例外が上がってくるタイミングが安定しなかったため、
sleep を追加した。
(接続の切換時に、次に何か入力するまで例外が上がって来ない、等。
ただ、少し後の message-waiting-p も sleep みたいなものだと思うのだが。。。)
2. lem-mode.lisp 内の start-thread について、
handler-case の内側で loop するようにした。
(change-connection 例外をハンドルできない レアケース をなくすため)
3. lem-mode.lisp 内の slime-quit-all / slime-quit-all-for-win32 について、
lem の終了時に swank-server との通信がすでに切れていると、
エラーが出て lem を終了できなくなったため、
ignore-errors を追加した。

Improve slime connection on Windows v3

---

modes/scheme-mode/eval.lisp
modes/scheme-mode/lem-scheme-mode.asd
modes/scheme-mode/package.lisp
modes/scheme-mode/repl.lisp

scheme-repl-mode を追加してみました。
(今までは、REPL の画面も scheme-mode で兼用していました)
M-x start-scheme-repl で Scheme の REPL の画面を開いて、
Enter キーで、すぐに評価できるようになりました。
(今までは、C-c C-e 等で評価する必要がありました)

Add scheme-repl-mode

---

frontends/pdcurses/ncurses-pdcurseswin32.lisp

補完メニューを表示した状態でマウスクリックすると、
裏のウィンドウが選択されて、補完メニューが消えなくなったため、
クリック操作をガードするようにしました。
(マウスで補完メニューの項目を選択できるとよいのかもしれませんが。。。
それは難しそうなのでガードのみにしました)
マウスホイールについては、インタラプト画面 ( C-] で表示される floating-window )
のスクロールに使えるようなので、ガードしないでおきました。

Guard mouse click for completion menu on lem-pdcurses

---

lib/core/input.lisp

Last piece of https://github.com/cxxxr/lem/pull/430

Remove essentially redundant call fo `update-timer`

---

modes/scheme-mode/package.lisp
modes/scheme-mode/repl.lisp
modes/scheme-mode/scheme-mode.lisp
modes/scheme-mode/swank-connection.lisp
modes/scheme-mode/swank-protocol.lisp

- r7rs-swank ですが、R7RS の縛りが厳しかったため、Gauche 用に改造した
r7rs-swank-Gauche-custom ( https://github.com/Hamayama/r7rs-swank-Gauche-custom )
を作成してみました。
- これで、scheme-slime の対応機能を少し増やすことができました。
( https://github.com/Hamayama/r7rs-swank-Gauche-custom#%E6%A9%9F%E8%83%BD )
- 本プルリクエストは、そのための Lem 側の変更分になります。

[scheme-mode] Enhance scheme slime function for r7rs-swank-Gauche-custom

---

lib/lisp-syntax/indent.lisp

There are some bugs and I do not know the cause so I will revert.
test results
```
$ ros -e '(asdf:test-system :lem-tests)'
(cond ((foo 1
+        2)))
-            2)))
`(defclass foo ()
,(mapcar x
+     y))
-            y))
(defun move-to-line (point line-number)
"`point`を行番号`line-number`に移動し、移動後の位置を返します。
`line-number`がバッファの範囲外なら`point`は移動せず、NILを返します。"
(let ((cur-linum (line-number-at-point point))
(nlines (buffer-nlines (point-buffer point))))
(cond ((or (> 1 line-number)
+            (< nlines line-number))
-               (< nlines line-number))
nil)
((= line-number cur-linum)
point)
((< line-number cur-linum)
(if (< line-number (- cur-linum line-number))
(line-offset (buffer-start point) (1- line-number))
(line-offset point (- line-number cur-linum))))
(t
(if (< (- line-number …
```

Revert "Complex indent method fix"

---

modes/nim-mode/nim-mode.lisp

Fixed Nim multiline comments

---

README.md

I've pre-build a docker container with Lem, ready for playing.
How this will help people, who are interesting what is Lem about,
but don't want to install SBCL and Roswell right away.

Added a note how to run Lem in the Docker container.

---

modes/python-mode/run-python.lisp

run-python コマンドが Windows 上で動作するようにしました。
実行コマンドは、Windows の場合、python に -i オプションが必要でした。
(付けないと応答が来ない)
また、`*exit-editor-hook*` で、delete-process を実行しないと、lem を終了できませんでした。
(これは、Windows 版の SBCL のスレッド関連の問題かもしれない)
あと、エラー処理を少し追加しました。
＜その他 情報等＞
日本語を表示する場合は、事前に export PYTHONIOENCODING=utf-8 が必要でした。
(この設定しないと、python が入出力を cp932 と仮定してエラーになるもよう (python 3.8.0 で確認))

Make run-python command work on Windows

---

ChangeLog.md

Probably it is time for release 1.7?

Changelog was updated

---

modes/asm-mode/asm-mode.lisp
modes/asm-mode/lem-asm-mode.asd

but we cannot input tabs yet... :sob:

asm-mode!!!

---

lem.asd
modes/asm-mode/asm-mode.lisp

- **import asm-mode into lem**
- calculate indentation
- tab insertion with "tab" key

more improvements for asm-mode

---

modes/fm-mode/fm-mode.lisp

https://github.com/cxxxr/lem/pull/504
の過程で整理したコードからフレームごとに違うバッファリストを持つ機能をrevert

Refactor fm mode

---

contrib/mouse-sgr1006/main.lisp
frontends/pdcurses/ncurses-pdcurseswin32.lisp

Revert "Fix mouse control on curses frontend v2"

---

frontends/pdcurses/ncurses-pdcurseswin32.lisp

- lem-pdcurses で、ウィンドウの境界表示に対応しました。
- 日本語のファイルを表示中にプロンプトウィンドウを表示すると、
ずれて表示されたりしたため、余白の追加等をしています。
(それでも多少ずれることがあります。Windows コンソールの問題)
- あと、ConEmu 上で、ファイル名補完の表示が最下行にかかった際に、
全体がスクロールしてめちゃくちゃな表示になるケースがあったため、
最下行を 1 行空けるようにしました。

[lem-pdcurses] Add border display to window, etc.

---

lib/core/popup-window.lisp

ポップアップ画面の window-redraw で、
width と height の計算結果に対してさらに計算を行うため、
結果が変わることがありました。
(`*extra-width-margin*` がセットされていると、幅が広がっていく)
このため、初回の指定値を base-width と base-height に保存して、
window-redraw (adjust-for-redrawing) では、それらを使うようにしました。
また、width と height の計算を一部修正しました。
(最小値が反映されないケースがありました)
＜関連プルリクエスト＞
#525 #530

Fix popup window position v3

---

lib/core/frame-multiplexer.lisp

Enable frame-multiplexer at startup by default

---

lib/core/window.lisp

長い行の折り返しがあって、行の途中から画面に表示されている場合に、
画面の幅を変更すると、
画面の表示とマウスクリックの座標が不一致になる不具合がありました。
対策として、画面の表示開始位置 (window-view-point) を調整(再計算)する関数を作って、
window-see のところで呼び出すようにしました。
(最初は、画面のサイズを変更するところで呼び出すことを考えたのですが、
画面の横分割の実行時や、サイズ変更後に裏のバッファに切り換えたときにも
発生したため、やめておきました。
(window-see は、非アクティブな画面 (window) には効果がなく、
アクティブにしたタイミングで、画面の開始位置が更新されるので、
若干違和感はあるのですが、ずれたままよりはよいかと…))

Adjust window view point for long line

---

contrib/mouse-sgr1006/main.lisp
frontends/pdcurses/ncurses-pdcurseswin32.lisp
lib/core/frame-multiplexer.lisp

マウスクリックでフレームを選択できるようにしました。
画面上部のタブを、マウスでクリックすると選択できます。

Enable to select frame by mouse click

---

modes/lisp-mode/lisp-mode.lisp

fix inconvenience to edit ros script.

---

modes/paredit-mode/paredit-mode.lisp

Modify paredit mode export

---

modes/lsp-mode/lsp-mode.lisp

add support for markdown drawing in lsp-hover

---

README.md

fixes https://github.com/lem-project/lem/issues/605

fixed issue with lem install instructions

---

modes/vi-mode/commands.lisp
modes/vi-mode/core.lisp
modes/vi-mode/visual.lisp
tests/e2e/vi-mode.lisp

Feel free to leave feedback. I'm actively working to improve vi-mode support. Thank you, @cxxxr

[VI-MODE] • Change "command" state to expected "normal" state from stand Vim.

---

modes/vi-mode/commands.lisp
tests/e2e/vi-mode.lisp

• Excuse the other commit, my apologizes

[VI-MODE] • Word refactor

---

modes/vi-mode/commands.lisp

I think his can fix the issue https://github.com/lem-project/lem/issues/653

Fix vi-backward-word-begin stack bug

---

.github/workflows/generate-document.yml
lem.asd
src/commands/document.lisp
src/ext/document.lisp
src/internal-packages.lisp
src/keymap.lisp

Future tasks
- Add docstring to each command
- Add a link to the location of each command definition
- Prepare two outputs for markdown and lem buffer
- Add key bindings for commands in each mode

Add command keybindings document generator

---

modes/lisp-mode/lisp-mode.lisp
modes/lisp-mode/repl.lisp

Also other command from SLIME/Sly

Add cd repl function and get/set current lisp directory

---

.github/workflows/generate-document.yml
src/commands/buffer.lisp
src/commands/edit.lisp
src/commands/file.lisp
src/commands/font.lisp
src/commands/mark.lisp
src/commands/move.lisp
src/commands/multiple-cursors.lisp
src/commands/process.lisp
src/commands/s-expression.lisp
src/commands/window.lisp
src/commands/word.lisp

Added docstring to basic commands.
There may be some areas that are still missing, but that is for the future.

Add docstring to each command

---

modes/vi-mode/commands.lisp
src/base/basic.lisp

Document some point related commands.

chore: Document some point commands

---

src/base/file-utils.lisp
src/ext/directory-mode.lisp

It works :) and it can certainly be improved (before being extended).

directory-mode: sort by name and mtime

---

modes/lisp-mode/completion.lisp
modes/lisp-mode/lem-lisp-mode.asd
modes/lisp-mode/lisp-mode.lisp
modes/lsp-mode/lsp-mode.lisp
src/ext/hover.lisp

Reimportation of LSP features.

Improve display of completion results

---

src/ext/language-mode.lisp
src/ext/thingatp.lisp

A very Emacsy approach to get the "thing at point", the idea is to extend it with more types :+1:

Add thingatp functionality

---

src/commands/window.lisp

Same, more command docstrings for documentation-describe-bindings.

window: add commands documentation

---

README.md

Important IMO: mention and link to the binaries, mention LSP and other programming languages, mention vi mode.

README: link to downloads, mention LSP

---

src/commands/project.lisp

for consistency with kill-buffer.

project: rename detele -> kill buffers

---

src/color-theme.lisp

* Documents find-color-theme, define-color-theme, inherit-load-theme, and apply-color-theme

Document some color theme functions

---

src/base/point.lisp

Using a mix of automatic translation and guessing.

point: translate docstrings

---

src/base/point.lisp

I introduced a copy-paste error, apologies :pray:

point: translate docstrings (fix)

---

src/base/macros.lisp

I checked everything loads fine :pray: Thank you.

macros: translate docstrings

---

modes/lisp-mode/repl.lisp

Using properties, as suggested here(https://github.com/lem-project/lem/pull/793#pullrequestreview-1503247383)

Improve backward and forward prompt movement

---

src/ext/legit/legit.lisp

legit: fix quit on Escape and M-q

---

src/base/point.lisp

So, this functions was not working correctly, assuming that the reference were going always in descendant order, when is not the case.
I can arrange them and then correct the function, but I think it may cost too much, so I with a few more checks, I can be sure to get the correct reference.
Ping @cxxxr , because this should be included in the 2.1v release (sorry :raised_hands: )

Fix closest-point function

---

frontends/sdl2/image-buffer.lisp

for #863 again, tested with this test image and more configurations.
Simpler and actually correct logic.
Thanks to the person brainstorming with me today^^

image viewer: improve fit to screen

---

extensions/vi-mode/ex-command.lisp
extensions/vi-mode/ex.lisp

Add 2 commands for vi-mode:
* `:b`, equivalent to `C-x b` (`M-x select-buffer`)
* `:bd`, equivalent to `C-x k` (`M-x kill-buffer`)

Add :b and :bd command for vi-mode.

---

src/ext/directory-mode.lisp

Added `M-x directory-mode-renmae-file ("r")`.
The difference with "R" is that the directory cannot be changed.
Also, the UI appears to reflect input in real time.

Add directory-mode-rename-file command

---

extensions/lisp-mode/detective.lisp
extensions/lisp-mode/misc-commands.lisp
src/ext/detective.lisp

I was testing the commands with some Lem tests, and forgot about the `#` symbol, this should fix it.
I'm also addressing some of the comments https://github.com/lem-project/lem/pull/957#pullrequestreview-1580460203 tho I don't fully understand this one https://github.com/lem-project/lem/pull/957#discussion_r1295809648 :sweat_smile: 
Thanks!

Fix test name when starting with # and small improvements

---

frontends/sdl2/main.lisp

This seems to solve my issues with SDL2 #630. Could someone else test it out? I tested running from sly/emacs and from sbcl on the command line. GNU Guix with Sway (no X support).

sdl2: Run paint operations on SDL2 main thread

---

src/interp.lisp

Fix to reset `*this-command-keys*`

---

extensions/vi-mode/states.lisp

Modify invisible cursor in vi-mode NORMAL.

Modify vi-mode NORMAL cursor

---

extensions/vi-mode/commands.lisp

Make the argument of vi-mode's motion optional

---

extensions/vi-mode/commands.lisp
extensions/vi-mode/commands/utils.lisp
extensions/vi-mode/tests/operator.lisp
extensions/vi-mode/visual.lisp

Allow to select the end of line while in visual mode

---

extensions/lsp-mode/lsp-mode.lisp
src/ext/completion-mode.lisp

https://github.com/lem-project/lem/pull/1115#issue-1918303020
A workaround for the problem reported here has been applied.

Fix invidual mismatch between diagnostics and completion window

---

Makefile

Update Makefile not to load the user-home Quicklisp.

---

roswell/lem-language-server.ros
roswell/lem-ncurses-ccl.ros
roswell/lem-ncurses.ros
roswell/lem-rpc.ros
roswell/lem-sdl2.ros

Fix Roswell scripts not to change the current directory when running

---

README.md

README: build with our Docker file

---

extensions/vi-mode/binds.lisp
extensions/vi-mode/commands.lisp
extensions/vi-mode/tests/text-objects.lisp
extensions/vi-mode/text-objects.lisp

In addition to existing text objects implemented `WORD` text object for dealing with broad words.

Vi `WORD` text object.

---

extensions/markdown-mode/markdown-mode.lisp

This command inserts a markdown link on the current point.

Add `markdown-mode` command `markdown-insert-link`

---

frontends/sdl2/main.lisp
src/commands/font.lisp
src/interface.lisp
src/internal-packages.lisp

Add set-font-size in addition to increase and decrease functions, this is handy for me to be able to set it to 18 in my config

Set font size

---

frontends/sdl2/image-buffer.lisp

for #863
Now smaller images get expanded.

image: fit to screen also for smaller images

---

contrib/ollama/README.md
contrib/ollama/lem-ollama.asd
contrib/ollama/listener.lisp
contrib/ollama/ollama.lisp
contrib/ollama/project.lisp

Hello, I have added a contrib package to talk to Ollama servers.
There is a listener-mode interface and a simple prompt command that streams into a temp buffer.
You can close the stream with C-c C-c in both interfaces.
I added some improvements to the listener-mode interface that weren't in the last PR.
Let me know if you have any feedback,
Thank you.

Ollama client

---

extensions/vi-mode/binds.lisp
extensions/vi-mode/commands.lisp

Vim bar (goto column) motion.
https://vimdoc.sourceforge.net/htmldoc/motion.html#g$

Adds vi-mode goto-column motion.

---

extensions/vi-mode/binds.lisp
extensions/vi-mode/commands.lisp
extensions/vi-mode/word.lisp

Vim ge gE (backward word end) motions.
https://vimdoc.sourceforge.net/htmldoc/motion.html#ge

Adds vi-mode backward-word-end and its commands.

---

extensions/vi-mode/binds.lisp

Adds [ZQ](https://vimdoc.sourceforge.net/htmldoc/editing.html#ZQ) to vi mode.
This solve the #1189

Adds ZQ to vi mode

---

frontends/sdl2/keyboard.lisp

Allow ALT_R as a modifier

---

extensions/legit/legit.lisp
extensions/legit/peek-legit.lisp
extensions/legit/porcelain.lisp

if changes were staged, unstage them first,
then use "k" on a file of the "unstaged changes" section.
This asks confirmation.
Only git right now.

legit: discard changes to unstaged file

---

extensions/welcome/lem-welcome.asd
extensions/welcome/welcome.lisp
lem.asd

Add an extension package to print a nice welcome screen on startup.
ncurses screenshot:
sdl2 screenshot:
adding color should be possible but I am not sure how to use ANSI escape codes in a buffer.

welcome page

---

extensions/welcome/welcome.lisp

Made the global mutable variables have earmuffs, as per the recommended styles.
I forgot to be doing this lately...

Welcome page style cleanup

---

extensions/color-preview/color-preview.lisp
frontends/sdl2/color-picker.lisp
frontends/sdl2/lem-sdl2.asd
frontends/sdl2/tree.lisp
src/internal-packages.lisp

[Screencast from 2024-01-29 23-15-45.webm](https://github.com/lem-project/lem/assets/13656378/73ae1668-dd19-4400-bd01-f03bd6b318c1)

Add color-picker in SDL2

---

contrib/mouse-sgr1006/lem-mouse-sgr1006.asd
extensions/color-preview/lem-color-preview.asd
extensions/documentation-mode/lem-documentation-mode.asd
extensions/elixir-mode/lem-elixir-mode.asd
extensions/go-mode/lem-go-mode.asd
extensions/json-mode/lem-json-mode.asd
extensions/lisp-mode/lem-lisp-mode.asd
extensions/scala-mode/lem-scala-mode.asd
extensions/shell-mode/lem-shell-mode.asd
extensions/swift-mode/lem-swift-mode.asd
extensions/typescript-mode/lem-typescript-mode.asd
lem.asd
lib/encodings/lem-encodings.asd
lib/language-client/lem-language-client.asd
lib/lsp-base/lem-lsp-base.asd

In preparing lem for inclusion in the ocicl repo, I needed to fix these .asd files to add missing dependencies.

Add missing dependencies to .asd files.

---

.github/workflows/test.yml
Dockerfile
README.md

Nothing earth-shattering here, changes documented in the commits but I'll summarize here as well as provide the necessary post-merge setup
The qlot image that this is based on installs qlot to the root user only, which breaks when trying to run the container as a user other than root. The reason for alpine is it produces a smaller image (200MB smaller) and otherwise runs just fine. Happy to revert this commit if needed, the main reason for the PR is the second point
Since it's free, might as well take advantage of hosting an image on github so that users don't have to build their own and deal with the issues associated (like #1271). You can see the result of the build [on my fork](https://github.com/elken/lem/pkgs/container/lem) and the only bit of post-merge setup is go to …

Container improvements

---

.github/workflows/test.yml

Due to a rebase, these were dropped for some reason...
Follow-up to #1318

Include missed env values

---

src/buffer/internal/basic.lisp
src/buffer/internal/buffer.lisp

I kept a couple japanese sentences when I wasn't totally sure of the translation. Also it could help fellow japanese contributors. I am sorry for english predominance[0].
[0]: I'd prefer french like in the 18th century :p

translate docstrings: buffer, basic

---

src/commands/help.lisp

add completion to apropos-command

---

extensions/lisp-mode/repl.lisp

I've extended the regex used to parse graphics control codes in the repl and shell to catch and discard other ANSI escape codes as well.

Handle ANSI escape codes.

---

contrib/calc-mode/main.lisp

Use maybe-load-systems, not maybe-quickload.

maybe-load-systems, not maybe-quickload

---

extensions/vi-mode/ex-command.lisp
extensions/vi-mode/tests/ex.lisp

Bugfix substitution next line of visual line selection in vil mode.

Bugfix out-of-range substitution of vi visual mode

---

src/defcommand.lisp

This is a fix to stop https://github.com/lem-project/lem/pull/1378

Fix doc-strings

---

extensions/markdown-mode/preview.lisp

[docstrings] markdown preview: add command docstring and package documentation

---

extensions/lisp-mode/internal-package.lisp
extensions/lisp-mode/macroexpand.lisp

This makes it possible to set up custom keybinds for these commands

Export symbols for some commands from relevant packages

---

src/commands/project.lisp

Export all project-related commands

---

qlfile.lock

Bump base16 commit

---

src/buffer/internal/basic.lisp
src/ext/grep.lisp

Character offset doc

---

extensions/lem-dashboard/dashboard-items.lisp

The dashboard was just going off the buffer text for the file/project path. This doesn't work well with big fonts or a small window since the text can get truncated. This PR moves it so it's inside a text property instead.

Store dashboard links in text property

---

src/ext/grep.lisp
src/ext/peek-source.lisp

Adds a couple minor grep improvements:
- `n`/`p` for navigation
- `a` takes you to the start of the content in the current line

Minor grep improvements

---

src/ext/listener-mode.lisp

Use like this (in `init.lisp`):
```lisp
(define-key lem/listener-mode:*listener-mode-keymap* "M-p" 'lem/listener-mode:listener-previous-startswith-input)
(define-key lem/listener-mode:*listener-mode-keymap* "M-n" 'lem/listener-mode:listener-next-startswith-input)
```
This is the behaviour I currently have in emacs. No idea where it came from but I like it so I implemented it for Lem too.

List listener history filtering by prefix

---

extensions/vi-mode/commands.lisp

Followup to https://github.com/lem-project/lem/pull/1559
1. `point` encapsulation.
2. It changed `forward-matching-paren` and `backward-matching-paren` behaviour too. Restored it.

Make use of the paren-finding logic only on %

---

src/macros.lisp

Replace lem-base with lem-core, refactor so that only that which we profile gets unprofiled.

macros: fix with-profile

---

src/ext/frame-multiplexer.lisp

https://github.com/lem-project/lem/issues/1595

add `frame-multiplexer-switch-{n}` command

---

extensions/lisp-mode/grammar.lisp
extensions/lisp-mode/repl.lisp

close https://github.com/lem-project/lem/issues/1623

Highlight warning in REPL

---

extensions/lisp-mode/connection.lisp
extensions/lisp-mode/lem-lisp-mode.asd
extensions/lisp-mode/read-only-sources.lisp
lem.asd
src/ext/read-only-sources.lisp

Derrived from https://github.com/lem-project/lem/pull/1656

open the source code of the sbcl as read-only

---

src/ext/line-numbers.lisp

Deduplicate compute-line calls

---

frontends/sdl2/keyboard.lisp

i have seen people do this from time to time, namely using one of the gui mods as an extra modifier.  on my keyboard, i have an extra gui mod for this purpose, two left guis on both sides and two right gui mods on both sides

turn right gui mod into the hyper modifier in sdl2 version

---

frontends/ncurses/cl-charms-pdcurseswin32.lisp
frontends/ncurses/lem-ncurses.asd
frontends/ncurses/ncurses.lisp

have a conversation with hamayama-san about pdcurses https://github.com/Hamayama/PDCurses-win10-jp-package/issues/1

Less pdcurses in ncurses

---

extensions/legit/legit.lisp

chore: update legit.lisp

---

src/ext/peek-source.lisp

If "peek source" window was already open when a new one was opened then the first one was never removed from the view and it was not possible to close it afterwards.
For example second M-x grep before previous grep window is closed can reproduce this bug.

Bugfix: peek source window remains stuck in the view

---

src/ext/filer.lisp

Hello, I'm adding the filer-delete-select (C-c C-d) command to delete selected file.

Add filer-delete-select for filer mode

---

extensions/lem-dashboard/lem-dashboard.lisp

Redraw dashboard when other window is selected

---

frontends/sdl2/font.lisp

the same as on linux will work here

Add get-font-list config for mac

---

src/ext/grep.lisp

when changing the grep command and arguments in a Lem session, we want to change *last-query* too,
otherwise the grep command presents us a command that is the previous grep command.
Also, this functions sets 4 variables at once,
and allows to easily get the default grep arguments back.
Usage:
LEM/GREP> (change-grep-command "rg" :args "--no-heading -n" :input "test") "rg"
"--no-heading -n"
"rg --no-heading -n test"
LEM/GREP> (change-grep-command "git grep")
"git grep"
"-nHI"
"git grep -nHI "

grep: add change-grep-command

---

src/internal-packages.lisp
src/lem.lisp
src/system.lisp

Set PATH properly in macOS (Discussion #1864)

New `lem-core:exec-path` for PATH in macOS

---

src/interface.lisp
src/internal-packages.lisp

`lem-if:set-font-name` -> `lem-core:set-font-name`

change font api

---

src/commands/other.lisp

Changes to remove the Emacs-like feel

"M-x " -> "Comamnd: "

---

frontends/sdl2/sdl2.lisp
frontends/server/main.lisp
src/buffer/internal/buffer.lisp
src/buffer/package.lisp
src/common/character/icon.lisp
src/ext/list-buffers.lisp
src/ext/multi-column-list.lisp
src/interface.lisp
src/internal-packages.lisp

Change appearance of list buffers

---

extensions/markdown-mode/interactive.lisp

We can eval and print Python code blocks.
```python
import os
print "test"
print os.getcwd()
```
```result
test
/home/vince/bacasable/lisp-projects/lem
```
note that the check of `when-markdown-mode` doesn't work anymore.
```lisp
(if (eq 'lem-markdown-mode:markdown-mode
(buffer-major-mode (current-buffer)))
(progn ,@body)
```
since in a code block, we use the language's major mode.
I disabled the check

markdown interactive: add Python eval

---

src/ext/completion-mode.lisp
src/ext/prompt-window.lisp
src/prompt.lisp

Synchronize the position and size of the prompt-window and completion-window

---

STYLEGUIDE.md

it was probably a mistypo, so I corrected it because I got a bit confuse when I first read as english is not my first language, I thought it was some word I didn't know.

fix(styleguide.md): rething corrected to rethink

---

frontends/server/main.lisp
lem.asd
src/buffer/line.lisp
src/commands/sprof.lisp
src/display/base.lisp
src/display/logical-line.lisp
src/display/physical-line.lisp
src/interface.lisp
src/internal-packages.lisp
src/lem.lisp

[Screencast from 2025-08-21 21-37-59.webm](https://github.com/user-attachments/assets/99855457-a882-4a0e-851f-73218114d646)
left: before optimization
right: after optimization

Optimize performance

---

extensions/lisp-mode/lisp-mode.lisp

improve pop-up messages after compilation in lisp-mode
