io.lisp

Don't crash when write-squence is called on buffer-output-stream with string

---

lem.ros

This change intend make it portable for non-sbcl lisps.
It include experimental patch for preloading sbcl specific modules.
This change might have bad effect.
ccl等で絶望的になりそうな部分を多少、動きそうな感じにしました。
ついでにSBCL_HOMEが無くても大丈夫なようにdumpする前にrequireしておくという暴挙を実験してみてます。
悪影響はあるかもしれませんが…モジュールがみつからなくてロード出来ない事態が多少回避出来ているので様子を見たい所です。

make lem.ros loadable for lisps other than sbcl.

---

roswell/lem.ros

roswellが入っている前提でのlemのセットアップ(lemだけの事を考えているわけではないのですが…)を少し便利にしました。
roswellのバージョン
```
% ros --version
roswell 0.0.6.62(22c0787)  #0.0.6.62以前のリリースだと動きません。
```
セットアップ
```
% ros install snmsts/lem # githubの内容をgitでチェックアウトします。
% rm ~/.roswell/local-projects/system-index.txt  # これが必要なのは現状のroswellのバグです。調査してroswellの方を直します
% ros install lem # lemのroswellディレクトリの中身を~/.roswell/bin/以下にコピーします。
% ros setup # ~/.roswell/lemの利用dumpがroswellになっているのでlemを含めたdumpを生成します。
```
```
% ~/.roswell/lem
```
もうすこしセットアップの手数を減らすつもりですが(``ros install snmsts/lem``だけとか)、スクリプト自体の仕様はかえずに動くようにするので、邪魔に感じなければ取り込んでいただけると嬉しいです。

ros installでの簡単セットアップ

---

roswell/lem.ros

sorry my decision was not good.
I notice sharing same image name cause slow down when making image file and affected by broken each other.
稀にlemのパッケージ変更の為にroswellの開発中のイメージダンプに失敗したりしました。
あとlemに一切変更していなくてもload→dumpまでの時間が余計にかかるので、
分離した方が良いかな…と思いました。ディスク容量で少し損する以外はとりたててダメージは無いかと思いますので問題なさそうであれば宜しく願います。

separate from roswell's image file.

---

lem-core/init.lisp
lem-core/lem.lisp
roswell/lem.ros

~/.lemrcに
```
;;-*- mode:lisp -*-                                                                                                                                                                           
(ql:quickload :swank :silent t)
(swank:create-server :dont-close t)
```
としているのですが、起動は遅いしstderrorに出力が出てきて最初から画面が崩れるしで良いこと無いので、
lemのdump時にユーザが追加のコードをloadできるようにすることと、
lemの起動時にwindowの類を初期化する前にコードの実行ができるように少し考えました。
マージ後の整理は必要かと思いますが、どうかよろしくお願いします。
あと混じってしまいましたが``(truename ".")`` はpwdが削除済みの場合エラーをおこします。

load `~/.lem/site-init.lisp` before dump core.

---

lem-core/help-command.lisp

小文字にするのは趣味ですが、undefined-keyの非表示は万人が嬉しいかと思います。

describe-bindings not show 'undeined-key' and downcase function name.

---

lem-core/defcommand.lisp

define-command changed not to return gensymd symbol

---

lem-core/command.lisp
lem-core/dired.lisp
lem-core/grep.lisp
lem-core/gtags.lisp
lem-go-mode/go-mode.lisp
test/lisp-indent.ros

Hi. I found a dired's bug and fixed it.
1. make directory such that the path string has space(s)
2. `find-file` with the path above
- `find-file` with `/path/to/space included/dir/`
```
Subprocess with command "LANG=en; ls -al /path/to/space included/dir/"
Backtrace for: #<SB-THREAD:THREAD "editor" RUNNING {1002ECF3E3}>
0: ((LAMBDA NIL :IN UIOP/IMAGE:PRINT-BACKTRACE))
1: ((FLET "THUNK" :IN UIOP/STREAM:CALL-WITH-SAFE-IO-SYNTAX))
...
7: (CERROR "IGNORE-ERROR-STATUS" UIOP/RUN-PROGRAM:SUBPROCESS-ERROR :COMMAND "LANG=en; ls -al /path/to/space included/dir/" :CODE 2 :PROCESS NIL)
...
```
I think that some lines of these has same probrem about path quotation...🤔
At second commit, I fixed part of these.
```
~/code/lem$ git grep run-program
lem-core/command.lisp: …
```

Dired cannot list files in path that has space(s)

---

lem-core/word-command.lisp

This PR implement `count-words` command.
It counts up three things: number of words, line and characters, and prints them to mini buffer. Also it is bound to `M-=` like emacs.

count-words command

---

.gitignore
lem-frontend-electron/.gitignore
lem-frontend-electron/cli.js
lem-frontend-electron/package.json
package.json

Hi, there. This request is **not complete** but it currently works like this.
```
$ npm insall -g asciian/lem#npm-installable
```
If you merged, we can do this on your repository `npm install -g cxxxr/lem`.
These command will install a binary of frontend-electron as /usr/local/bin/lem.
When we type `lem`, shell calls `~/.roswell/bin/lem` before `/usr/local/bin/lem`.
So, now, we cannot  use `/usr/local/bin/lem`. To solve this issue,  you should change the name of frontend-electron. I propose these nickname, `lemon` and `golem`.
Thanks!

npm installable

---

lem-core/help-command.lisp

This happens in the initial tmp buffer, making `describe-bindings` crash.  A simple check prints null bindings without flattening the null keymap.

describe-bindings-internal crashed on null keymap.

---

lem-frontend-xcb/global.lisp
lem-frontend-xcb/lem-xcb.asd
lem-frontend-xcb/xcb-app/ft2.lisp
lem-frontend-xcb/xcb-app/geometry.lisp
lem-frontend-xcb/xcb-app/lemwin.lisp
lem-frontend-xcb/xcb-app/window-direct.lisp
lem-frontend-xcb/xcb-app/window-double.lisp
lem-frontend-xcb/xcb-app/xcb-system.lisp

Refactored double-buffer;
Thread-safety features:
During interactive resizing, editor thread occasionally crashed the UI thread by injecting events while pixmaps were being reallocated.  This happened only when debug messages created an opportunity for thread switch - possibly never without, but it's better to be thread-safe than thread-sorry.

XCB refactoring and cleanup; thread-safe.

---

lem-frontend-xcb/xcb-app/ft2.lisp
lem-frontend-xcb/xcb-app/lemwin.lisp
lem-frontend-xcb/xcb-app/xcb-system.lisp

Moved Freetype2 initialization into `(interface-invoke)` editor-thread callback.  Freetype2 is not thread-safe and must be used in a single thread.  Since some glyphs (Kanji etc.) are loaded during printing, the editor thread must be used to initialize Freetype2, while the input loop runs in a different thread...  
It still does not handle double-width characters well, but at least it does not lock up as before.

Font handling still not right, but at least does not crash

---

lem-frontend-capi/main.lisp
lem-frontend-electron/lem-electron-backend/main.lisp
lem-frontend-ncurses/ncurses.lisp
lem-frontend-xcb/global.lisp

should we use ``lem::*implementation*`` ?

set *features* for each frontend

---

lem-core/showparen.lisp

```
(define-command toggle-show-paren (&optional (p (not *show-paren-timer*))) () 
```
こう書きたいけど駄目なものでしょうか?意図が無いならassert外しちゃいますが。
I would like to use above expression. if there's no intention, I would like to remove assertion which prevent it.

refactor(rewrite?) show-paren

---

roswell/lem-ncurses-ccl.ros

This PR simply add a ros script which uses ccl-bin instead of sbcl-bin. 
It is useful when use lem on the platforms on which SBCL has no thread supports such as raspberry pi. 
Originally, it is what personally I use on my chromebook. (see also #59)
Sorry for bad English.
このPRは単にsbcl-binの代わりにccl-binを使用するrosスクリプトを追加しただけです．
ラズパイのようなSBCLのスレッドサポートがないプラットフォームで有用と思います．
元々は，私が個人的にchromebookで使っているものです．(#59 の話です)

Add `ncurses-ccl` frontend for platforms on which SBCL has no thread support

---

package.json

This request solve #165 . When npm installs package, npm tests the version of package. The version must use Semantic Versioning. When you updates version number of package.json, you will needs to use that. Thank you.

Change version to correct format

---

lem-frontend-electron/lem-editor/keyevent.js

Tested on macOS™.
On the os, key sequence Alt-option + X generates M-≈ but not M-x by default. that causes lem-rpc crashed.
There're few resorts we can take to resolve this issue on the application layer, or accurately a browser context. Nevertheless remapping the code to the value is a way.

fix M-x crash problem for frontend based on electron.

---

lem-frontend-electron/lem-editor/keyevent.js
package.json

add keyboard-layout package from atom.
the convert power comes from UCKeyTranslate on macOS.
if it works, the only disadvantage is that keyboard-layout brings native binary code dependency to this project, not that pure.
may the users not care.
incidentally, do `npm install` at project root directory to update the project dependency chain first before test.

add a dependency: keyboard-layout to handle different keyboard layout

---

lem-lisp-mode/lisp-mode.lisp

on `lisp-connection-list` chose a connection would close the menu.

close menu-mode when selected on lisp connections

---

lem-vi-mode/ex-command.lisp

`:e` in vi-mode finds files from the current directory, not current buffer's directory.

[vi-mode] Find file from the current buffer directory with ':e'

---

lem-vi-mode/ex.lisp

It's almost the same as `minibuffer-file-complete` except the complete insertion offsets.

[vi-mode] File name completion for :e

---

lem-core/interp.lisp

minimum support to distinguish current context of command-hook.
to know the information ``this-command`` are bound on emacs case.

pre/post-command-hook with command-name

---

lem-css-mode/css-mode.lisp
lem-css-mode/lem-css-mode.asd
lem.asd

I write major mode for css syntax highlight.
1. simple syntax highlight (atkeywords, properties, values, selectors) for css2.2, and html5
2. calculate indent depth (unit is two spaces)

add: css-mode

---

lem-vi-mode/commands.lisp

[vi-mode] Don't add newlines before/after kill-rings of 'd'.

---

lem-vi-mode/commands.lisp

`dd` removes the line but `cc` doesn't.

[vi-mode] Fix 'cc' not to remove the line.

---

lem-core/command.lisp
lem-vi-mode/commands.lisp

Break at 2e8b1854edc7848629d8943f590c586ad8e086ec on #248 because of calling `previous-line` without arguments.

[vi-mode] Fix 'cc' to work

---

lem-encodings/lem-encodings.asd
lem-encodings/utf-16.lisp

This PR makes lem read/write UTF-16 files with this settings:
```
(setf lem:*default-external-format* :utf-16)
(setf lem:*default-external-format* :utf-16be)
(setf lem:*default-external-format* :utf-16le)
```

Support UTF-16

---

lem-core/command.lisp
lem-core/kill.lisp
lem-vi-mode/binds.lisp

In Evil, it allows to choose a yank in history by `C-p` and `C-n`.

Add Evil's yank-pop/yank-pop-next for choosing yank in history.

---

lem-encodings/8bit.lisp
lem-encodings/lem-encodings.asd

I try ```$ ros update lem```. However, following error message was displayed
```
[1/3] System 'lem' found. Loading the system..
; 
; caught ERROR:
;   READ error during COMPILE-FILE:
;   
;     Package LEM-ENCODINGS/TABLE does not exist.
;   
;       Line: 7, Column: 47, File-Position: 304
;   
;       Stream: #<SB-INT:FORM-TRACKING-STREAM for "file /home/satoaki/.roswell/local-projects/cxxxr/lem/lem-encodings/8bit.lisp" {10058C2EB3}>
Aborted during step [1/3].
Unhandled UIOP/LISP-BUILD:COMPILE-FILE-ERROR in thread #<SB-THREAD:THREAD "main thread" RUNNING
{1001928083}>:
COMPILE-FILE-ERROR while compiling #<CL-SOURCE-FILE "lem-encodings" "8bit">
```
So, I try fix this phenomena. However, I'm worried this correction.
Could you check this correction is correct or no? 
Thank you.

fix: package-dependency

---

contrib/bracket-paren-mode/bracket-paren-mode.lisp
contrib/bracket-paren-mode/lem-bracket-paren-mode.asd

bracket paren minor mode
any closed bracket/parentheses(")","}","]") is converted to one
correspondence to opening bracket/parentheses.

bracket paren minor mode

---

frontends/ncurses/term.lisp
frontends/pdcurses/ncurses-pdcurseswin32.lisp

Windows 上の lem-pdcurses の表示について、少しデバッグや改善を行いました。
- C-| を C-_ (Redo) に変換する処理を追加
(PDCurses が C-_ のイベントを上げられないため)
- 補完メニューの表示が日本語表示のところでずれる件の対策
(まだ若干ずれるケースがありますが。。。)
- サロゲートペアの文字の表示の改善
(ある程度表示できるようになりました。まだ若干ずれるケースがあります。。。)
- ConEmu 対応
ConEmu の設定は、Settings - Features - ANSI and xterm sequences を OFF にする必要があります。
また、pdcurses.dll にパスが通っている必要があります。
起動方法は以下のようになります。
```
ros -Q -s lem-pdcurses -L sbcl-bin -- %USERPROFILE%\.roswell\lisp\quicklisp\bin\lem-ncurses
```
- cmd.exe (コマンドプロンプト) 対応
pdcurses.dll にパスが通っている必要があります。
起動方法は以下のようになります。
```
ros -Q -s lem-pdcurses -L sbcl-bin -- %USERPROFILE%\.roswell\lisp\quicklisp\bin\lem-ncurses
```
- その他、表示のデバッグ等

Fix and enhancement of lem-pdcurses on windows

---

frontends/pdcurses/ncurses-pdcurseswin32.lisp

PDCurses でしばしば画面が乱れる件ですが、やっと原因が分かったため対策しました。
PDCurses の getch が、内部で wrefresh を呼んでおり、
Lem の入力用スレッドと本体スレッドの両方から画面を更新していました。。。
対策として、charms/ll:newpad で作成したダミーの画面で getch を発行するようにしました。
(参考URL:
https://github.com/wmcbrine/PDCurses/blob/b7135bc906413898c13e47ec9e154ce3d642c939/pdcurses/getch.c#L193
https://stackoverflow.com/questions/19748685/curses-library-why-does-getch-clear-my-screen )
これでだいぶ表示が安定すると思います。
その他、少し修正しました。
( M-( と M-) が使えない件の対応。lem-if:redraw-view-after の処理見直し等)
また、本修正により、ConEmu の ansi color 設定 が ON でも、
(事前に chcp 65001 を実行しておけば) 正常に表示できるようになりました。

Fix display problem of pdcurses

---

modes/scheme-mode/grammer.lisp
modes/scheme-mode/lem-scheme-mode.asd
modes/scheme-mode/package.lisp
modes/scheme-mode/scheme-mode.lisp

Scheme モードに eval の機能を追加しました。
C-c C-e で直前の式を評価します。
C-c C-r でリージョンを評価します。
デフォルトでは gosh -i を起動します。
非同期通信には lem-process (async-process) を使用しています。
async-process のインストール方法は、
ros install cxxxr/async-process
で、エラーが出るので、インストール先フォルダで、
./bootstrap
を実行です。
(暫定かもしれませんが。。。)
あと、ハイライト処理をいくつか修正しました。
(defineの関数定義、make- 、正規表現(Gauche用)、shebangコメント(Gauche用))
`*global-keymap*` 対応ありがとうございます。
async-process もよい感じです。

Add eval function to scheme mode

---

modes/scheme-mode/eval.lisp
modes/scheme-mode/grammer.lisp

scheme process buffer を scheme mode に設定するようにしました。
これにより、バッファ内で C-c C-e で評価が可能になりました。
(本物の repl のように enter で評価はできませんが。。。)
また、scheme のプロセスが終了していたら、再起動するようにしました。
あとハイライトを1箇所だけ修正しました。

Set scheme process buffer to scheme mode

---

lib/core/command.lisp

porting of mark-whole-buffer("C-x h") of emacs.

[Add] mark-set-whole-buffer

---

modes/nim-mode/nim-mode.lisp

- some keywords added in Nim 0.19.0
- hilight types and operators
This PR hilight identifiers if the identifiers have same name as built-in types. For example, an image below, an identifier `seq` should not be hilighted:

nim-mode follows nim v0.19.0 syntax

---

frontends/pdcurses/ncurses-pdcurseswin32.lisp

lem-pdcurses で、いくつかのキーを使用可能にしました。
```
C-Delete     (delete-word)
M-Delete     (none)
M-Backspace  (backward-delete-word)
M-Home       (move-to-beginning-of-buffer)
M-End        (move-to-end-of-buffer)
M-PageUp     (none)
M-PageDown   (none)
M-^          (delete-indentation)
M-\          (none)
```

Enable several keys on lem-pdcurses

---

frontends/pdcurses/ncurses-pdcurseswin32.lisp

lem-pdcurses ですが、いろいろ触っていて、1件見つけたため修正しました。
マウスクリックの座標を取るところ ( mouse-get-pos-x ) で、
C-x 3 で画面を横分割して、右側の画面をクリックした場合に、
左側の画面情報を使って、座標を計算してしまっていました。
この処理は、ConEmu のときのみ使用されるため、
ConEmu 上で画面を横分割した場合のみ、不具合になります。
(テスト時は、左右同じ表示にしていたようで、気が付きませんでした。。。)
また、変数名の統一やコメント等、ロジックに影響のない範囲で、少し見直しをしました。

Fix mouse click position on lem-pdcurses

---

lib/core/interface.lisp

If you mark, then scroll down, then scroll up and have the cursor on the first line, it renders wrong. 
1. setting the mark
2. scrolling down
3. almost there
4. incorrectly colors the rest

Fix disp-set-overlay for one line

---

modes/lisp-mode/util.lisp

M-x start-lisp-repl を実行したときに、
usocket:socket-error ではなく sb-bsd-sockets:socket-error が発生していて、
キャッチできずエラーになることがあったため、判定を追加してみました。
エラー時のログは以下です。
```
Socket error in "bind": 10013 (アクセス許可で禁じられた方法でソケットにアクセスしようとしました。)
Backtrace for: #<SB-THREAD:THREAD "editor" RUNNING {10045F0BB3}>
0: ((LAMBDA NIL :IN UIOP/IMAGE:PRINT-BACKTRACE))
1: ((FLET "THUNK" :IN UIOP/STREAM:CALL-WITH-SAFE-IO-SYNTAX))
2: (SB-IMPL::%WITH-STANDARD-IO-SYNTAX #<CLOSURE (FLET "THUNK" :IN UIOP/STREAM:CALL-WITH-SAFE-IO-SYNTAX) {2E9EBCB}>)
3: (UIOP/STREAM:CALL-WITH-SAFE-IO-SYNTAX #<CLOSURE (LAMBDA NIL :IN UIOP/IMAGE:PRINT-BACKTRACE) {100723EB0B}> :PACKAGE :CL)
4: (LEM:POP-UP-BACKTRACE #<SB-BSD-SOCKETS:SOCKET-ERROR {1007146E43}>)
5: ((FLET "H0" :IN LEM::COMMAND-LOOP) #<SB-BSD-SOCKETS:SOCKET-ERROR {1007146E43}>)
6: …
```

Fix sbcl usocket error

---

modes/lisp-mode/lisp-mode.lisp

Windows 上で、lisp-mode に入ったり、M-x start-lisp-repl を実行すると、
CPU を 25% 程度消費し続けていました。
ループしている場所が分かったので、(sleep 0.001) を入れたところ、0% になりました。
どうも、message-waiting-p (usocket:wait-for-input) が、タイムアウト指定を無視して、
(戻り値が NIL のときでも) すぐに戻ってきているようでした。

Reduce cpu usage in lisp-mode on Windows

---

frontends/ncurses/term.lisp

MSYS2 の mintty 上で、winpty をかませて lem を起動したときに、
RGB 色の R と B が逆になって表示されていたため、
init.lisp で設定を可能にしてみました。
本変更を適用後、
init.lisp に以下のように記述することで、R と B が他の環境と同じになります。
```
;; for windows pdcurses
#+(and win32 lem-ncurses)
(progn
;; color setting
(lem.term:term-set-color  0 #x00 #x00 #x00)
(lem.term:term-set-color  1 #x00 #x00 #x80)
(lem.term:term-set-color  2 #x00 #x80 #x00)
(lem.term:term-set-color  3 #x00 #x80 #x80)
(lem.term:term-set-color  4 #x80 #x00 #x00)
(lem.term:term-set-color  5 #x80 #x00 #x80)
(lem.term:term-set-color  6 #x80 #x80 #x00)
(lem.term:term-set-color  7 #xc0 #xc0 #xc0)
(lem.term:term-set-color  8 #x80 #x80 #x80)
(lem.term:term-set-color  9 #x00 #x00 #xff)
(lem.term:term-set-color 10 #x00 #xff #x00)
(lem.term:term-set-color 11 #x00 #xff #xff)
(lem.term:term-set-color 12 #xff #x00 …
```

Enable terminal color setting

---

frontends/pdcurses/ncurses-pdcurseswin32.lisp

- lem-pdcurses には、ワイド文字に関する処理がいろいろと入っていますが、
もう少し整理しようと思い、
windows-term-setting クラスを追加してみました。
- ワイド文字対応の処理は、主に以下の３種類の幅の変換になっています。
(1) 表示の幅
(2) 位置(座標)の幅 (例えば、Windows コンソールでは、Unicode のサロゲートペアの文字が 2 で、それ以外の文字が 1 になります)
(3) カーソル移動の幅 (例えば、mintty では表示の幅で指定、ConEmu では位置の幅で指定、というように異なります)
- それぞれについて、変換あり / 変換なし / 関数によるカスタマイズ、を、
`*windows-term-setting*` のプロパティで選択できるようにしました。
デフォルトの設定は、以下のようにしています。
|タイプ|表示の幅|位置の幅|カーソル移動の幅
|---|---|---|---|
|mintty |○|○|○|
|ConEmu |○|○|×|
|cmd.exe|×|×|×|
○:変換あり
×:変換なし
- これで、今後、対応する端末のタイプが増えても、
個別の名称で全箇所に分岐を追加する必要がなくなると思います。
(ただ、新しく Windows Terminal というのが出てきていて、
今後は Windows Console API が非推奨になりそうとのことで、
PDCurses 自体が不要になりそうですが。。。)
- 実際には、きれいにいかないケースもあって、現状、それらは個別に対応しています。
例えば、以下があります。
1. 画面を左右に分割すると、lem が右画面を先に表示するケースがあり、
単純に左端から幅をカウントしていると、後から左画面を更新されて、 …

Add windows terminal setting to lem-pdcurses

---

frontends/pdcurses/ncurses-pdcurseswin32.lisp

mintty 上で winpty をかませて lem-pdcurses を実行した場合に、
画面のリサイズに失敗することがあったため、修正しました。
入力として resize イベントが上がってくるのですが、
実際に画面サイズが変わるまでにラグがあるようで、
charms/ll:resizeterm をすぐに実行すると、
PDCurses 内部が古いサイズのままになることがありました。
また、charms/ll:resizeterm がエラーで戻ってきた場合に、
一度 charms/ll:resizeterm が成功するまでは、
PDCurses が、次の resize イベントを上げないようになっていたため、
エラー時には、現状サイズで一度 charms/ll:resizeterm を実行するようにしました。

Fix window resize on lem-pdcurses

---

frontends/pdcurses/ncurses-pdcurseswin32.lisp

- #380 の続きで、処理の見直しを行いました。
- disp-char-width, pos-char-width, cur-char-width を defmethod にしてみました。
- マウスの処理の修正/見直し (分割線のマウスによる移動がうまくできないケースがありました)
- エラーチェックの追加等
- 今回、ざっとですがテストをしたので、結果を以下に載せておきます。
https://gist.github.com/Hamayama/452e4cc31ad9a5c479dad0b88613888f
( init.lisp 有りと無しの場合について、(1) mintty + winpty, (2) ConEmu, (3) cmd.exe 
の３端末で動作確認しました )
基本的には、大丈夫かと思います。

Refactor lem-pdcurses (char-width processing, mouse function, etc.)

---

README.md

Just added a link to my `.lem/init.lisp` sample config in the README.md.   I didn't want to modify the official `lemrc-example` but I can add a new file such as `lemrc-example2`, etc, if you prefer.

Add an additional config example

---

lib/core/list-buffers.lisp
lib/core/menu-mode.lisp

C-x C-b (または M-x list-buffers) で buffer menu の画面を出したときに、
実際よりも少ない数のバッファが表示されたり、
表示と異なるバッファが選択されてしまったりする件を修正してみました。
(今までは、操作前に g キーを押すことで回避していました)
原因は、表示時点のバッファリストを menu-origin-items に記憶しているのですが、
これが、実際の `*buffer-list*` とポインタが共有されており、
`*buffer-list*` が更新されると、リストの途中を指すようになったりして、
誤動作していました。
対策としては、バッファリストの list-copy をとってから記憶するようにして、
選択時には、記憶内容と実際の `*buffer-list*` を比較し、
異なるときはメッセージを表示して、操作を実行しないようにしました。

Fix buffer menu selection mismatch

---

modes/lisp-mode/lisp-mode.lisp
modes/lisp-mode/swank-protocol.lisp
modes/lisp-mode/util.lisp

Windows 上 で M-x slime を実行すると、固まったり、
応答が表示されなかったり、終了できなくなったりする件を、改善してみました。
- message-waiting-p ( modes/lisp-mode/swank-protocol.lisp )：
Windows 版の sbcl では、
usocket:wait-for-input を呼び出す前にイベントオブジェクトをリセットしないと、
2回目以降の usocket:wait-for-input で、ウェイトしなくなってしまう。
このため、WSAResetEvent でイベントオブジェクトをリセットするようにした。
(本現象は、usocket:wait-for-input の引数にソケットを1個だけ指定したときに発生する。
ソケットが1個だけのときは、内部情報 (wait-list) を毎回作らないで使いまわすようになっており、
イベントオブジェクトも使いまわしになるためリセットが必要だった。。。
https://github.com/usocket/usocket/blob/2b92b917cf9bd763492461b5b9814e801d1b063f/usocket.lisp#L348 )
- port-available-p ( modes/lisp-mode/util.lisp )：
usocket:socket-listen のところで、
:reuse-address t を指定しているが、
複数プロセスが同一ポートで待ち受けして変になるケースがあったため、
:reuse-address nil に変更した。
- start-thread ( modes/lisp-mode/lisp-mode.lisp )：
- 前述の usocket:wait-for-input の対応の結果、 …

Improve slime connection on Windows

---

modes/lisp-mode/repl.lisp

M-x start-lisp-repl と間違えて M-x lisp-repl-mode を実行すると、
Enter を押すたびにエラーが出る状態になってしまうので、
ガードしてメッセージを表示するようにしてみました。

Guard and display message for lisp-repl-mode

---

lib/core/list-buffers.lisp
lib/core/menu-mode.lisp

メニューの整合性をチェックする関数を、
メニュークラスの方に登録できるようにしてみました。
(Buffer Menu 以外のメニューでも使えるように)
あと list-buffers.lisp を少し整理しました。
( `::` を使わない感じで。。。)

Add check-consistency-function to menu class

---

lib/base/syntax.lisp
modes/lisp-mode/repl.lisp

lisp-repl-mode で、以下のような複数行の文字列を入力しようとすると、
エラーになる件を修正しました。
```
"123
456"
```

Fix multi-line string input in lisp-repl-mode

---

lib/core/history.lisp
lib/core/listener-mode.lisp
lib/core/minibuffer.lisp

ヒストリ機能使用中に、編集中の文字列を記憶しておき、元の表示に戻せるようにしました。
最新のヒストリを表示中に M-n を押すと、編集中の文字列の表示に戻します。
例えば、REPL に 12345 まで入力して、M-p でヒストリを呼び出すと、
12345 は消えますが、M-n を繰り返すことで 12345 の表示に戻せます。
ただし、ヒストリを呼び出して編集した場合には、それが新しい編集中の文字列になります。
(古い編集中の文字列の情報は消えます。また、ヒストリデータ自身は変化しません)

Enable history function to backup/restore edit string

---

modes/lisp-mode/lisp-mode.lisp

If `(buffer-value buffer "package")` returned a value that was not
a string designator, and error was signaled and Lem died.
E.g. the file "iterate.lisp" from project `:iterate` contains the
following property list:
```
;;;-*- syntax:COMMON-LISP; Package: (ITERATE :use "COMMON-LISP" :colon-mode :external) -*-
```
Therefore, opening that file and calling `lisp-mode` killed Lem.
Now, wrap call with ignore-errors and use default if NIL is returned.

Fix buffer-package for non-standard package value

---

.travis.yml
lib/setlocale/lem-setlocale.asd

The problem was introduced in:
https://github.com/cxxxr/lem/compare/409827f610fb...9b8f5fe5a2a6
https://travis-ci.org/cxxxr/lem/jobs/551310435
Also, failing tests on Linux now considered insignificant, because they are broken 6 month.
Last successful build on Linux was 2019-01-07:
https://travis-ci.org/cxxxr/lem/builds/476333555
It was broken in https://travis-ci.org/cxxxr/lem/builds/476754077 (https://github.com/cxxxr/lem/compare/d0fe8c93fdb4...591eb96fdc79), but brobably related not to the commit but to the quicklisp version upgrade.

Trying to fix error of building lem on OSX + CCL

---

lib/core/help-command.lisp
lib/core/language-mode.lisp
lib/core/mode.lisp
modes/lisp-mode/lisp-mode.lisp
modes/paredit-mode/paredit-mode.lisp

* list-modes - shows all available modes;
* describe-mode - shows current major mode and enabled minor modes.
Also, each mode now can have a human-readable description and an attribute to distinguish major mode from a minor. You can call
function `is-major` on a symbol, to check if it is a major mode.

Added commands to show information about current mode and all available modes

---

lib/lisp-syntax/indent.lisp

Lem didn't correctly indent Lisp forms whenever the
method registered for a symbol ended in `&rest <integer>.
For instance, `multiple-value-bind` was indented like that:
```
(multiple-value-bind (a b
c d
e f)
g
h)
```
However, it should be:
```
(multiple-value-bind (a b
c d
e f)
g
h)
```
I also added an error-check before setting some Lisp indentation method. Tested error checking all methods both in static and dynamic tables, no error was found. Indentations now is like Emacs in all tests I made.

Complex indent method fix

---

.github/FUNDING.yml

Simply merge this pull request and activate the "Sponsorships" option in lem's project settings to get a cute little "Sponsor" button linking to your [Open Collective account](https://opencollective.com/lem)!
Here's a [preview](https://github.com/Hexstream/lem) of the end result.
Here's the [official documentation](https://help.github.com/en/articles/displaying-a-sponsor-button-in-your-repository) for this nice feature.
(Note that you do not need to be sponsored by GitHub to use this feature.)

Add native GitHub "Sponsor" button linking to Open Collective account

---

lib/base/fileutil.lisp

On SBCL Linux, `(pathname-directory "~/")` returns `(:absolute :home)`,
which `completion-file` don't handle properly.

Fix completion for filenames inside "~"

---

lib/core/file-command.lisp

When openning a file in an non-existing directory `find-file`
and `read-file` ask the user if the directory should be
created before opening the file, aborting when the user
responds 'n'.

Prompt for directory creation when it does not exist

---

lib/core/window-command.lisp

If the user types a wrong buffer name, `select-buffer` asks
whether the user wants to create it.

select-buffer prompt for buffer creation of non-existing buffer

---

frontends/ncurses/ncurses.lisp

This is a my first PR for lem.
---
https://github.com/cxxxr/lem/issues/287
I felt the behavior of lem is slower than vim, too.
I added configurable variable for escape delay.
Default value `100` is taken from vim. c.f. https://vim-jp.org/vimdoc-ja/options.html#'ttimeoutlen'

Make escape-delay configurable

---

lib/core/kill.lisp

Calling `C-y` and `M-y` with an empty kill ring signalled an error. Do nothing instead.

Fix kill-ring-rotate when `*kill-ring*` is empty

---

modes/scheme-mode/errors.lisp
modes/scheme-mode/eval.lisp
modes/scheme-mode/lem-scheme-mode.asd
modes/scheme-mode/lem-scheme-syntax.lisp
modes/scheme-mode/package.lisp
modes/scheme-mode/repl.lisp
modes/scheme-mode/scheme-mode.lisp
modes/scheme-mode/swank-connection.lisp
modes/scheme-mode/swank-protocol.lisp
modes/scheme-mode/syntax-parse.lisp
modes/scheme-mode/util.lisp

scheme-mode に scheme-slime コマンドを追加して、
[r7rs-swank] に接続できるようにしてみました。
--
＜使い方＞
[r7rs-swank] は GitHub から入手して、適当なフォルダに配置が必要です。
init.lisp に、次のように起動コマンドを記述します。
```
(setf lem-scheme-mode:*scheme-swank-server-run-command*
'("gosh" "-AC:/work/r7rs-swank" "-e(begin (import (gauche-swank)) (start-swank ,port))"))
```
(上記は、Scheme 処理系に Gauche を使うときの例です。
`-A` オプションには r7rs-swank のフォルダのパスを指定します。
ポート番号を指定する箇所には `,port` と記述します (lem が内部で実際のポート番号に置換します))
後は、lem を起動して、M-x scheme-slime とすると、
swank-server が起動して、repl のバッファが表示されます。
(細かい使い方については、後でまとめようと思います)
(現状 r7rs-swank に不具合があり、M-x scheme-load-file が失敗します。
プルリクエスト https://github.com/ecraven/r7rs-swank/pull/11 を送っています)
--
＜作業について＞
作業のメモを以下に置いておきます。
https://gist.github.com/Hamayama/37a7c766dca2fd0f3ee42c0147530f94
大体は lisp-mode からのコピーですが、通信関係はけっこう調整が必要でした。 …

[scheme-mode] Add scheme slime function connecting to r7rs-swank

---

modes/lisp-mode/swank-protocol.lisp

scheme-mode の変更を反映しました。
- WSAResetEvent の戻り値の定義見直し
(Win32 API の BOOL は、64bit環境でも32bitのintだった (エラーは出ないようですが。。。))
- message-waiting-p で、ストリームのバッファをまずチェック (listen) するようにした 
(ソケットには未受信データがなくても、
ストリームのバッファには未受信データが残っているケースがあった。
(r7rs-swank との通信では、よく発生した))
- read-message-string で、usocket:wait-for-input のチェックを削除した
(上の関連で、ソケットには未受信データがなくても、
ストリームのバッファには未受信データが残っている場合に、
読み込んでくれなかった)

[lisp-mode] Update swank protocol read message function

---

frontends/pdcurses/ncurses-pdcurseswin32.lisp

- https://github.com/cxxxr/lem/pull/423 の escape-delay に対応しました。
- 今までは、Escape キーの入力があったときにフラグを立てて、
次の入力を M-x として解釈するようにしていました。
しかし、以下の問題がありました。
(1) 単独の Escape キーを入力したあとに、何かキーを押すと M-x になってしまう
(2) C-x M-x のようなキーバインドを入力できない (単独の Escape 入力が間に挟まるため)
- 今回、フラグを削除してタイマーのみにしました。
(lem-ncurses と同じにしました)
- ただ、現状の PDCurses には、
Alt キーと同時押しで入力できない組み合わせがあり (M-<, M->, M-; 等)、
それらを入力するには Escape キーとの組み合わせが必要になります。
- そのときにタイムアウトが 100 msec だと、ちょっと入力できなかったため、
デフォルト値は 1000 msec にしました。
- vi-mode を使用する等で、短い値にしたい場合には、
init.lisp に以下のように記述してください。
```
#+(and win32 lem-ncurses)
(setf (variable-value 'lem-ncurses::escape-delay :global) 100)
```
- あと、いろいろテストしていて、winpty に不具合が見つかったため、報告しました。
https://github.com/rprichard/winpty/pull/175
(現状、mintty+winpty を使用していて、1行目の2～8桁目にカーソルを置いて、
Escape キーを押すと、Escape キーがうまく機能しなくなります。 …

[lem-pdcurses] Use escape-delay variable

---

Makefile.am

Indentation was wrong.
This pull closes issue https://github.com/cxxxr/lem/issues/449

Fixed "target pattern contains no `%'" error from Make.

---

modes/lisp-mode/lisp-mode.lisp

The root of the problem was that on OSX `swank:*communication-style*` is equal to `:fd-handler`
for some reason. In this case `swank:create-server` does not start threads which
accept connections on TCP port and process incoming messages.
To make it work propertly, we need to specify that communication style is `:spawn`.
This commit closes issue https://github.com/cxxxr/lem/issues/411.

Fixed an issue when connection to swank didn't initialized propertly

---

lib/core/lem-core.asd
lib/core/lem.lisp
modes/lisp-mode/lisp-mode.lisp
modes/lisp-mode/swank-protocol.lisp

Two new options were added to control if log should be written to the file:
* `--log-filename /tmp/lem.log` - this will output `INFO`, `WARNING` and `ERROR` messages
to the file.
* `--debug` - with this flag Lem will output also `DEBUG` messages to the log.
This flag should be used along with `--log-filename`.

Added ability to output infmation into the log.

---

lib/core/timer.lisp

Otherwise, there will be a `slot-unbound` error when calling `get-next-timer-timing-ms` or `update-timer`

Don't check timers that have no last-time

---

README.md

This section will list an external contribs which are not available from Lem repository.
We can remove this list when the [package manager](https://github.com/cxxxr/lem/issues/413#issuecomment-525174828) will be available in Lem.

Added a section "Extensions and modes"

---

lib/process/process.lisp

destroy-thread でエラーになると、
delete-process が完了できない状態になったため、
スレッドの状態をチェックするようにしました。

[lem-process] Avoid destroy-thread error in delete-process

---

lib/core/command.lisp
lib/core/window-command.lisp
lib/core/window.lisp

#452 の不具合修正になります。
(参照: https://github.com/cxxxr/lem/pull/452#issuecomment-575975609 )
(1) 一行しかない場合は上下のスクロールができない(論理行でみると次の行が無いことが原因?)
→ scroll-down,scroll-up の処理を修正しました
(下手にメッセージを出そうとして、失敗していました)
(2) window-view-pointが論理行で行頭にない、かつカーソルが1行目の1列目にあるときwindow-cursor-yが1で0ではない(1行目2列目からは0になる)
→ window-cursor-y を修正しました
(これは、よく見つかりましたね。。。)
(3) next-page,previous-pageでスクロール後、カーソルのいる行が前と変わっている(前は画面の真ん中になっていた)
→ next-page,previous-page の処理を修正しました
(n を明示的に指定した場合とは処理が異なりますが、前と同じにはなったかと。。。)

Fix #452 (Workaround for long line display v2)

---

lib/core/listener-mode.lisp
modes/scheme-mode/repl.lisp

listner-mode に入るときに、
listener-point が初期化されていなければ、初期化するようにしました。
これは、repl の接続先が起動できなかった場合に、
Enter キーを押すたびに、listener-return のところでエラーが出ることを防ぎます。

Initialize listener-point when entering listener-mode

---

modes/lisp-mode/swank-protocol.lisp

Issue #460 の対応になります。
(SBCL 版の Lem と CCL 版の swank-server を接続すると、#A の非互換のためエラーになる件)
modes/lisp-mode/swank-protocol.lisp の with-swank-syntax に
`(*print-readably* nil)` を追加しました。
https://github.com/slime/slime/blob/1761172817d2e1a8b48c216bf0d261eb277ae562/swank.lisp
を確認したところ、
`*print-readably*` を t にしているケースはないようでした。
(with-standard-io-syntax 内も)

Set *print-readably* to nil in with-swank-syntax

---

frontends/electron/lem-editor/lem-editor.js

Electronフロントエンドにおいて、ウィンドウをリサイズした際に全てのイベントに対応しようとしてエディター画面のリサイズ追従が追いつかない現象がありました。
そのためイベントに対する感度を鈍くし、最後のリサイズイベントから200ms後に実際のリサイズを実行します。

Reduced the sensitivity of resize events

---

frontends/electron/index.html
frontends/electron/index.js
frontends/electron/lem-editor/lem-editor.js
frontends/electron/lem-editor/option.js
package.json

- LemEditor.calcDisplayCols(), LemEditor.calcDisplayRows() において微調整を不要にしました
- 表示したい行・列数をもとにウインドウをリサイズできる LemEditor.resizeTo() を追加しました
- option.js に initialCols, initialRows を追加し、起動時にこの行列数で表示
- ウインドウを文字サイズ単位でリサイズできるようにします (今のところWindowsのみ)
'will-resize'イベントを処理するため、Electronを更新しました。
ただしこのイベントの処理は今のところWindowsでしか正しく動作しないようです。
- Linux: 未サポート
- MacOS: イベントで渡されるnewBoundsの内容が正しくない場合がある

Editor window will be resized in character size units

---

frontends/electron/lem-editor/lem-editor.js

LinuxやMacOSでも文字サイズ単位でのリサイズになるよう回避策を実装してみました。
- will-resize イベントが使えないため、ユーザーがリサイズした後に再度文字サイズ単位でリサイズします
- 短時間に二重にリサイズするため環境によってちらつきが発生することがあります
- MacOSではElectronが対応すればこの回避策は不要になります (Windowsと同じ処理で良くなる)

Character unit resizing workaround for Linux and MacOS

---

frontends/electron/electron.yml.example
frontends/electron/lem-editor/lem-editor.js
package.json

- Electronフロントエンドのオプションを .lem/electron.yml で設定可能にしました
- electron.ymlでの設定は frontends/electron/lem-editor/option.js の内容を上書きする動作です
- 設定ファイルを直接編集するためコメントアウトできるようYAMLフォーマットとしました
- 設定例を frontends/electron/electron.yml.example に追加しました

Enabled loading user option file

---

contrib/mouse-sgr1006/main.lisp
frontends/ncurses/ncurses.lisp
frontends/pdcurses/ncurses-pdcurseswin32.lisp
lib/core/command.lisp
lib/core/key.lisp
lib/core/lem.lisp

マウスの制御をいろいろと改善しました。
1. isearch (C-s) と マウス操作 と C-g の組み合わせで、落ちる件の対応 (#470)
2. mouse-sgr1006 が有効にならないことがある件の対応
( `*terminal-io*` を lem の起動時に保存しておいて、
そちらに エスケープシーケンス を出力するようにしました。
また、エディタ終了時には OFF にするようにしました )
3. mouse-sgr1006 のマウスホイール対応
(マウスホイールでスクロールするようにしました)
4. 補完メニューを出している間は、マウスクリックを無効化
(変な状態になるため)
5. ミニバッファがアクティブのときは、
マウスクリックでミニバッファにも移動可能とした
6. getch の一時的なタイムアウト設定をマクロ化
(with-getch-input-timeout)
7. mouse-sgr1006 で、charms/ll: の使用を止めた
(getch 関数を、引数で渡すようにしました)
mouse-sgr1006 の確認は、
Windows の VirtualBox 内の Linux Mint 19.3 (Cinnamon) で行いました。
(ターミナルは、GNOME Terminal 3.28.1 )
＜補足＞
mouse-sgr1006 を使う場合は、
M-x site-init-add-dependency で
mouse-sgr1006 の追加が必要です。

Improve mouse control

---

modes/vi-mode/ex-command.lisp

This request adds the `:x` or `:xit` command to VI mode.
It does the same thing as `:wq` except it only writes
when changes have been made.
Part of vi(m) and my go-to key to write and quit.
Open a file, enable VI mode and execute `:x` 
Lem should write to the currently open file and quit.

[vi-mode] Add x[it][!] support to ex-command

---

modes/asm-mode/asm-mode.lisp

I referenced those when writing asm-mode:
- [GNU as](https://sourceware.org/binutils/docs-2.34/as/index.html)
- [rgbasm: assembler for gameboy development](https://rednex.github.io/rgbds/rgbasm.5.html)

asm-mode: note that referenced documents when I was writing it

---

modes/fm-mode/fm-mode.lisp

fm-modeを使用中に画面をリサイズしてフレームを切り替えると`(current-frame)`じゃないフレームはリサイズ時の処理が走らないので表示がおかしなるバグを修正しました。
This PR fixes a bug that breaks rendering result of frames that not `(current-frame)` after resizing window manually in fm-mode.

fm-mode: resize current frame after switching

---

contrib/fbar/fbar.lisp
contrib/mouse-sgr1006/main.lisp
frontends/pdcurses/ncurses-pdcurseswin32.lisp
lib/core/window.lisp

#500 等で削除されたグローバル変数等が、一部ソースに残っていたため削除しました。
確認済み項目：
```
lib/core/minibuffer.lisp
*minibuf-window*             なし
*minibuffer-calls-window*    なし
*minibuffer-start-charpos*   なし
*echoarea-buffer*            なし
*minibuffer-buffer*          なし
lib/core/window.lisp
redraw-display*              なし
*floating-windows*           8個削除
*header-windows*             なし
*modified-floating-windows*  なし
*window-tree*                なし
*current-window*             1個削除
*modify-header-windows*      なし
lib/core/command.lisp
*next-line-prev-column*      1個削除
```

Remove nonexistent global variables

---

modes/fm-mode/fm-mode.lisp

fm-modeのオンオフコマンドの名前を`fm`から`fm-mode`にしました。

Change command name to toggle fm-mode

---

lem.asd
lib/core/frame-multiplexer.lisp
lib/core/lem-core.asd
modes/fm-mode/lem-fm-mode.asd

「fm-modeってmodeじゃないよね」という点と「coreに入れたほうがいいよね」という話があったので、lib/coreにいれました。
あとmodeではないので`frame-multiplexer`としました。
「デフォルトでONでもいいのでは」という話もありましたが、いったんこのPRではやっていません。

Rename and Move 'modes/fm-mode/*' to 'lib/core/frame-multiplexer.lisp'

---

contrib/mouse-sgr1006/main.lisp
frontends/pdcurses/ncurses-pdcurseswin32.lisp

- マウス操作が出来なくなった件の修正になります (関連プルリクエスト #515)。
- ガードの条件を「current-window が floating-window かどうか」だけにしました。
- find-file のファイル名補完の popup-window や、
割り込み表示の typeout-window については、
これでガードできるようでした。
- ただ、言語のキーワード補完の popup-window のように、
この条件にヒットしないケースもあるようでした。
あまり条件を複雑にしたくなかったので、そこは妥協しました。
(マウスクリックすると、言語のキーワード補完の選択表示は消えます)

Fix mouse control on curses frontend v2

---

ChangeLog.md
frontends/ncurses/term.lisp

This pull fixes colour glitches in case if colour theme sets the background and foreground colours and Lem's frontend is NCurses.
Two pictures to illustrate.
Before this patch:
After this patch:

Now if color attribute does not specify foreground or background color, the default color is used explicitly

---

lib/core/config.lisp
lib/core/lem.lisp

Windows 上で、isearch で日本語を検索すると、
config.lisp の読み込みエラーになったため、
エンコーディングを指定するようにしました。
( uiop:read-file-form のソースを調べて、
同じものを with-open-file の :external-format にセットしました)

Set encoding of config.lisp

---

frontends/ncurses/cl-charms-pdcurseswin32.lisp
frontends/ncurses/term.lisp
frontends/pdcurses/ncurses-pdcurseswin32.lisp

- 最近、Windows 10 の PC を入手したのですが、
Windows Console API の動作が変わってしまったようで、
日本語の表示がうまくできなくなっていました。
(Windows Terminal が出来たことで、conhost v2 というものになったようです)
- 大きなところとしては、
SetConsoleCursorPosition() が、Windows 10 では、
文字数ではなく文字幅単位 (全角文字を 2 と数える) で、
X座標を指定するように変わっていました。
(Windows 8.1 までは、( chcp 65001 の場合は) 文字数で指定するようになっていました。
(これは、日本語版 Windows の固有の動作だったのかもしれない。。。))
- それで、ちょっと Lem だけでは修正できなかったため、
PDCurses の改造版を作成してみました。
https://github.com/Hamayama/PDCurses-win10-jp
- 本プルリクエストは、その改造版が入っていた場合に、
処理を分岐して、Windows 10 で日本語の表示ができるようにするものです。
(PDCurses の改造版が見つからなければ、今まで通りの処理になります)

[lem-pdcurses] Try to fix Japanese character display on Windows 10

---

lib/core/popup-window.lisp
lib/core/prompt-window.lisp
lib/core/window.lisp

ポップアップ画面の表示位置を修正しました。
(画面の端で表示させると、はみ出してスクロールしてしまったり (PDCursesだけかも)、
補完の候補をしぼりこむときに、上にずれて表示される 等)

Fix popup window position

---

frontends/pdcurses/ncurses-pdcurseswin32.lisp

lem-pdcurses を、Windows Terminal 上で動かして少し調整しました。
Windows Terminal 上での実行方法は、以下に簡単に記述しておきました。
https://gist.github.com/Hamayama/fc442e71304629527866f7c69c2e9f5e
PDCurses-win10-jp に、VT エスケープシーケンスの処理を追加したため、
Windows Terminal でもマウスで操作できるようになりました。
(カーソルの移動、分割線のドラッグ、ホイールによるスクロールに対応)

[lem-pdcurses] Adjust for Windows Terminal

---

modes/scheme-mode/scheme-mode.lisp
modes/scheme-mode/swank-connection.lisp

autodoc の動作を lisp-mode に合わせました。
(Space または M-a で autodoc を表示するようにしました)
＜関連プルリクエスト＞
#528

[scheme-mode] Fix autodoc display v2

---

frontends/ncurses/ncurses.lisp
frontends/pdcurses/ncurses-pdcurseswin32.lisp
lib/core/popup-window.lisp
lib/core/prompt-window.lisp

popup window と prompt window の表示の修正になります。
VirtualBox 上 の Linux Mint 20 で、動作確認したのですが、
画面の右端に border が表示されると、反転色が漏れ出すことがあるようでした。
このため、ncurses の場合も、`*extra-right-margin*` を設定するようにしました。
また、prompt window についても、popup window と同様の処理を行うようにしました。
これで #533 のコメントの件が直るのかは、ちょっと分かりませんが。。。
(そもそも、#533 では、prompt window の方は触ってない)
＜関連プルリクエスト＞
#525 #530 #533

Fix popup and prompt window display

---

frontends/electron/webview/clhs.lisp
modes/calc-mode/main.lisp

maybe-quickload is in lem, `(asdf:make :lem/executable)` will build failed

fix unknown symbol: maybe-quickload

---

lib/core/frame-multiplexer.lisp

Sorry. In this case, the correct way is enabling via editor-variable.

Fix the way to enable frame-multiplexer

---

modes/lsp-mode/lsp-mode.lisp

This PR defines lsp-mode's language spec for Rust's [rls](https://github.com/rust-lang/rls).

Add LSP spec for Rust's `rls`

---

lib/core/keymap.lisp

Currently, if a key is already bound, attempting to override that
binding produces an error, specifically, if the following config code
is used:
```lisp
(define-key lem-lisp-mode:*lisp-mode-keymap* "," 'my-function)
(define-key lem-lisp-mode:*lisp-mode-keymap* ", ," 'my-other-function)
```
The given error is:
```
The value
MY_FUNCTION
is not of type
HASH-TABLE
when binding HASH-TABLE
```
Which is not particularly helpful.
This commit adjusts the behavior of `define-key` in the above
situation: change the definition of the key to the given definition,
regardless of whether it's already been defined.
---
The alternate solution that occurred to me would be to signal a condition here and ask the user whether they want to override the definition or leave the existing one in place. I can write …

Allow a multi-key sequence to override a single-key definition

---

lib/core/command.lisp
lib/core/directory-mode.lisp
lib/core/file-command.lisp
lib/core/interp.lisp
lib/core/lem.lisp
lib/core/line-numbers.lisp
lib/core/mode.lisp
lib/core/package.lisp
lib/core/rectangle.lisp
lib/core/typeout.lisp
lib/utils/class.lisp
lib/utils/lem-utils.asd
modes/lsp-mode/lsp-mode.lisp
modes/vi-mode/core.lisp

conditionとsignalを用いてコマンド実行前後の処理を外から追加する仕組みを提供する
`*pre-command-hook*` と `*post-command-hook*` は廃止する
主に以下のシンボルを追加
after-executing-command (condition)
before-executing-command (condition)
handle-signal (generic-function)
コマンドの前後にbefore-executing-command, after-executing-commandのサブクラスにsignalを送る
コマンドループの外側でhandler-bindを用いてデフォルトのlem:handle-signalを呼び出すようになっている
拡張の例1
静的に挙動を追加する
```common-lisp
(define-condition foo (after-executing-command) ())
(define-condition bar (before-executing-command) ())
(defmethod handle-signal ((condition foo))
;; コマンド実行前に呼び出される
)
(defmethod handle-signal ((condition bar))
;; コマンド実行後に呼び出される
)
```
拡張の例2
動的にコマンドループに作用させる
```common-lisp
(define-condition hoge (after-executing-command) ())
(handler-bind ((hoge (lambda (c)
(declare (ignorable c))
;; コマンド実行後にここに到達する
;; …
```

Executing command signal

---

modes/vi-mode/commands.lisp

`d$` does not work. replace apply to call-command

Replace apply to call-command

---

src/file-command.lisp

Changes made in src/file-command.lisp
This change adds the variable `delete-trailing-whitespace-on-writing-file` and the defun `clear-trailing-whitespace-on-write`.
I tried to keep it in the same style as `Add-Newline-at-EOF-on-Writing-File` and `add-newline-at-eof`.
I tested by setting the variable to `t`, introducing trailing whitespace in multiple buffers, then saving using `save-current-buffer` and `save-some-buffers` to ensure the whitespace was removed in the proper places.  I then did the same with the variable set to `nil`, and ensured that the whitespace was not removed.

Add var and defun for removing trailing whitespace on save

---

modes/paredit-mode/paredit-mode.lisp
modes/vi-mode/binds.lisp
modes/vi-mode/commands.lisp
modes/vi-mode/core.lisp
modes/vi-mode/ex-command.lisp
modes/vi-mode/ex-core.lisp
modes/vi-mode/ex-parser.lisp
modes/vi-mode/ex.lisp
modes/vi-mode/jump-motions.lisp
modes/vi-mode/vi-mode.lisp
modes/vi-mode/visual.lisp
modes/vi-mode/word.lisp
tests/e2e/vi-mode.lisp

Migrate "." -> "/" to follow new ASDF project package naming conventions.

[VI-MODE] • Migrated lem-vi-mode. -> lem-vi-mode/

---

tests/e2e/vi-mode.lisp

Also notice that `e2e` tests are currently not being run by rove. Is this intentional?

[VI-MODE] • Missing change from vi-mode package name migration

---

modes/vi-mode/commands.lisp

Without this change options are always ignored if clipboard data is present, thus, breaking `yy` & `p` operations.

[VI-MODE] • Temporary work around for macOS issue with global yank

---

modes/vi-mode/core.lisp
modes/vi-mode/visual.lisp
tests/e2e/vi-mode.lisp

Using CLOS to simplify implementation of VI State. Perviously, there was a lot of functions custom handling hooks and state changes.

[VI-MODE] • State CLOS refactor

---

roswell/lem-sdl2.ros

This is a  launcher script enabled when lem is installed via [roswell](https://github.com/roswell/roswell).

Add a launcher script for SDL2 frontend for roswell users

---

modes/lisp-mode/inspector.lisp
src/commands/other.lisp

So, I notice these two things:
- When I was trying to inspect a symbol it was complaining triggering this error:
Seems like the inspector was assuming that it always was a variable, quoting the value solves the issue and it allow it to inspect any symbol.
- When executing commands, the order seem a little odd (for example, trying to call lisp-aproppos, I got longer commands first)
In this case, I just added a sort function so it always trigger the shortest first, I don't know if this was a design decision and I hope that it doesn't introduce too much overhead having to sort all the time. Still, I  think it's a improvement in usability

Add quote in the inspector function and sort in execute command

---

modes/elixir-mode/lsp-config.lisp
modes/lsp-mode/spec.lisp

So... I just realize that the variable only get expanded at compilation time, so when I changed the variable in the config the value doesn't get updated.
The idea is to just change the value in the user configuration with a good old setf command:
```
(defvar *fer/elixir-lsp-path*
'("sh" "path-to"))
(setf (lem-lsp-mode/spec:spec-command
(lem-lsp-mode/spec:get-language-spec 'lem-elixir-mode:elixir-mode))
*fer/elixir-lsp-path*)
```

Remove elixir server-path variable and add a way to change the lsp spec

---

modes/lisp-mode/lisp-mode.lisp

Some improvement. Ideas are from Emacs. ;)

feat(lisp-mode): Add command to eval buffer

---

src/commands/other.lisp

FYI, I made smaller PRs, so it's easier to review. :)

chore: Document functions in other.lisp

---

src/clipboard.lisp

chore: Document clipboard.lisp

---

src/ext/abbrev.lisp

I realize that it checks for repeat keywords in each buffer, but not when they are combined, this solves de issue :+1:

Fix abbrev duplication keywords

---

src/window.lisp

Functions that are left undocumented are functions I'm still trying to understand. But I will add it later after I understand it!

chore: Document some functions in window.lisp

---

src/echo.lisp

This patch also fixed some indentation issues.

chore: Document functions in echo.lisp

---

lem.asd
src/base/buffer.lisp
src/commands/file.lisp

This makes using Lem more efficient :sunglasses: 
The new command should work for all platforms. 
We have a choice of programs to find files: 
- [fd](https://github.com/sharkdp/fd), which is`fdfind` in Debian, excludes .git, node_modules and the like by default
- find
- a lisp way
This is NOT like "find file in project", which could be done later on. This is only "find a file with a choice of all files in subdirectories, starting from this buffer's directory".
I settled on CLOS `eql` specializers to dispatch by the chosen finder program, so the user has built-in configuration options (around methods, etc).
subject to review:
- I introduced my STR library as a dependency. It is lightweight and, albeit not strictly necessary for this PR, I believe it is very handy (and popular!).
- on …

find files recursively

---

modes/vi-mode/core.lisp
modes/vi-mode/ex.lisp
modes/vi-mode/lem-vi-mode.asd
modes/vi-mode/visual.lisp

The plan is to use inheritance to reduce code redundancy and improve the extensibility of vi-states, such as `visual` state. Currently, `visual` state has three sub states (`visual-char`, `visual-line`, `visual-block`), which produce code redundancy with state changes.
TODO: Follow-up with PR to refactor redundancy `visual` state.

[VI-MODE] • Enhance define-vi-state to allow expose more of the defclass CLOS functionality.

---

.gitignore
.gitmodules
patch-build.lisp

So, using quick-patch as a submodule, we can use it to have certain versions of repositories loaded when compiling Lem.
For now it's only used in the patch-build script, and  it can be used the same as the build.lisp:
```
sbcl --load "patch-build.lisp"
```

Add repository patch as a solution for dependency hell

---

modes/vi-mode/visual.lisp

Seems like there is no place in the code where the state is "visual", it's just one of the visual possibilities.
I think this fixes the issue https://github.com/lem-project/lem/issues/720

Fix visual state problem

---

docs/default-keybindings.md
src/commands/edit.lisp

Just added this little command I use all the time in Emacs. The keybindings wasn't in use, so it's fairly inconsequential.
Does the documentation markdown file update the links automatically somehow?

Added C-S-Backspace command that kills the whole line

---

modes/lisp-mode/hyperspec.lisp

If the user right clicks on, say, "save-lisp-and-die", nothing would happen, because this symbol isn't in the index.
Display a message.

hyperspec: message the user if symbol not found

---

lem.asd
src/commands/file.lisp
src/commands/project.lisp
src/commands/window.lisp
src/defcommand.lisp
src/ext/filer.lisp

Similar to find-file-recursively, but finds the project root first.
If no project root was found, use find-file-recursively from the current working directory.
---
It works for me on Linux. I think real tests on other platforms is required, for this reason I marked the PR as draft. Maybe the test suite can help…

new command project-find-file

---

modes/lisp-mode/eval.lisp
modes/lisp-mode/lem-lisp-mode.asd
modes/lisp-mode/lisp-mode.lisp
modes/lisp-mode/swank-protocol.lisp

https://github.com/lem-project/lem/assets/13656378/6a8bf3da-73a0-4db9-b216-d940792b0878
I implemented command to evaluate the expression at the cursor position.
`M-x lisp-eval-at-point (C-x C-e)`: Evaluates the expression in backward of the cursor or the range if a region is selected.
`M-x lisp-eval-interrupt-at-point (C-c i)`: Interrupts the evaluation of the cursor position.
The display after evaluation can be erased on the hook of an operation to edit the range.

Reimplementation of the eval commands in lisp-mode

---

src/commands/project.lisp
src/commands/window.lisp

I propose to add default keybindings.
C-x p f is modeled after Emacs' project.el, but
C-x p d (open directory) and C-x p K (upper case k) differ. There is no confirmation prompt to delete the project buffers, so I put it further away with the uppercase letter.
That being said… maybe it should with a "D", like "Delete", or rename the command to `project-kill-buffers`, like `kill-buffer`?
Emacs' C-x p d is project-find-dir, which we can do in Lem with project-find-file (it includes subdirectories).

project: add keybindings (C-x p f)

---

src/commands/file.lisp
src/commands/project.lisp
src/common/history.lisp

Continuing the projects feature:
- introduces a command to save the current project in the history, on disk
-  => (this could be improved further with automatic project discovery later on)
- then project-switch-project prompts to choose a project, then calls project-find-file.
Keybindings: `C-x p p` is similar to Emacs' project.el, the other two on "s" and "u" are not.
In the future, it could be nice to have a setting to choose if we want automatic collecting of projects in the history, each time we visite a file in a new project (it would be the default), or not, if we prefer to have a small list of saved projects and use the "save" command ourselves (as it is the case now).

projects: save and switch projects

---

src/ext/peek-source.lisp

At first I added "n" and "p", but they interfere with vi-mode.
A global "grep-help" command "clutters" a bit the global list of commands… but being a help, it isn't a bad thing.

grep: add keys and help

---

modes/lisp-mode/repl.lisp

This function complements quickload.
It also covers asdf source-registry, unlike the original.

Add quickload repl-shortcut

---

modes/lisp-mode/lisp-mode.lisp
modes/lisp-mode/message-definitions.lisp
modes/lisp-mode/repl.lisp
modes/lisp-mode/swank-protocol.lisp
src/ext/button.lisp

[Screencast from 2023-06-25 00-31-23.webm](https://github.com/lem-project/lem/assets/13656378/002dd97c-5af5-4951-b3a9-679fa1c376c8)
This feature is an alternative to slime-presentation.
- You can inspect objects printed by micros:micros-print
- You can inspect the evaluation results
- You can also perform actions in the context menu by right-clicking

Associate object with printed in REPL

---

frontends/sdl2/main.lisp

I had a problem with SDL2 frontend not working on some GPUs.
https://github.com/lem-project/lem/issues/754
https://github.com/lem-project/lem/issues/690
https://github.com/lem-project/lem/issues/630
My environment is AMD Radeon and I had the same problem when I installed the driver with amdgpu-install.
After some trial and error, I changed the renderer option from accelerated to software and it works.

SDL2: change renderer option from `accelerated` to `software`

---

modes/lisp-mode/lem-lisp-mode.asd
modes/lisp-mode/trace.lisp

The following two commands have been added.
- `M-x lisp-trace-list (C-c T)`
- `M-x lisp-toggle-trace (C-c C-t)`

Add trace commands to lisp-mode

---

frontends/sdl2/font.lisp
frontends/sdl2/main.lisp

This patch handles the text rendering on high-DPI screen for macOS.
I mark this PR Work-in-Progress, because I haven't fully tested this patch, here is the check list:
For MacOS
For other platforms 
It was broken by itself, this patch didn't make it worse.
#801
It was broken by itself, this patch didn't make it worse.
#802

fix blurry text on Apple retina display

---

src/file.lisp

As the title says, fix spelling in function names.

Correct spelling of associate.

---

frontends/sdl2/font.lisp

Returns a list of filenames as strings containing TTF and OTF fonts installed on the windows system.
(length (lem-sdl2/font:get-font-list (lem-sdl2/platform:get-platform))) => 2132 on my particular machine

Implement get-font-list for windows.

---

modes/lisp-mode/eval.lisp
modes/lisp-mode/lem-lisp-mode.asd
modes/lisp-mode/sldb.lisp

This feature displays evaluation results on the fly.
https://github.com/lem-project/lem/assets/13656378/cdeb8ead-3380-4804-b85b-d487a7e733b1
`(micros:watch form)` you can look the results of form evaluation on the fly.

The powerful print debugger (a.k.a the watcher)

---

lem.asd
modes/lisp-mode/detective.lisp
modes/lisp-mode/lem-lisp-mode.asd
modes/lisp-mode/lisp-mode.lisp
src/base/buffer.lisp
src/base/package.lisp
src/base/point.lisp
src/ext/detective.lisp
src/ext/language-mode.lisp

The idea of this new feature is to have a version of imenu ready to work with regex but also with other external tools (like for example tree-sitter).
One of the interesting challenges of this approach is to parse the buffer efficiently with regex and organize all of them correctly. I'll focus on this the last part given that initially I don't think the overhead is that much.

Add imenu (detective) support for Lem

---

src/frame.lisp

As the title says this should fix the x position of a mouse click when the line numbers overlay is active.

Fixed overlays not being considered when finding the x position in a window

---

src/ext/detective.lisp

@Sasanidas Allow me to chime in :D 
Exporting functions was necessary to discover them while defining keybindings.

detective: export user-facing functions, add docstrings

---

modes/elisp-mode/elisp-mode.lisp
modes/elisp-mode/lem-elisp-mode.asd

Seems like there are a few unwanted dependencies form the jsonrpc/http transport class, and in this case I'm just calling it for a simple information prompt. So for now, it will load only when the user setup the rpc server as mention here https://github.com/lem-project/lem/pull/810#discussion_r1257303942

Remove jsonrcp/http dependency from elisp-mode

---

frontends/sdl2/main.lisp
lem.asd
src/commands/frame.lisp
src/external-packages.lisp
src/interface.lisp
src/internal-packages.lisp

These patches add the ability to get/set the gui window's title along with toggling fullscreen.

Fix some minor SDL2 paper cuts

---

src/base/buffers.lisp
src/base/package.lisp
src/commands/other.lisp

Yesterday I was working on Lem with 30+ buffers open, and when closing the editor, it told me that I had some that were modified but not saved, so I spent a few minutes going around trying to realize which one were the ones that were open.
This patch aims to solved this issue providing information on which buffers are modified but not saved.

Add modified buffers information when exit Lem

---

frontends/sdl2/image-buffer.lisp

\+ and - are much more convenient, and they also work on my keyboard when `C-+` doesn't :D

image viewer: add +, -, 0 keys and help

---

README.md
src/ext/directory-mode.lisp

for the issue seen in https://github.com/lem-project/lem/pull/876
thanks

directory-mode: sort and follow file name (fixes)

---

src/commands/window.lisp
src/internal-packages.lisp
src/window.lisp

I would like to be able to switch to the repl and then use `switch-to-last-focused-window` to return to the buffer I was last editing. Currently the use of `switch-to-last-focused-window` is limited because commands which switch windows are left to set `*last-focused-window*` themselves and most of them don't.
To resolve this I added a line to set `*last-focused-window*` in the `switch-to-window` function.
The next step would be to make all the commands which directly call (setf (current window)) use `switch-to-window` so that `*last-focused-window*` is set and `window-leave-hook` is run.

Set last focused window in switch-to-window.

---

modes/elisp-mode/run-elisp.lisp
modes/elixir-mode/run-elixir.lisp
modes/lisp-mode/inspector.lisp
modes/lisp-mode/lisp-mode.lisp
modes/lisp-mode/repl.lisp
modes/lisp-mode/sldb.lisp
modes/python-mode/run-python.lisp
modes/scheme-mode/repl.lisp
modes/scheme-mode/swank-connection.lisp
modes/shell-mode/shell-mode.lisp
src/ext/directory-mode.lisp
src/ext/listener-mode.lisp
src/mouse.lisp

This replaces all the uses of `(setf (current-window))`to switch windows (except pop-up windows) with `(switch-to-window)`.

Use (switch-to-window) where appropriate.

---

frontends/sdl2/main.lisp

Before this PR Lem SDL2 has various WM_CLASS like `sbcl`, `lem-sdl2`, etc... It caused X11's WM_CLASS is not set explicitly. Because of it we cannot configure some software detect Lem process with WM_CLASS e.g. [xkeysnail](https://github.com/mooz/xkeysnail).
This PR sets WM_CLASS as `Lem SDL2` so now users can be find Lem SDL2 process via windos class name.
I checked WM_CLASS is set after this commit like this:
```
;; clicked lem window after launching `lem-sdl2` or `lem -f sdl2` or something
$ xprop | grep WM_CLASS
WM_CLASS(STRING) = "Lem SDL2", "Lem SDL2"
```

Set WM_CLASS in X11

---

extensions/lisp-mode/apropos-mode.lisp
extensions/lisp-mode/lisp-mode.lisp

Added `M-x lisp-search-symbol (C-c C-d s)`.
Use apropos to search for a symbol and jump to the location of the definition.
Inspired by lsp workspace/symbol.

Add lisp-search-symbol command

---

extensions/lisp-mode/sldb.lisp

Similarly to #896, I want to change the vi-mode state to NORMAL in SLDB mode.
ex. https://github.com/fukamachi/.lem/commit/ba23d4569c8d226d6378fb2ac64a03f7a49e310b

Add lem-lisp-mode:*lisp-sldb-mode-hook*.

---

src/config.lisp

If .lem/config.el is empty it gives the following error:
```
Unhandled SB-KERNEL:INDEX-TOO-LARGE-ERROR in thread #<SB-THREAD:THREAD tid=8219 "SDL2 Main Thread" RUNNING
{10043281F3}>:
The index 0 is too large for a list of length 0.
Backtrace for: #<SB-THREAD:THREAD tid=8219 "SDL2 Main Thread" RUNNING {10043281F3}>
0: (SB-DEBUG::DEBUGGER-DISABLED-HOOK #<SB-KERNEL:INDEX-TOO-LARGE-ERROR expected-type: (INTEGER 0 (0)) datum: 0> #<unused argument> :QUIT T)
1: (SB-DEBUG::RUN-HOOK *INVOKE-DEBUGGER-HOOK* #<SB-KERNEL:INDEX-TOO-LARGE-ERROR expected-type: (INTEGER 0 (0)) datum: 0>)
2: (INVOKE-DEBUGGER #<SB-KERNEL:INDEX-TOO-LARGE-ERROR expected-type: (INTEGER 0 (0)) datum: 0>)
3: (ERROR SB-KERNEL:INDEX-TOO-LARGE-ERROR :DATUM 0 :SEQUENCE NIL :EXPECTED-TYPE (INTEGER 0 (0)))
4: …
```

lem-core:config-plist errors out when ~/.lem/config.lisp is empty

---

src/config.lisp

Sorry, I made a mistake in the altered config function. 
I should not have included the if statement otherwise config returns nil, not even the default value. Instead we just needed to add (car plist) otherwise everything else stays the way you wrote it.
My previous commit leaves all the settings unset.

Attempt #2: config-plist errors out when ~/.lem/config.lisp is empty

---

src/lem.lisp

This is what it looks like
```
$ lem --help
Usage: lem [ OPTION-OR-FILENAME ] ...
Options:
-q, --no-init-file      do not load ~/.lem/init.lisp
--slime PORT            start slime on PORT
--eval EXPR             evaluate lisp expression EXPR
--debug                 enable debugger
--log-filename FILENAME file name of the log file
--kill                  immediately exit
-v, --version           print the version number and exit
-h, --help              display this help and exit
```

added help to cli

---

extensions/vi-mode/binds.lisp
extensions/vi-mode/commands.lisp

`;` is a key command for finding a char in the same line (`f`, `F`, `t`, `T`) by the last searched query.

Add ';' for vi-mode to find a char in the same line repeatedly.

---

extensions/lisp-mode/repl.lisp
src/base/line.lisp
src/ext/listener-mode.lisp

lem is including color information in the attribute property of the buffer, when syntax highlighting is enabled, this value is overwritten, so when a listener sets an attribute to a prompt, it is erased.
In this PR, sticky-attribute is newly added separately from attribute.
The listener now sets this to the prompt.

Enable syntax highlighting in the listener as well

---

extensions/vi-mode/core.lisp
frontends/ncurses/ncurses.lisp
src/interface.lisp
src/internal-packages.lisp

**This also affects other than vi-mode.**. 
Please review changes if this doesn't break other Lem's features or frontends.
Adds `lem-if:update-cursor-shape` to change the cursor's shape, like a box, a vertical bar, or an underline.  
It works only on ncurses frontend for now.
In vi-mode, the cursor will be changed to 'vertial bar' on INSERT mode.

Add lem-if:update-cursor-shape to change the cursor's shape for lem-ncurses

---

extensions/vi-mode/core.lisp
extensions/vi-mode/ex-command.lisp
extensions/vi-mode/ex.lisp
extensions/vi-mode/lem-vi-mode.asd
extensions/vi-mode/options.lisp
extensions/vi-mode/vi-mode.lisp

It is to make Lem's vi-mode closer to Vim's behavior. If you prefer the previous behavior, there's 2 options to achieve:
Set `autochdir` to `t` in your `init.lisp`:
```common-lisp
(setf (lem-vi-mode:autochdir) t)
```
To change the option temporarily, just execute `:set autochdir` (and `:set noautochdir` to turn off).
Use `:cd` command to change the directory manually:
```vim
" Move to "extensions/vi-mode"
:cd extensions/vi-mode
" `%:h` expands to the directory of the current buffer's file
:cd %:h
" `-` means the previous directory
:cd -
```
* Add Vim's options feature
* Currently only `autochdir` is implemented
* Works when running `:e` (`find-file`) or switching the buffer/window
* **[Incompatible changes]** Change the base directory to find with `:e` to the **current directory**
* You …

Introduce Vim's options feature, and add `:set` & `:cd`

---

extensions/vi-mode/binds.lisp
extensions/vi-mode/commands.lisp

It's a pair of `;`, but repeat the last search in the opposite direction.

Add ',' to search in the line repeatedly but backward

---

extensions/vi-mode/README.md
extensions/vi-mode/options.lisp
extensions/vi-mode/vi-mode.lisp

Also, stop defining functions for each option, because `number` conflicts with the common-lisp package. (ref #908)

Add "number" option to show line numbers in vi-mode.

---

extensions/lisp-mode/detective.lisp
extensions/lisp-mode/lisp-mode.lisp
extensions/lisp-mode/misc-commands.lisp
src/ext/detective.lisp

- Add the detective ability to get misc references (only tests for now)
- Add a few convenience options to detective, so it's more flexible
- Add two commands to run tests:  `lisp-test-run-buffer` and `lisp-test-run-current`

Add test detection with detective and some handy lisp commands to run the test on the REPL

---

extensions/lisp-mode/eval.lisp
extensions/lisp-mode/internal-package.lisp
extensions/lisp-mode/lisp-mode.lisp

close https://github.com/lem-project/lem/issues/959
Merge `C-c C-r` with `C-x C-e`
C-x C-e during region selection => Equivalent to C-c C-r
C-c C-r => to unbinding, change to the command to run the test in the future.

C-x C-e to eval that range during region selection

---

src/config.lisp

Use XDG_CONFIG_HOME to find the lem configuration directory.

---

extensions/vi-mode/commands.lisp
extensions/vi-mode/commands/utils.lisp

* Fix `d%` to work regardless of whether the direction is forward or backward
* Fix `df<char>` and `dt<char>` not to delete if the search failed
* Support visual block mode to make `d` & `y` work with a rectangle region
ref #952

Fix new bugs of vi-mode introduced by #952

---

extensions/vi-mode/ex-command.lisp
extensions/vi-mode/lem-vi-mode.asd
extensions/vi-mode/options.lisp

Add "iskeyword" of vi-mode option, which is used to specify a character set to be treated as a `word` by vi-mode.
* Type: a list of strings
* Default: `@,48-57,_,192-255`
* Alias: `isk`
It can be set in ex mode, like `:set iskeyword=@,_`. Be sure it must be a comma-separated string in ex mode.
In this PR, several set operations like `+=`, `-=`, `^=` are also added, which can be used like `:set iskeyword+=@-@` to add a new value.
To set in `init.lisp`, a function `vi-option-value` is available:
```common-lisp
(import 'lem-vi-mode:vi-option-value)
(setf (vi-option-value "iskeyword") '("@" "_"))
```

Add "iskeyword" option

---

extensions/vi-mode/core.lisp
extensions/vi-mode/visual.lisp

I don't know if this is the appropriate way (and works in other environments) to set it up in Lem.

NeoVim-like status indicator for vi-mode

---

lem.asd

Fix the indentation for one of the dependencies in the `lem.asd` file.

Consistent indentation in `lem.asd`.

---

extensions/vi-mode/lem-vi-mode.asd
extensions/vi-mode/tests/utils.lisp
extensions/vi-mode/tests/visual.lisp
extensions/vi-mode/visual.lisp

The vi-mode has several visual modes, `visual-char`, `visual-line` and `visual-block`. When one of those modes is enabled while the other one is one, the starting point should be taken over.

Switch between visual modes without resetting the starting point

---

src/config.lisp
src/site-init.lisp

Currently this drops lem-site-init.asd into ~/.lem which causes lem-home to always use ~/.lem instead of XDG_CONFIG_HOME + lem
small whitespace fix in config.lisp #434

site-init: use lem-home instead of user's home directory

---

src/ext/loading-spinner.lisp
src/overlay.lisp

Fix for https://github.com/lem-project/lem/issues/987
- nil is passed to `update-line-spinner`
- The `temporary` slot of `overlay-line-endings` is unbound, causing an error in initialize-instance

Fix error in start-loading-spinner

---

src/command.lisp
src/input.lisp
src/internal-packages.lisp
src/interp.lisp
src/lem.lisp

This PR adds the following symbols:
* `lem:this-command-keys`: A function to get a key sequence that invokes the current command.
* `lem:universal-argument-of-this-command`: A function to get the universal argument of the current command.
These are equivalent to Emacs's `this-command-keys` and `current-prefix-arg`.
ref https://www.gnu.org/software/emacs/manual/html_node/elisp/Command-Loop-Info.html#index-this_002dcommand_002dkeys
Originally, I was making these changes to implement vi-mode's `.`, an operator to repeat the last operation, however, I split them as an individual PR to hear other's thoughts.

Add `lem:this-command-keys` and `lem:universal-argument-of-this-command`

---

src/ext/isearch.lisp

This reverts commit 006111d5db33b930bfe069f1b101bec6d5e86f68.
ref https://github.com/lem-project/lem/pull/996#discussion_r1304551049

Revert "Fix not to move the cursor by *isearch-search-function*."

---

extensions/vi-mode/binds.lisp
extensions/vi-mode/commands.lisp
extensions/vi-mode/commands/utils.lisp
extensions/vi-mode/core.lisp
extensions/vi-mode/ex-command.lisp
extensions/vi-mode/ex.lisp
extensions/vi-mode/lem-vi-mode.asd
extensions/vi-mode/modeline.lisp
extensions/vi-mode/options.lisp
extensions/vi-mode/states.lisp
extensions/vi-mode/tests/utils.lisp
extensions/vi-mode/utils.lisp
extensions/vi-mode/vi-mode.lisp
extensions/vi-mode/visual.lisp

Move some code in `lem-vi-mode/core` into `states`, `modeline`, and `utils`.

Reorganize packages of vi-mode

---

src/internal-packages.lisp
src/keymap.lisp

Add a new variable `*emulation-mode-keymaps-functions*` to set keymaps that precede other major/minor modes. This is equivalent to Emacs's `emulation-mode-map-alists` for emulation mode.
ref. [Controlling Active Maps | Emacs manual](https://www.gnu.org/software/emacs/manual/html_node/elisp/Controlling-Active-Maps.html#index-emulation_002dmode_002dmap_002dalists)
For the time being, `vi-mode` is in mind. It requires switching multiple keymaps by its "state" and has to _merge_ with others to work better in other modes.
Talking about preceding lisp-mode's keybinds, and problems with directory-mode at #992 .

Add a feature to set high priority keymaps for emulation modes

---

src/keymap.lisp

After the merge of #1004, the completion-mode can't use `C-n` and `C-p` to choose an item.
This is because #1004 adds minor-mode keymaps to the top of the keymaps list to make them a high priority. I didn't think this caused any problems, but it invoked the undef-hook of the completion keymap by accident.
The key command will go through the list of keymaps like this: `next-line` -> `completion-next-line` -> `completion-self-insert` (by undef-hook).
Reported by @Sasanidas.

Fix unintended undef-hook invocation due to more than twice key lookup

---

extensions/paredit-mode/lem-paredit-mode.asd
extensions/paredit-mode/paredit-mode.lisp

Since it doesn't depend on vi-mode anymore.

Delete a dependency of lem-paredit-mode

---

extensions/vi-mode/commands.lisp
extensions/vi-mode/commands/utils.lisp
extensions/vi-mode/lem-vi-mode.asd
extensions/vi-mode/tests/text-objects.lisp
extensions/vi-mode/tests/visual.lisp
extensions/vi-mode/text-objects.lisp

In some cases, `a"` doesn't work expectedly. ref #1014

Fix vi-mode text objects

---

extensions/vi-mode/tests/visual.lisp
extensions/vi-mode/visual.lisp

Fix the vi-mode's visual block region when the cursor moves to right-top or left-bottom.

Fix vi-mode's visual rectangle region 

---

extensions/vi-mode/binds.lisp
extensions/vi-mode/commands.lisp
extensions/vi-mode/states.lisp

Add replace-state to vi-mode that is on when `r` is pressed. It allows quitting the replace-state by `Esc` or `C-g`.
As Vim's replace state provides other special commands like `C-e` and `C-y`, this flexibility would be required for the future extension.

Add replace-state to vi-mode

---

extensions/vi-mode/options.lisp
extensions/vi-mode/vi-mode.lisp

Allow to set the minimal number of lines to keep above or below the cursor.
Ex mode: `:set scrolloff=10`
Init file: `(setf (option-value "scrolloff") 10)`

Add `scrolloff` option to vi-mode

---

extensions/vi-mode/core.lisp
extensions/vi-mode/ex.lisp
extensions/vi-mode/modeline.lisp

Currently, it shows "COMMAND" for all windows while in Ex mode, but it's lame.

Show vi modeline status only for the "main" window in Ex mode.

---

extensions/vi-mode/ex-command.lisp
extensions/vi-mode/ex-parser.lisp

The `c` flag is for asking for each substitution, which uses `M-x query-replace`.
The answer options of `query-replace` are not the same as Vim and lack some, but it's still fairly useful.
It'd be better to have `q` option to quit the rest of the substitution for further improvements.

Add `c` flag to `:s`.

---

extensions/vi-mode/commands.lisp

Fix an unintended column movement regarding `vi-line`, which is commonly used in vi commands. It uses `next-logical-line`; however, it keeps the column position unintentionally.
For example, `^$j` goes to the beginning of the line.

Fix an unintended column movement regarding `vi-line`

---

src/commands/project.lisp

Hi there
The `prompt-for-project` method returns `(show-message "No projects." :timeout 5)` if there aren't any `candidates`. 
I think the `show-message` function doesn't return nil and and that's why `project-switch` method fails.
This is the error message:
```
The value
#<LEM/POPUP-WINDOW::POPUP-WINDOW {1004B65343}>
is not of type
(OR STRING PATHNAME SYNONYM-STREAM FILE-STREAM NULL)
when binding :DEFAULTS
Backtrace for: #<SB-THREAD:THREAD "editor" RUNNING {100401DA73}>
0: (MAKE-PATHNAME :HOST NIL :DEVICE NIL :DIRECTORY NIL :NAME NIL :TYPE NIL :VERSION NIL :DEFAULTS #<LEM/POPUP-WINDOW::POPUP-WINDOW {1004B65343}> :CASE :LOCAL)
1: (UIOP/FILESYSTEM:CALL-WITH-CURRENT-DIRECTORY #<LEM/POPUP-WINDOW::POPUP-WINDOW {1004B65343}> #<FUNCTION (LAMBDA NIL :IN LEM-CORE/COMMANDS/PROJECT::PROJECT-SWITCH) …
```

Fix project-switch issue when It doesn't exists projects

---

extensions/vi-mode/commands.lisp
extensions/vi-mode/ex.lisp
extensions/vi-mode/lem-vi-mode.asd
extensions/vi-mode/registers.lisp
extensions/vi-mode/tests/registers.lisp
extensions/vi-mode/visual.lisp
src/ext/isearch.lisp

This doesn't affect the existing features, but it's required for adding Vim's keyboard macro.
Added a new hook `*isearch-finish-hooks*` to Lem's isearch, which is invoked when `isearch-finish` is called.

Implement Vim's register for vi-mode

---

extensions/vi-mode/utils.lisp

1. `:e .<Return>`
1. `:e %:h<Tab>`

Fix an error when expanding the filename modifier (like %:h) on the directory buffer

---

extensions/vi-mode/commands.lisp
extensions/vi-mode/tests/operator.lisp

Fix a bug that `cc` and `S` don't keep a single empty line after deletion. Introduced by a recent change of #1055 .

Fix linewise vi-change to keep an empty line

---

frontends/sdl2/keyboard.lisp

On SDL2 / Linux, when the meta key is assigned separately from the alt key, the meta key is not recognized as meta but super.
Currently, it is hard-coded which modifier key is actually assigned to which modifier.
This PR introduces a dynamic variable `*modifier-code-table*` that allows modifier keys to be set.
By default, the behavior is the same as before.
The following can be written in the configuration file.
```lisp
#+lem-sdl2
(setf lem-sdl2/keyboard::*modifier-code-table*
`((:shift ,sdl2-ffi:+kmod-lshift+ ,sdl2-ffi:+kmod-rshift+)
(:ctrl ,sdl2-ffi:+kmod-lctrl+ ,sdl2-ffi:+kmod-rctrl+)
(:meta ,sdl2-ffi:+kmod-lgui+ ,sdl2-ffi:+kmod-rgui+)
(:super ,sdl2-ffi:+kmod-lalt+ ,sdl2-ffi:+kmod-ralt+)))
```

lem-sdl2: Make configurable modifier keycode by dynamic variable

---

src/commands/window.lisp

Addresses the issue: #827
Toggles line wrap in buffer only, unsure if should be global or not

Add command to toggle line wrap in the buffer

---

src/ext/directory-mode.lisp

I think this address https://github.com/lem-project/lem/issues/1072 , the rm command was deleting the symlink directory content which is not the desire behaviour and can cause serious problems (specially when rm doesn't ask any question).

Add safeguard for deleting symlinks

---

extensions/vi-mode/binds.lisp
extensions/vi-mode/commands.lisp
extensions/vi-mode/lem-vi-mode.asd
extensions/vi-mode/registers.lisp
extensions/vi-mode/tests/kbdmacro.lisp
extensions/vi-mode/vi-mode.lisp

- `q{a-zA-Z0-9"}` to record a new macro
- `q` to finish recording
- `@{a-zA-Z0-9"}` to execute a macro
- `Q` to execute the last recorded macro

Add keyboard macro to vi-mode

---

src/ext/universal-argument.lisp

The universal argument isn't reset when some error occurs in the command called in `universal-argument-default`.
This happens quite often with vi-mode for errors like `end-of-buffer`. For example, `10000j` ends with an `end-of-error`, and can see the remaining universal argument with `1j`.

Ensure to reset the universal arguments even when error occurs

---

extensions/vi-mode/core.lisp
extensions/vi-mode/leader.lisp
extensions/vi-mode/lem-vi-mode.asd
extensions/vi-mode/states.lisp
extensions/vi-mode/vi-mode.lisp
src/internal-packages.lisp
src/key.lisp
src/keymap.lisp

Vim provides a special key `<Leader>`, which is configurable by each user.
For example, an extension provides a command mapped to `<Leader> x`, then it's invoked by `\` + `x` since `Backslash` (`\`) is the default map of `<Leader>`. If the user set `g:mapleader` to `Space`, it can be invoked by `Space x`.
```common-lisp
(define-command say-hello () () (message "Hello!"))
(define-key lem-vi-mode:*normal-keymap* "Leader x" 'say-hello)
(setf (variable-value 'lem-vi-mode:leader-key) "Space")
```
* Add `define-named-key` to define a custom named key
* Rewrite `keymap-find-keybind` as a generic function, and export it

Add `<Leader>` key to vi-mode.

---

extensions/vi-mode/commands.lisp

It didn't indent when the next line is empty.

Fix `o` to indent properly.

---

extensions/vi-mode/commands.lisp

Fix the linewise region of `=` and `J` not to include the next line.

---

extensions/vi-mode/commands.lisp
extensions/vi-mode/commands/utils.lisp
extensions/vi-mode/ex-command.lisp
extensions/vi-mode/jump-motions.lisp
extensions/vi-mode/jumplist.lisp
extensions/vi-mode/lem-vi-mode.asd
extensions/vi-mode/tests/jumplist.lisp
extensions/vi-mode/tests/utils.lisp

* Make jumplist window-local
* Keep only 100 points in a single jumplist
* Remove points on the same line when pushing a new point in a jumplist history
* Remove newer history when pushing a new point after going back the history
* Don't save on the same line motion
* Don't save on operator execution (like `dG`, `d%`)
* Save the current point on `:e` and `:b`
* Copy a current jumplist when splitting the current window

Revise vi-mode's jumplist

---

extensions/vi-mode/commands.lisp

Lem's keyboard macro stops when an error occurs (such as command-not-found) while recording.
https://github.com/lem-project/lem/blob/68823d61b7783ebb01a21a20b24c1691911d862f/src/interp.lisp#L87
Ignoring it should be fine for vi-mode, but for now, fix it to work even in the case.

Fix vi-mode's keyboard macro in case that the recording is accidentally stopped

---

extensions/lisp-mode/detective.lisp
src/ext/detective.lisp

fixed https://github.com/lem-project/lem/issues/982

Fix parsing for `(def |foo bar|`

---

extensions/swift-mode/lem-swift-mode.asd
extensions/swift-mode/lsp-config.lisp
extensions/swift-mode/swift-mode.lisp
extensions/swift-mode/swift.json
lem.asd

Created an extension for syntax highlighting and LSP support (on macOS so far) for Swift.
Adding Linux support is pretty simple, but I have to set up a Linux machine for testing.
A quick note, it seems that the LSP fights over the message box, which is a bit confusing for using autocomplete. Any suggestions here?

Swift Language support

---

src/lem.lisp

This allows to load Lem extensions in .lem/init.lisp even when Lem source isn't in an ASDF load path (such as `~/common-lisp`).

Reuse the main thread's ASDF source registry in the editor thread.

---

src/ext/thingatp.lisp
tests/thingatp.lisp

I was wrong, this is a different way of interacting with link, only taking into account the point context (way more simpler than links).
So the actual implementation doesn't work and break the functionality of it. 
With this PR we can restore it back keep both functionality (as original intended)

Restore back original thing-at-point functionality

---

lem.asd
src/commands/window.lisp
src/ext/legit/legit-commit.lisp
src/ext/legit/legit.lisp

Currently, we can only write one-line commit messages in Lem/legit :S This improves the situation, we create a special buffer to write commit messages.
I only tested this evening while working on it.

legit: write commit message in a buffer

---

extensions/lisp-mode/lisp-mode.lisp

Fix for https://github.com/lem-project/lem/issues/1122
There are cases where micros cannot be seen from outside sbcl when using qlot, so the micros.asd is explicitly loaded at startup.

Add micros path to child process started by slime command

---

lem.asd
roswell/lem-language-server.ros
roswell/lem-ncurses-ccl.ros
roswell/lem-ncurses.ros
roswell/lem-rpc.ros
roswell/lem-sdl2.ros
roswell/lem.ros

Lem cannot be installed via Roswell since it adopts Qlot to manage dependencies.
This PR allows Lem to be installed via Roswell again. It needs to run `qlot install` while running `ros install lem-project/lem`. This feature actually doesn't work in the current Roswell, so users must update it first.
* Roswell [v23.10.14.114](https://github.com/roswell/roswell/commit/0e7a2f1b6d9153f33edf1cc7b780825913a93618) or above.
* [Qlot](https://github.com/fukamachi/qlot)
```
$ ros install lem-project/lem
```
No need to specify `follow-dependency=t` anymore.
```
$ git clone https://github.com/lem-project/lem
$ cd lem
$ qlot install
$ qlot exec ros -S . install lem
```

Allow to install Lem via Roswell.

---

src/ext/directory-mode.lisp

and put the cursor on the file name.
previous discussion: https://github.com/lem-project/lem/pull/868
I still find this feature useful, last time in July you seemed to find it useful too.
---
It doesn't work with an image buffer:
- buffer-filename is not set
- but if I set it (image-buffer.lisp, open-image-buffer), I have an encoding error coming from find-file-buffer.

directory-mode: add C-x C-j to open this file's directory

---

scripts/build-ncurses.lisp
scripts/build-sdl2.lisp
src/internal-packages.lisp
src/lem.lisp

Load $HOME/.lem/build-init.lisp when creating executables with make.
asdf:initialize-source-registry is slow when starting lem (also load-site-init is slow)
Commenting out these two will reduce startup time from 1 second to less than 0.1 second
The reason we are using asdf:initialize-source-registry is that when we are managing lem using qlot, there are cases where the lem is not in the asdf load path.
In this case, the system in lem/contrib is not found when you try to quickload it.
https://github.com/lem-project/lem/pull/1123
As a solution, I prepared an initialization file to be loaded at build time.

load initialization build-init.lisp when creating executable

---

extensions/paredit-mode/lem-paredit-mode.asd
extensions/paredit-mode/paredit-mode.lisp
extensions/paredit-mode/tests/main.lisp

To work more conveniently with `||` embraced symbols (e.g. `|aSdF|`) implemented pair insertion, deletion and wrapping similar to `()` and `""`.
With corresponding tests.

Paredit insert vertical line

---

src/base/package.lisp

Fix typo with-current-buffers in lem-base export

---

src/base/buffer.lisp
src/base/package.lisp

It seems that `with-buffer-point` is also user facing (not used in lem-base itself) so I'm also exporting it.

Export with-current-buffer and with-buffer-point, close #1152

---

extensions/lisp-mode/apropos-mode.lisp
extensions/lisp-mode/lisp-mode.lisp

This commands gives autocompletion to all the asd systems on the image and then go to the .asd file that define that system.

Add lisp-search-asdf-definition command

---

src/commands/file.lisp

Seems like when the file is on the ARG, not always is a PATHNAME, sometimes is a string that can be a valid absolute pathname.
Checking the absolute path seems to solve the issue.

Fix the pathname detection

---

extensions/lisp-mode/highlight.lisp
extensions/lisp-mode/lem-lisp-mode.asd
qlfile.lock

This is a PR that adds variable highlighting to lisp mode.
This feature is experimental and can only be used in a few cases.

Lisp highlight

---

src/internal-packages.lisp
src/keymap.lisp

A simple macro for defining multiple keys.
Example usage:
```lisp
(define-keys *global-keymap*
("C-a b" 'describe-bindings)
("C-a k" 'describe-key)
("C-a a" 'lem-lisp-mode:lisp-apropos)
("C-a c" 'apropos-command)
("C-a p" 'lem-lisp-mode:lisp-apropos-package)
("C-a f" 'lem-lisp-mode:lisp-describe-symbol))
```
It is a macro only because I prefer the &body indentation for this.  If you think a function is better, that is okay too.
Thank you.

define-keys

---

src/base/icon.lisp
src/ext/filer.lisp
src/modeline.lisp

This fixes https://github.com/lem-project/lem/issues/1178
The issue exists on Arch and OpenBSD as far as I am currently aware, the freetype2 package that sdl2_ttf depends on is built without certain options on these systems that break icons in lem.
Using the icon registry, we go from having a pointer error, to just displaying an empty box icon, which is much preferred.
There are probably other icons elsewhere in the source that I haven't run into yet, but the solution is just to add them to src/base/icons.lisp
Before:
After:

sdl2 icons workaround

---

src/base/package.lisp

Small change which exports the two accessors `point-line` and `point-linum`.
There might be more functions which should be exported but I didn't go through the whole file.

Export point accessors point-line and point-linum.

---

src/base/icon.lisp

My bad, I had put in the wrong hexcode for lock emoji, this fixes it.

proper code for lock

---

src/window/virtual-line.lisp

Adds two new keyword arguments to `window-recenter` to make it possible to scroll the window to an arbitrary line.
Emacs uses a single argument, interpreting negative numbers as `from-bottom`, but as this is not a command, I think the additional keyword argument might be better.
I did implement it in `window-recenter`. I could also introduce a new function for arbitrary scrolling, and re-implement `window-recenter` using this new function, if you think the function name is not appropriate for this feature.

Make it possible to recenter the window to an arbitrary line.

---

src/keymap.lisp

This allows binding a key to a keymap instead of a command.
```
(define-key *global-keymap* "C-x w" lem-some-package:*some-package-keymap*)
```
This way, a package which provides multiple commands, but not a mode with which these commands are associated, the person implementing the package can provide a keymap, with all the commands bound to an appropriate key.
Users can then simply bind the keymap to a key-combination of their choice and can start using the package right away, without the need to bind many keys to a common prefix.

Allow binding a key to a keymap.

---

src/base/package.lisp

Reverts lem-project/lem#1204
reason
- line structure is an internal structure and should not be exported
- The same is true for point-linum; line-number-at-point exists instead.

Revert "Export point accessors point-line and point-linum."

---

src/ext/prompt-window.lisp

In find-file prompt, it is helpful to truncate the path before ~/ or // on Unix-style systems, otherwise paths can get really long.  This change modifies `lem/prompt-window::prompt-file-completion` to do this.  I do not use windows so this is behind a read-time feature condition and should only affect Linux/Mac
Thank you.

find-file unix path normalization

---

extensions/legit/legit.lisp
extensions/legit/porcelain.lisp

This has been laying on a branch for some weeks, I think it's better put in use.
Support is simple, and it will be hard to have great support for different VCSs, but starting support for 3 of them helped me modularize my code and spot some missing cases in Git. So it's beneficial to have it IMO.

legit: add simple Mercurial support

---

extensions/vi-mode/binds.lisp

Vim shift + arrow keys in insert mode:
https://vimdoc.sourceforge.net/htmldoc/insert.html#ins-special-special

Adds vi-mode binding for Shift arrow keys in insert mode.

---

contrib/tetris/tetris.lisp
src/common/timer.lisp

In Tetris, when multiple rows need to be removed at once, calling the timer-ms accessor does not work since the function is neither exported in timer package, nor used in the Tetris source.
This fixes the game.

Tetris fix

---

extensions/vi-mode/ex-command.lisp
src/commands/file.lisp

Adds the command `current-directory` to display the directory of the buffer as a message, or insert it into the current buffer.
Adds the vi-mode ex command `:pwd`.

Adds the commend current-directory and the ex command pwd.

---

extensions/vi-mode/ex-command.lisp

Old behaviour if a filename is given stays the same. Without a filename, revert the buffer. Dependent an `!` user will be asked.
https://vimdoc.sourceforge.net/htmldoc/editing.html#:edit

Enhances vi-mode ex :edit command to be able to revert the buffer.

---

src/display/physical-line.lisp

This patch fixes rendering of long lines when **line-wrapping** and **line-numbers** are enabled.
Previously, the separation of objects was done on the whole width of the window, which includes the `left-side-width`. This makes rendering of the first line correct, but following lines of the same logical line are wrong.
Now, the separation of objects is done without the `left-side-objects` on the reduced width. The left side is rendered separately.
The `empty-left-side-objects` are needed, otherwise there might be artefacts of the message buffer on the left side, because the empty space is never rendered.
I don't think is a nice solution, but I am not so familiar with the rendering code. Feel free to suggest any changes, or drop this PR if you have a better idea. It works for me right now …

Fixes rendering of long lines when line wrapping is on.

---

extensions/vi-mode/ex-command.lisp

Only a partial implementation.
Executing a command and inserting its output is not yet supported.
The range currently does not distinguish between `:0` and `:1` so it is not possible to insert at the beginning of the file.
https://vimdoc.sourceforge.net/htmldoc/insert.html#:r

Adds vi-mode ex command :read.

---

src/completion.lisp

Allow to specify the key for the candidates of completion-strings. Useful if the candidates are a list of completion-items.

Allow the keyword argument :key for completion-strings.

---

extensions/vi-mode/ex-command.lisp

wqa should write all buffers, not just the one visiting.
https://vimdoc.sourceforge.net/htmldoc/editing.html#:xall

Fixes vi-mode ex command :wqall should write all buffers.

---

extensions/lisp-mode/repl.lisp

I have some glitches with `backward-prompt` and `forward-prompt`. If the evaluation does not produce any output, like
```
CL-USER> (error "foo")
CL-USER> (error "foo")
```
The next prompt is right on the next line. Since `move-to-previous-virtual-line` moves the cursor to the start of the line, one prompt is skipped. The same happens for `forward-prompt` if there are multiple prompts which didn't produce any output.
This fix resolves the issues for me, could someone have a look if it makes sense?

Fix backward-prompt glitches where a prompt is skipped.

---

extensions/vi-mode/binds.lisp
extensions/vi-mode/commands.lisp
extensions/vi-mode/tests/commands.lisp

Adds the vi command `vi-search-backward-symbol-at-point` `#`
https://vimdoc.sourceforge.net/htmldoc/pattern.html##
Enhances `vi-search-forward-symbol-at-point` `*` to wrap around and to accept a prefix-argument.

Adds vi-mode command # and fixes * to wrap around.

---

src/ext/frame-multiplexer.lisp

Some enhancements for the frame-multiplexer.
- Adds a recent list, so one can jump between recently visited frames. Mostly used to the jump to the most recent.
- Adds names to the frames. If no name is given, the behaviour is unchanged. Names can be removed by giving a frame an empty name
New commands:
- `frame-multiplexer-switch`  jump to a frame with the given ID (prefix argument)
- `frame-multiplexer-recent` go to a frame in the recent list
- `frame-multiplexer-rename` give a name to a frame
- `frame-multiplexer-nomalize-ids` re-assign IDs in case many frames have been deleted and created, so it is easier to jump with `frame-multiplexer-switch`
Changed commands:
- `frame-multiplexer-next` Accepts a prefix argument with which the jump can get bigger
- `frame-multiplexer-prev` Same as …

Adds a recent list to the frame multiplexer + small enhancements.

---

src/ext/isearch.lisp

Many public isearch commands signal conditions if they are executed right after startup, before isearch has been initialized by `isearch-forward` or one of the related functions:
`isearch-add-cursor-to-next-match`
The variable LEM/ISEARCH::*ISEARCH-STRING* is unbound.
`isearch-next`
The variable LEM/ISEARCH::*ISEARCH-SEARCH-FORWARD-FUNCTION* is unbound.
`isearch-prev`
The variable LEM/ISEARCH::*ISEARCH-SEARCH-BACKWARD-FUNCTION* is unbound.
`isearch-next-highlight`
The variable LEM/ISEARCH::*ISEARCH-STRING* is unbound.
`isearch-prev-highlight`
The variable LEM/ISEARCH::*ISEARCH-STRING* is unbound.

Fixes *isearch-string* unbound after startup.

---

frontends/sdl2/drawing.lisp
src/display/physical-line.lisp

I am not sure if this is a complete fix for the rendering in the sdl2 frontend, but it fixes #1240
Maybe `render-line` should not fill to the end of the line but only to the width of the objects?
Or is it required that the objects given to `render-line-with-caching` always fill the whole line? If so, then `redraw-logical-line-when-line-wrapping` needs to be adapted to only call `render-line-with-caching` once per line.

Fixes line rendering for wrapped lines in sdl2 frontend.

---

src/ext/frame-multiplexer.lisp

Sorry, introduced a small bug to the frame multiplexer, which issues an error if the next/prev command is called and only one frame is present.
This adds proper `nil` checks for this case.

Fixes the frame-multiplexer prev/next commands if only one frame present.

---

src/ext/frame-multiplexer.lisp

I am not sure about the name of the `*keymap*` variable.
Currently, there is a lot of repetition in `init.el`. If the variable is named `*keymap*`, the user writes this into it's init.el to remap it:
```
(define-key *global-keymap* "C-v" lem/frame-multiplexer:*keymap*)
```
But now, the name of the keymap does not match the of the variable. But naming the variable `*frame-multiplexer-keymap*` introduces a lot of repetition in `init.el`
```
(define-key *global-keymap* "C-v" lem/frame-multiplexer:*frame-multiplexer-keymap*)
```
What do you think? What is the name of the keymap used for, is it just for user information?

Adds a keymap for the frame-multiplexer.

---

src/display/physical-line.lisp
src/window/virtual-line.lisp
src/window/window.lisp

The next attempt to fix line rendering for #1243 
The sdl2 front-end requires the whole line to be rendered. Otherwise, the caching of lines won't work. It also doesn't like empty strings.
The `left-side-width` depends on the front-end. For ncurses, it is the number of characters, for sdl2 the number of pixels.
I also tried to fix the scrolling version with line-numbers. Because the line-numbers are appended before the calculations are done, those will be scrolled out as well.
Hopefully this works now.

Fixes line-rendering for wrapping and scrolling.

---

src/ext/link.lisp

Link mode doesn't have a name, so in `describe-mode`, the minor mode list contains `nil`.
Maybe this was done so the mode doesn't show up in the modeline?
If so, I think lem should have a mechanism to hide modes from the modeline, but a mode should always have a name, so describe mode shows something reasonable.

Give link-mode a name, so it shows up in DESCRIBE-MODE.

---

src/ext/auto-save.lisp

The auto-save-mode was never actually enabled/disabled. Since `toggle-auto-save` does not call the mode, the user never sees the mode in the modeline.
Also: adding and removing the hook should be independent from wether the timer is set or not. Otherwise, disabling the mode will not remove the hook if the timer is not set, because the set `auto-save-checkpoint-frequency` to `nil`.

Actually enable/disable the auto-save mode.

---

frontends/sdl2/view.lisp
src/ext/popup-window.lisp

This fixes a crash in SDL2 when a texture is empty:
```
debugger invoked on a SDL2::SDL-ERROR in thread
#<THREAD tid=37708 "main thread" RUNNING {1007760253}>:
SDL Error: Texture dimensions can't be 0
Type HELP for debugger help, or (SB-EXT:EXIT) to exit from SBCL.
restarts (invokable by number or by possibly-abbreviated name):
0: [CONTINUE] Return to the SDL2 main loop.
1: [ABORT   ] Abort, quitting SDL2 entirely.
(SDL2:CREATE-TEXTURE #<SDL2-FFI:SDL-RENDERER {#X5638722A74A0}> 373694468 2 288 0)
source: (CHECK-NULLPTR
(SDL-CREATE-TEXTURE RENDERER
(ENUM-VALUE 'SDL-PIXEL-FORMAT PIXEL-FORMAT)
(ENUM-VALUE 'SDL2-FFI:SDL-TEXTURE-ACCESS ACCESS) WIDTH HEIGHT))
```
The change in `popup-window` is needed for an assertion in `window`:
```
debugger invoked on a SIMPLE-ERROR in thread
#<THREAD …
```

Fixes an SDL2 crash which happens when texture have no size.

---

extensions/lisp-mode/misc-commands.lisp

A simple command to navigate to https://quickdocs.org from lisp mode.

Add command to go to quickdocs using the reference at point

---

extensions/python-mode/python-mode.lisp

Associate python shebang with python mode.
Would maybe be good if it would be possible to define a regex for that?

Associated python shebang with python-mode.

---

src/commands/help.lisp

Show the global minor modes in `describe-mode`.
Gathering the global minor modes is not nice, but I didn't want to export another function from mode.lisp.

Show the global minor modes in describe-mode.

---

src/ext/frame-multiplexer.lisp

The `virtual-frame-width` and `virtual-frame-height` is never updated.
This leads to two problems:
1. As soon as the native window (or terminal) is resized, the virtual frame thinks constantly that it needs to be redrawn. This makes the frame-multiplexer erase its buffer and re-write it, which leads to a redraw in the front-end. This is noticeable in the CPU usage (not extreme on my machine, but still).
2. Since the internal size is not updated, as soon as the native window gets back to its original size, this last resize will not lead to a redraw of the frame-multiplexer. Therefore, the header line will remain as it was before (I noticed that the background colour is not redrawn). As soon as you do something (like `M-x`), the whole window is redrawn again and one can see the change in …

Update the stored display size in the virtual frame.

---

src/commands/buffer.lisp

This adds an interactive command. The name "indent-buffer" is taken by the function.

add indent-current-buffer

---

extensions/color-preview/color-preview.lisp
extensions/color-preview/lem-color-preview.asd
lem.asd

`M-x color-preview` to enable.

add color-preview

---

src/format.lisp

Accidentally left this in earlier, it serves no purpose and is annoying.

remove debug message

---

frontends/sdl2/keyboard.lisp
frontends/sdl2/platform.lisp

Adds FreeBSD as a platform. The methods for handling input on linux appear to work on FreeBSD too. Moves the common code to functions and calls them from the :linux and :freebsd methods.

Add FreeBSD support

---

extensions/go-mode/go-mode.lisp

This should fix Ejdă's error, but I can't recreate it, so please let him test it first.

remove old define-command

---

src/lem.lisp

On some systems (like Guix), Quicklisp is not present. When this is the case, Lem shows a disruptive error on startup. Lem initialisation continues after this, but getting rid of the needless error would be nice.

Make initialisation of Quicklisp conditional on whether it is present

---

extensions/vi-mode/commands.lisp
extensions/vi-mode/tests/visual.lisp

Fix invalid index of lem-vi-mode/commands:vi-delete.
column-point will get invalid index error, after deleting.

Fix invalid index of lem-vi-mode/commands:vi-delete

---

lib/language-client/request.lisp

Fix lsp client to work when built using guix.
The client logs to the file specified by `lem-language-client/request::*log-pathname*`
This variable is calculated at compile time, and in guix the build environment does not have access to the user directories, which means that the variable is set incorrectly to `/gnu/store/...`
I imagine this would be preferable to fix anyway, the change makes the variable a bit more resilient to changes in the environment

Change log-pathname from being set at compile time

---

extensions/lisp-mode/macroexpand.lisp

Same as lisp-macroexpand, but replaces the form in the buffer with the expanded one.
[Screencast from 2024-02-04 16-55-42.webm](https://github.com/lem-project/lem/assets/43155857/9d3157eb-63b3-4c85-946b-4fa166f43550)
I would find this useful for when I start writing something with a macro and then change my mind on using it.

M-x lisp-macroexpand-in-place

---

.gitignore
lem.asd
src/commands/other.lisp
src/interface.lisp
src/internal-packages.lisp
src/lem.lisp
src/quicklisp-utils.lisp
src/site-init.lisp
src/system-utils.lisp

This patch removes a hard dependency on quicklisp, and allows for the use of ocicl instead.  There should be no change for quicklisp users, but users with the `ocicl-runtime` package loaded will pull dependencies from an ocicl OCI registry.

Remove hard dependency on quicklisp

---

src/ext/directory-mode.lisp

This command removes the marked lines from the directory-mode buffer:
> Delete the marked lines from the directory-mode buffer.
> This does not delete the marked entries, but only remove them from the buffer.
This function can be useful to narrow the directory buffer by first marking lines using a regex and then killing those lines.
I also added a helper method MARKED-LINES which returns a list of temporary points for each marked line.
MARKED-FILES is now implemented using this helper.

Adds the command DIRECTORY-MODE-KILL-LINES.

---

src/ext/directory-mode.lisp

The following new commands have been added:
DIRECTORY-MODE-MARK-DIRECTORIES
> Mark all directories in the current buffer except '..'.
> With prefix argument ARG, unmark all those directories.
DIRECTORY-MODE-MARK-LINKS
> Mark all symbolic links in the current buffer.
> With prefix argument ARG, unmark all those links.
DIRECTORY-MODE-MARK-SUFFIX
> Mark all files with the given SUFFIX.
> The provided SUFFIX is a string, and not a file extenion, meaning every file with
> a name ending in SUFFIX will be marked.
> With prefix argument ARG, unmark all those files.
DIRECTORY-MODE-MARK-EXTENSION
> Mark all files with the given EXTENSION.
> A '.' is prepended to the EXTENSION if not present.
> With prefix argument ARG, unmark all those files.
DIRECTORY-MODE-NEXT-MARK
> Move to the next Nth marked …

Adds more mark commands for directory-mode.

---

contrib/mouse-sgr1006/main.lisp
src/internal-packages.lisp
src/window/side-window.lisp

With the ncurses front-end, I could not switch the focus to the left side window (Filer window) by clicking on it. The mouse support was enabled by loading the `mouse-sgr1006` contrib library.
This PR fixes it by considering all the windows when calculating the window to which it should shift focus to.

Enabled focusing leftside window with mouse in ncurses frontend

---

contrib/tetris/tetris.lisp

erase-buffer requires a buffer in the argument
https://github.com/lem-project/lem/blob/1c365fe3d64b543d4a161cf52d9bec2748d6321f/src/buffer/internal/basic.lisp#L253
Due to timers running in threads a `defvar` is used to store the tetris buffer

fix usage of erase-buffer in tetris

---

src/ext/directory-mode.lisp

The key bindings added in https://github.com/lem-project/lem/pull/1296  conflict with vi-mode, so I changed them to C-k.

Change key bindings `k` to `C-k` in directory-mode, to avoid conflicts with keys in vi-mode

---

contrib/tetris/tetris.lisp

adds killing the tetris buffer as another method to quit otherwise timers will leak

run tetris-quit after killing buffer as well

---

src/keymap.lisp

Often used by user, figured it wouldn't hurt to add a small docstring

Add small docstring for define-key

---

extensions/legit/legit-rebase.lisp
extensions/legit/porcelain.lisp

Now the interactive rebase (legit status, "r" and "i" on a commit) works (the best case, still more workflows to tackle, like abort a rebase). Damn, I was persuaded it did. It is possible I didn't test from scratch, but was using old definitions in my running lisp :S

(minor) legit: fix rebase

---

contrib/mouse-sgr1006/main.lisp

This feature allows us to scroll other windows under the mouse while the focus is on one window.
I use this feature heavily while referencing another code in a split window. This also matches the behaviour of Emacs and Vim (at least on macOS).
This is gated under the parameter `lem-mouse-sgr1006:*scroll-unfocused-window*` with the default value as `nil`. I am open to setting this as default behaviour, but I was not sure other users would prefer this.

Added scrolling of unfocused window with mouse in ncurses frontend

---

extensions/vi-mode/registers.lisp
extensions/vi-mode/tests/visual.lisp

Fix process-block-region space padding of vi visual mode

Fix process-block-region space padding of vi visual mode

---

extensions/legit/legit-rebase.lisp
extensions/legit/legit.lisp
extensions/legit/porcelain.lisp

We can now use "r c" or "r s" to continue or skip a rebase process that was started outside of Lem. `C-c C-c` in the rebase buffer was telling git to continue the rebase and pick our changes, but now we can call "--continue" anytime.

legit: add --continue and --skip

---

frontends/sdl2/lem-sdl2.asd
frontends/sdl2/main.lisp

On Mac OSx the GUI needs to run in the main thread. If running from another thread such as a REPL, the SDL2 frontend will fail so it's necessary to ensure execution is running in the actual main thread.

Wrap SDL2 call with trivial-main-thread to run in main thread

---

contrib/mouse-sgr1006/main.lisp
src/internal-packages.lisp

Without this fix, the cursor position was be off by the width of the line number view to the right.

Fixed cursor movement by mouse when line numbers are enabled

---

lem.asd

Regarding a comment in the discord, `M-x lem-version` fetches the version from the .asd file which is currently out of date

Update version in .asd to latest

---

src/display/base.lisp
src/display/physical-line.lisp
src/internal-packages.lisp

for example
```
(setf (variable-value 'lem::wrap-line-character :global) #\$)
(setf (variable-value 'wrap-line-attribute :global) (make-attribute :background "red"))
```

add editor-variable `wrap-line-character` and `wrap-line-attribute`

---

src/ext/line-numbers.lisp

M-x toggle-line-numbers => obey to the global variable `*relative-line*`.
C-u M-x … => display relative line numbers.

line numbers: use prefix argument to show relative line numbers

---

src/ext/popup-window.lisp
src/ext/prompt-window.lisp
src/internal-packages.lisp
src/prompt.lisp

This will let people hook prompt completion when a prompt window is activated like this:
```lisp
(add-hook *prompt-after-activate-hook*
(lambda ()
(call-command 'lem/prompt-window::prompt-completion nil)))
(add-hook *prompt-deactivate-hook*
(lambda ()
(lem/completion-mode:completion-end)))
```
This will show completion items without needing to press `<Tab>`

prompt-after-hook

---

src/ext/completion-mode.lisp

Allow the order of completions to be reversed, this is helpful when the prompt is at the bottom of the screen so you don't have to move your eyes.
I am using this in my config so that completions are reversed in regular prompts, but normal in code completion:
```lisp
(add-hook *prompt-after-activate-hook*
(lambda ()
(setf lem/completion-mode::*completion-reverse* t)
(call-command 'lem/prompt-window::prompt-completion nil)))
(add-hook *prompt-deactivate-hook*
(lambda ()
(setf lem/completion-mode::*completion-reverse* nil)
(lem/completion-mode:completion-end)))
```

Completion tweaks

---

src/buffer/internal/buffer-insert.lisp
src/buffer/internal/buffer.lisp
src/buffer/internal/point.lisp
src/buffer/internal/var.lisp
src/common/var.lisp
src/display/base.lisp

These are mostly machine translated, but I found them to still be helpful.\
If anyone has some better translation I'd be happy to include it.\
Especially the `editor-variable` doc-string is a little unclear to me, how do 'local variables' relate to 'global values'?

Translated most (all?) doc-strings.

---

frontends/sdl2/main.lisp

Add an event handler for SDL's drop event so dragging files onto Lem opens it up.

Add file drag and drop support for SDL2

---

extensions/lisp-mode/paren-coloring.lisp
src/internal-packages.lisp

As it stands, `paren-coloring` colors are hardcoded, which can look jarring when using a theme. This PR makes it so that it just uses  `8`-`0d` of the current base16 [palette](https://github.com/chriskempson/base16/blob/main/styling.md). I tried it on a few themes and it seems to be working fine.
PS: I'm new to CL, so I might have done something dumb. Feel free to make whatever changes you see fit.

Use theme colors for rainbow parens

---

extensions/lisp-mode/completion.lisp
src/ext/popup-window.lisp

Documentation popups going over the edge of the screen have been driving me mad recently.
This adds a new gravity `vertically-adjacent-window-dynamic`, that ensures the popup is visible, and sets it as the default gravity for documentation popups.
It also makes the gravity type for documentation popups configurable with `*documentation-popup-gravity*`
I thought about replacing `vertically-adjacent-window` but figure some people prefer the old way.

Dynamic vertically-adjacent gravity

---

src/defcommand.lisp

A comment on discord mentioned that strings as argument-descriptors are sub optimal, to which I agree.
This merge-request overhauls the `define-command` macro so that it accepts both old-style string descriptors, as well as list argument-descriptors.
The following descriptors were added:
`:universal`, `:universal-1`, `:universal-nil`, `:string`, `:number`, ~`:num`,~ `:buffer`, `:other-buffer`, `:file`, `:new-file` and `:region`
with `:universal-1` ~and `:num`~ being aliases of `:universal` ~and `:number`~ respectively.
I also added some documentation to the existing `:splice` descriptor and exposed the extremely helpful comment in the command-function as a doc-string.

Make define-command accept more verbose/understandable argument-descriptors

---

extensions/lisp-mode/lisp-mode.lisp
extensions/markdown-mode/markdown-mode.lisp
extensions/markdown-mode/syntax-parser.lisp
src/internal-packages.lisp
src/keymap.lisp
src/mode.lisp

This PR is an additional change to that PR. https://github.com/lem-project/lem/pull/1377
- execute method is not called (e.g. https://github.com/lem-project/lem/blob/main/extensions/lisp-mode/self-insert-hook.lisp)
- Indentation in c-mode does not work

Change the target language function to be called in the markdown-mode code block

---

extensions/lisp-mode/lisp-mode.lisp

the function `send-swank-create-server` assumes the user has quicklisp installed and fails if they don't.
I have replaced
```lisp
"(ql:quickload :micros)"
```
with
```lisp
"(handler-case (eval (read-from-string \"(ql:quickload :micros)\"))
(error (c) (asdf:load-system :micros)))"
```
so that it falls back to `asdf:load-system` if quicklisp is not available.
Catching a reader error like this is a bit hacky, maybe we should just always use `asdf:load-system`? I'm not sure, but this seems to work.
Also, auto-formatting.

Fallback to asdf:load-system to create a micros server

---

extensions/vi-mode/ex-command.lisp

There are some vim users that expect to be able to cycle through their next buffer and previous buffers by using the commands:
`:bn` and `:bp`
This just simply adds those commands to the `ex-command.lisp`

Add :bn and :bp vi commands

---

src/internal-packages.lisp
src/site-init.lisp

So, the site-init functionality is lookinf or asd files recursively, this can be problematic when a package manager is introduce (like https://github.com/lem-project/lem-extension-manager). As it may load undesired libraries/files from other directories.
The idea of this change is to isolate the look for asd files for site-init functionality to a "lisp" folder on the ".lem" directory (it can also be modified by the user).

Move side init recursive load to a named directory

---

extensions/lisp-mode/grammar.lisp

This will make macros like `defmemo`, `defroute`, `defcommand`, etc. be highlighted the same as `define-*` macros.

add def* to grammar

---

extensions/legit/legit.lisp
extensions/legit/porcelain.lisp

This PR adds support for deleted files in Legit. It also incidentally overhauls a bit of the status UI.
Here's the before/after:
Change summary:
- Deleted files now show up under staged/unstaged
- Untracked files now have a diff preview
- Number of files per section are now listed
- Modifications now have their type listed to the left, similar to Magit (created/modified/deleted)
Deleted files don't have a diff preview as of right now, instead there's just a message stating the file has been deleted. Should probably be revisited at some point to have the deleted file's contents show up.
Also, I'm unfamiliar with Mercurial and Fossil. I attempted to keep it compatible, but I was unable to test properly on Fossil (couldn't commit with/without my changes). Mercurial is mostly fine, the only …

Legit `status` deleted file support, minor UI overhaul

---

extensions/legit/legit.lisp

This adds some minor QoL changes to untracked files in legit status:
- Show top-level list of files/directories inside of an untracked directory
- Fix an error when trying to display untracked file contents for binaries

Add better untracked file support to legit status

---

extensions/legit/README.md
extensions/legit/legit-commit.lisp
extensions/legit/legit-rebase.lisp
extensions/legit/legit.lisp
extensions/legit/peek-legit.lisp
extensions/legit/porcelain.lisp

Opening files/directories in legit status can sometimes yield an error if you don't have a buffer in the current project open. This changes it so we run `call-with-current-project` before so we have the right context.

Use `call-with-current-project` when opening unstaged files/directories in legit status

---

src/commands/file.lisp
src/system.lisp

First off, thank you creating Lem. I earnestly believe it could be the future of Emacs like text editors. I use it everyday.
The goal of this commit is to run external programs asynchronously by simply switching from uiop:run-program to uiop:launch-program. This in consequence changes the return value to a uiop:process-info object.
As far as I know, the find-file command is the only function reliant on the uiop:run-program return value. To remedy this, I added bufferp check in it.

Asynchronously run external commands with find-file

---

extensions/lsp-mode/lsp-mode.lisp

I'm using this locally because my LSP server is refusing to come up, and I'm trying to debug/work through the problem by doing `lsp-restart-server`s.
However, those fail while deleting the workspace for the current buffer because... lsp initialization always fails, hence the `(buffer-workspace)` call always fails
Anyways, I *think* this actually makes sense as a general change: I'm not an expert in lem LSP internals so maybe there's some reason this can't be upstream, but to me `lsp-restart-server` should start a connection without erroring if there's no existing one

Make lsp-restart-server proceed even when buffer-workspace fails

---

contrib/tetris/tetris.lisp

Come on, it's the 21st century. Every tetris clone needs a hard drop button.

Add hard drop to tetris

---

extensions/lisp-mode/lisp-mode.lisp

In Emacs, pressing C-c ~ in a Lisp buffer with SLIME will cause the REPL's package to be switched to the buffer's active package. This change implements that functionality.
Note that it doesn't have the functionality of switching Lisp's current directory. This is partially because I found that behaviour janky in Lem, and partially because I don't like it doing that in Emacs either.

Add SLIME's C-c ~ command (sync package) to lisp-mode

---

extensions/lisp-mode/paren-coloring.lisp
src/color-theme.lisp
src/ext/frame-multiplexer.lisp
src/internal-packages.lisp

This PR relies on: https://github.com/lem-project/lem-base16-themes/pull/2
(That one should get merged first, then we update qlfile.lock)
I've been adding base16 colors to parts of lem that were hardcoded, and I realized now that my efforts were a bit misguided. Instead of manually using base16 colors, which might not be present in some themes, the right way to do this is just to expose the appropriate attributes and modify the base16 theme generation code to use them (attached PR).
This PR exposes attributes where necessary (modeline/paren colors), and removes the functionality I had added for base16 colors, since it's no longer necessary. Also fixes a minor bug when selecting themes, where the colored parens wouldn't change with it immediately.
Now it looks right:

Expose modeline attributes, various theme fixes

---

extensions/terminal/ffi.lisp
extensions/terminal/terminal-mode.lisp
extensions/terminal/terminal.c
extensions/terminal/terminal.lisp

I'm not totally sure if the `-c "cd directory"; $SHELL` approach is really the *right* thing to do, but it at least works on both bash and fish.
I haven't regenerated any .so files: I figure @cxxxr might want to do that themselves. Although we really shouldn't be keeping binary blobs in the repo in the first place.

Make 'terminal' command launch shell in buffer's current directory

---

extensions/lisp-mode/eval.lisp

Fixes `compute-evaluated-background-color` producing a malformed color string. 
Also makes the highlight color darken instead of lighten when evaluating on light light themes.
It appears that the `compute-evaluated-background-color` function worked only through luck because it seems okay on most themes. On my theme, however, which had a pitch-black background color, the evaluation highlight looked really bad:
This PR corrects the issue, but it may be necessary to change the values used in the function in the future because now it probably won't look as it looked before on some themes.

Fix malformed eval background color

---

src/ext/line-numbers.lisp

Adds `active-line-number-attribute`, which allows to customize how the current line number should look if using `line-numbers-mode`.
The default `active-line-number-attribute` value is equivalent to the `line-numbers-attribute`.

Add active line number attribute

---

src/attribute.lisp
src/ext/themes.lisp
src/internal-packages.lisp

Closes #1468
This PR adds document attributes we can use with markup/document views (e.g. org mode, markdown, legit, etc.) and sets some working colors for the default lem theme. I'll push up a separate PR moving `markdown-mode` over to these alongside changes to the default theme ones if they don't work too well.

Add document attributes

---

src/ext/tabbar.lisp
src/internal-packages.lisp

Easy to reproduce with "lem -Q" and the M-x toggle-tabbar.   There are flashes when a tab is clicked.
I originally thought that it was because my theme had a dark background, so I made the included change to select the tabbar foreground color based on a light or dark background.   It does not fix the problem, but I think it is correct.  I exported functions related to light/dark background queries.
Also, I wonder if "lem -Q" should load ~/..lem/config.lisp.  I did not expect my theme to be loaded with "lem -Q".

tabbar does not display properly (SDL2)

---

src/common/color.lisp

This change adds "lispy" aliases for color names, in which spaces are replaced with dashes.
This is done with lower cased names only: "dark-gray", not "Dark-Gray".
Emacs does not do this.
I don't know if this is even useful, although it does make the hash table of colors available as a variable.

Create lispy aliases for color names with spaces.

---

extensions/lisp-mode/lisp-mode.lisp
extensions/lisp-mode/repl.lisp

When REPL is started with `M-x start-lisp-repl`, if it is a self connection, a message is displayed.
```common-lisp
;; Welcome to the REPL!
;;
;; The current REPL is running in the same process as the editor.
;; If you don't need to hack the editor,
;; please start a new process with `M-x slime`.
CL-USER> 
```
When another process is started with `M-x slime` and the connection is switched, a message is displayed in the REPL.
```common-lisp
;; Welcome to the REPL!
;;
;; The current REPL is running in the same process as the editor.
;; If you don't need to hack the editor,
;; please start a new process with `M-x slime`.
CL-USER> 
; changed connection (sbcl 2.4.6)
CL-USER> 
```
Also, if you return to self connection, it will display a message to that effect.
```common-lisp
;; Welcome to the …
```

Add welcome text to REPL and display of current connection

---

src/ext/grep.lisp

Adds `project-grep` command and binds it to `C-x p g`. Feels nice not having the grep directory show up every time (also having a keybind).

Add project grep

---

src/ext/grep.lisp

Adds the `-I` argument by default to exclude binary files. Safe to say most of the time we're not grepping through binary files, and it helps to get rid of editor errors like:

Change default grep prompt to exclude binary files

---

src/commands/file.lisp
src/common/history.lisp
tests/common/history.lisp

Adds `move-to-top` to `add-history`, which moves the entry to the top of the stack if it already exists. Then uses it with `file-history` to re-order the most recent entry if it's already in the history.

Add `move-to-top` to history, use with file history

---

src/ext/grep.lisp

I have added *grep-command* and *grep-args* for customizing the grep command.  This is useful for windows, which doesn't have grep by default.  I exported the variables, not sure if that's desired.
An alternative would be to rename *last-query* to *grep-command* and put the entire command in there.  Let me know if you would prefer that.
I have added the following to my init.lisp:
#+win32
(setq *grep-command* "c:/cygwin64/bin/grep.exe")

Add variables for git command and args.

---

frontends/sdl2/keyboard.lisp

The super key seems to be working properly on my M1 MacBook Pro 16'  running on macOS 14.5 (23F79). Not sure if the reason behind remove/disabling it is still valid: 292d2dad5489d255749b5e6d3b9b4e3e62ef5d55

Re-enable super key support in SDL2

---

src/ext/frame-multiplexer.lisp

Adds `frame-multiplexer-create-with-previous-buffer`, bound to `C-z C-C`, that creates a multiplexer frame and sets it to the previous buffer. Useful when you want to open a frame in the same dir. 
Maybe can be replaced with a `frame-multiplexer-duplicate` that copies over the entire frame at some point?

Add `frame-multiplexer-create-with-previous-buffer`

---

lem.asd
src/color-theme.lisp
src/ui/theme-list.lisp

Makes themes clickable in the theme list. Also moves the theme list to its own file and adds a `ui` module.

Use buttons for theme list

---

extensions/lsp-mode/client-capabilities.json

Rust analyzer will not return any code actions unless `codeActionLiteralSupport` is enabled.
This adds it to the default client capabilities, based on what is configured in emacs lsp-mode, see
https://github.com/emacs-lsp/lsp-mode/blob/c36b95be6625dac5a37d3874a1a738e0c84ac39f/lsp-mode.el#L3731-L3738
With this change, they do show up provided you run `M-x lsp-code-action` when in a valid location.

lsp-mode: update client-capabilities.json for code actions

---

extensions/lisp-mode/ext/autodoc.lisp

Fix highlighting the current argument:
`(change-buffer-mode buffer 'lisp-mode)` was overriding the attribute, so I set it back to fundamental mode before we apply the highlight.

Fix lisp completion current argument highlighting

---

STYLEGUIDE.md

A styleguide can be beneficial to… guide new contributors.
There aren't a lot of "don't"s or "must"s.
I gathered remarks that were applied on some pull requests, and you might recognize one or two preferences of mine.
This first attempt is here for debate.

add STYLEGUIDE

---

Makefile
extensions/ruby-mode/lem-ruby-mode.asd
extensions/ruby-mode/ruby-mode.lisp
lem.asd

This commit has really basic support for the ruby language, this includes:
- Syntax highlighting
- indentation
I reused a lot of the logic implemented in elixir-mode, but i changed the language *keywords* and the way the indentation is calculated, which could be better, but it seems to work alright from what i've tested.
I'm still working in adding LSP support for the language, but if this is ok, i guess that could be merged in another branch, since i don't know how long it might take me or if anyone else wants to work on it.
I appreciate any feedback/improvement btw.

Basic support for ruby language

---

extensions/vi-mode/ex-command.lisp

Option `*edit-buffer-directory*`  add to vi mode.
It selects `buffer-directory` or `getcwd` in ex-edit.

Add `*edit-buffer-directory*` to vi-mode

---

extensions/vi-mode/commands.lisp

From the vim documentation on `word`:
> Special case: "cw" and "cW" are treated like "ce" and "cE" if the cursor is on a non-blank.  This is because "cw" is interpreted as change-word, and a word does not include the following white space (see also cw).

cw should be a synonym to ce

---

extensions/vi-mode/ex-command.lisp

Add `wa` `wall` `wa!` `wall!` ex-command to vi mode.

Add wall ex-command to vi mode

---

frontends/sdl2/main.lisp

HiDPI support for MacOS was enabled via #799. 
This PR just removes the `#+darwin` restriction.
It seems that the original concern (https://github.com/lem-project/lem/pull/799#issuecomment-1614346368) is no longer a problem.
Tested on Linux KDE Plasma 6.2.2

Enable fractional scaling on all platforms

---

default.nix
flake.lock
flake.nix

This PR adds a Nix flake that can build lem-ncurses and lem-sdl2 on both Linux and macOS.
This is mostly code from https://github.com/dariof4/lem-flake, with some polishing and updating.
Currently all of the dependencies are manually tracked, which is a bit of a maintenance chore. Maybe there's some way to automate this bit with ql2nix or something.

Add Nix flake

---

flake.lock
flake.nix

This PR replaces the manual dependency pinning with a build process that uses `qlot bundle` to handle downloading dependencies based on the `qllock` file.

Nix: use qlot bundle instead of manual tracking

---

flake.nix

I removed the bundle hash from the last PR (#1593) and that ended up not being the right thing to do. This PR reverts that particular change.

nix: readd output hash for qlot bundle

---

src/ext/isearch.lisp

with this modification, isearch-next|prev-highlight will mimic isearch movement exactly, which i feel is more intuitive for those who use isearch a lot
font-size: 16px;
...
font-size: 22px;
...
font-size: 16px:
...
font-size: 20px;
...
| (<-- point here)
you search for "font-size: ", and now it's highlighted.  maybe you want to change the 22px font size.  with the current code, if you go back with `Shift+F3` , then, when you press `F3`, you will jump forward to the next instance of font-size, which is not how isearch works.  
but, with this patch, if you press `F3`, you will go to end of the highlight instead of the next instance, which i find more logical for isearch and better in general because now you can `kill-line` and put in the new font-size value

make isearch-next|prev-highlight mimic isearch movement exactly

---

flake.nix

`ae4d94d` restored the output hash, but not (seemingly) to the right value-- this fixes that, and also makes it so nix looks for binaries with the right names when using `nix run`.
(People on macOS should test that this does not break things for them-- I don't have any readily available Mac machines to do so myself.)

Fix flake hash, binary names on linux

---

frontends/sdl2/main.lisp

To fix issue: https://github.com/lem-project/lem/issues/1617

fix: sdl2 should not disable the kwin compositor, which will cause the window effects invalid, including the window opacity.

---

frontends/sdl2/frame.lisp
frontends/sdl2/lem-sdl2.asd

The issue: https://github.com/lem-project/lem/issues/1583

feature: add `maximize-frame` and `minimize-frame` command for lem sdl2 version.

---

extensions/vi-mode/binds.lisp
extensions/vi-mode/commands.lisp

To close the issue: https://github.com/lem-project/lem/issues/1621
The command `vi-swapcase-and-forward-char` is used as a **shortcut** to swap-case on cursor and forward char in **vi-normal mode**.
The `vi-swapcase` is an **vi-operator**, which requires an extract **motion action**, to decide the region of swap-case, which may be an over-kill for some simple-case.
If you only want to swapcase for consecutive characters, just simply press the `~` key, and this new command will swap the case of character, move the cursor to forward character, repeatly.

feature: add vi-swapcase-and-forward-char command for vi-mode

---

src/commands/edit.lisp

this patch makes `kill-whole-line`, one, kill the entire line, including the new line at the end of a line if indeed it is there, and, two, allow for prefixes
|;; one one one
;; two two two
;; three three three
;; four four four
;; five five five
(| is point) if `5 kill-whole-line`, all lines are deleted.
;; one one one
;; two two two
;; three three |three
;; four four four
;; five five five
(| is point) if `0 kill-whole-line`, nothing happens.
;; one one one
;; two two two
;; three three |three
;; four four four
;; five five five
(| is point) if `-2 kill-whole-line`, ";; one one one" and ";; two two two" are deleted, and the point stays right before the last "three".  if you want to delete the previous "three"s, then you can use the `kill` command.
i'm curious if others agree with me

fix and refactor `kill-whole-line`

---

src/ext/isearch.lisp

i hope it's okay to add dedicated keybinds for `isearch-toggle-highlighting`. the keybinds feel very natural, and having the command available to the user as a default keybind seems user-friendly to me.

Add keybinds for `isearch-toggle-highlighting`

---

src/ext/isearch.lisp

update point after backspacing and yanking while isearch is active
|
;; one test is what you need
(| is the point) with this patch, if you search for "ee" and then backspace, the point will move to the end of the word "one".   in Lem currently, if you search for "ee" and then backspace, the point will stay after "ee", when I feel it should be at the end of "one" since the search string has changed.  this patch also works when reverse searching
|
;; one test is what you need
(| is the point)  with this patch, if  "one test" is the current kill string and you yank, the point will move to after "one test".  in Lem currently, the point will not move after yanking, which i don't think is natural

update point after backspacing and yanking while isearch is active

---

src/highlight-line.lisp

To close issue: https://github.com/lem-project/lem/issues/1650
To configure the `line-color`, eval: 
```
(setf (lem:variable-value 'lem-core::highlight-line-color :global) "#000066")
```
The screen-shot:

feature: add option for highlight line-color.

---

extensions/java-mode/java-mode.lisp

I found Lem today. :) I saw that I can't indent Java files. It looked like it was missing an indent function, so I am using the one from c-mode.

java-mode: Use c-mode indentation function to indent Java files

---

extensions/lisp-mode/repl.lisp
src/ext/listener-mode.lisp

To close issue: https://github.com/lem-project/lem/issues/1654
Just like the special variables for `pprint` control, use the `let` binding form to modify the **special variable** `*fill-width*`, to avoid modifying the signature of functions in the call stack.
Screen-shots:

fix: the *fill-width* option should not cause the prompt window in listener-mode out of window

---

src/ext/language-mode.lisp

To close issue: https://github.com/lem-project/lem/issues/1614
Now treats as selecting current line if no region is selecting while `comment` or `uncomment` a `region`.
This is a useful shortcut, to just `comment` or `uncomment` **a single-line**, no matter where your current cursor is now, no need to enter visual mode and select a region.

feature: treat as selecting current line if no region is selected for comments.

---

extensions/vi-mode/commands.lisp

To close: https://github.com/lem-project/lem/issues/1649
Maybe there should be a helper-macro to wrap the call to `ppcre:create-scanner`.
We know there are many matching tokens in regex language, so we should not try to create the regex-scanner immediately after each-character typed. Take the regex `(\w)` for example, if we create the sacnner at once, it will throw an error after the input of `(` due to the `not matched parenthesis error thrown by ppcre`.

fix: ignore errors during the process of creating regex scanner for vi-search-{forward/backward}

---

extensions/vi-mode/states.lisp

Solve part of the issue: https://github.com/lem-project/lem/issues/1648
This commit contains changes:
- The color of cursor in vi-insert-mode should respect the set default cursor color.
- The cursor-type for `vi-operator` should be `underline`, e.g. the `ciw` command.
---
It will be better, after the bug of drawing of `underline` and `bar` cursor type in `sdl2 version` is fixed. The `underline` and `bar` cursor tpe is drawn well in `ncursrs version`.
In `sdl2 version`:
1. The `underline` cursor-type will over-draw the character under caret.
2. The `bar` cursor-type will over-draw the character under caret in some cases, taken `"LEM"` string for example.

fix: adjust the cursor-type to underline for vi-operator + the color of vi-insert cursor now respects the default cursor color

---

src/ext/language-mode.lisp

change `move-over-)` to `move-over-)-or-wrap` so that if the mark is active, the region will be wrapped with parens and the point will be placed after the close paren, helpful if you don't need to add anything in the parens.  could also be helpful if you use pareto mode.  and the name is changed so that functionality is not hidden from the user
an odd command, but one that seems like a logical counterpart to `insert-()-or-wrap`

change `move-over-)` to `move-over-)-or-wrap`

---

extensions/vi-mode/commands.lisp
extensions/vi-mode/tests/commands.lisp

This commit fix the `edge case` when vi-paste a line before at the last line.
Taken this example buffer
```
first
second
third1 th[i]rd2 third 3
```
If current-line is **at the last line**, then the `vi-paste-before` command in `line-mode` should `open a new line` above `current-line`.
---
The keypoint is that: **The last line** doesn't contains the **line-break character**, so it's an edge-case.

fix: the `vi-paste-before` command in `line-mode` at `the last line` should open a newline before current line.

---

extensions/vi-mode/commands.lisp
extensions/vi-mode/ex-command.lisp
extensions/vi-mode/jumplist.lisp
extensions/vi-mode/tests/jumplist.lisp

Things started when i found a `test-case` that differs the `jumplist implementation` between `lem` and `vim`.
Taken this test-case buffer
```
second-location
start
first-location
third-location
```
And input the key-sequence `2gg 4gg gg G gg <C-o>`, and type in `:jumps`, see the difference.
In this screen-shot, we can see that `vim` implementation: turning the `2 4 1 7` into `2 4 7 1`, and `jumplist-current points to line 7`.
Actually, there are 2 bugs in this screen-shot:
1. When push a new jumplist-history element, we should not destory all elements above jumplist-index. (Vim delete the point, and re-push it into the top of jumplist-history.)
2. The jumplist formatter function prints the wrong format (it should not print the `1: (1, 14) common-lisp/lem/test-file-1.lisp`), the …

fix: the vi jumplist-history-push should not destroy jumplist-history elements above the jumplist-index, when a new element is pushed.

---

src/internal-packages.lisp
src/interp.lisp

i have a command that duplicates a line, but because it uses `copy-region` or `kill-whole-line`, it behaves unexpectedly when it is repeated.  with `nullify-last-flags`, the command works as intended when it is repeated

add `nullify-last-flags` function to interp

---

src/ext/language-mode.lisp

i always use `C-m` for `newline`, so i wanted to see if you would be okay making it also indent.  if the user wants a new line that is not indented, then they can use `C-q C-j` to get one.  this is for using other language modes other than lisp where it is the default

make `C-m` (`Return`)  `newline-and-indent` in language modes

---

src/ext/frame-multiplexer.lisp

`C-z C-z` and `C-z z` are frame-multiplexer-recent, very helpful to switch between frames quickly. if you are constantly switching between two frames, `C-z C-z` is super easy and fast to press
`C-z N` (where N is number between 0 and 9) to go to the Nth frame directly.  very logical and intuitive.  tmux also uses the same system

add convenient keybinds for LEM's multiplexer.

---

flake.nix

Update output hash after commit 86d9f36a.
86d9f36a changed versions in qlfile.lock, which of course broke the Nix flake.
This change sets the new hash.

fix(flake): Update outputHash

---

extensions/vi-mode/binds.lisp
extensions/vi-mode/commands.lisp
extensions/vi-mode/tests/jumplist.lisp

The `vi-jump-previous` command is a useful command, to **jump between current point, and previous point**. 
A use-case: you are writing a function `b`, which calls the function `a`, you need to jump between the definition of `a` and `b`. Just **double pressed the ' key**, it will works.
---
The implementaion is easy: We can **compose** the `vi-jump-back command`  and `define-motion`.
The effect is to define a new motion-command, its function is `vi-jump-back`. 
But because it is a `motion-command`, so the `vi jumplist facility` will save `current-point` for us automatically.

add: the missing `vi-jump-previous` command and binding.

---

extensions/vi-mode/commands.lisp

In `vim`, it's possible to use `yy3p` to: yank current line, and paste it 3 times.

feature: make `vi-paste-{before/after}` accept the universal args.

---

src/ext/language-mode.lisp

Reverts lem-project/lem#1674.
created some problems with unnecessary indentation, like in markdown mode

Revert "make `C-m` (`Return`)  `newline-and-indent` in language modes"

---

extensions/lisp-mode/repl.lisp

To close issue: https://github.com/lem-project/lem/issues/1688
This commit adds the syntax to highlight `caught WARNING` and `caught ERROR` in repl.

feature: highlight caught warning and error in repl

---

extensions/vi-mode/vi-mode.lisp

To close issue: https://github.com/lem-project/lem/issues/1609
Before this commit: When executing the `self-insert` command in `vi-insert mode`, the **first key in command-keys** will be consumed, however, the **rest keys in command-keys** will be ignore.
After this commit: The **rest keys in command-keys** will also be inserted in vi-insert-mode.
This is useful when you define the `j k` as `escape` for `vi-insert mode`.
And you can press `j k` as `escape` in vi-insert-mode, and `j e` as `self-insert j ` and `self-insert e`.

fix: the vi-insert mode should insert the pending-keys (the length of command-keys > 1) for self-insert command.

---

src/ext/popup-message.lisp

Parent issue: https://github.com/lem-project/lem/pull/1693

fix: ban mouse click event in popup-window made by popup-message function

---

frontends/sdl2/keyboard.lisp
src/key.lisp

Until now, the conversion of keys was done for each frontend, but this has been changed so that it is done on the lem side.

Add a mechanism to perform conversions such as C-m/Return and C-i/Tab in a unified manner

---

extensions/vi-mode/vi-mode.lisp

In pr: https://github.com/lem-project/lem/pull/1691, we flush the `pending-keys` for `self-insert` command in `vi-insert-mode`, so that we can define keymap like `(define-key lem-vi-mode:*insert-keymap* "j k" 'lem-vi-mode/commands:vi-normal)`.
The `effect` of this `define-key` is:
1. Press `j k` in `vi-insert-mode` will the `lem-vi-mode/commands:vi-normal` command.
2. Press `j <second-key>` in `vi-insert-mode` will self-insert `j` and self-insert `<second-key>`.
However, in the `vim` editor, if the `<second-key>` is NOT print-able key, then it will `quit the key pending state`, and will not self-insert the `<second-key>`.
**A case is: press `j` and `Backspace`.**
This pr fix this edge-case.
---
NOTE: 
This pr has some minor difference from the `vim`. The `named-key` is not identical to …

fix: the self-insert command in vi-mode should not insert un-printable char while flushing the pending-keys

---

src/interp.lisp

minor documentation fix in `interp.lisp`.  match arg label exactly

minor documentation fix in `interp.lisp`

---

src/color-theme.lisp
src/internal-packages.lisp

add `after-load-theme-hook` so that users may add functions that should run after a theme is loaded.  this could be useful in some cases.  in my specific case, it's to to maintain the color of the point since it is always very hard to see when the point is on an overlay like in search.

add `after-load-theme-hook`

---

src/ext/universal-argument.lisp

add `editor-variable-universal-argument-function` so that users can define their own incrementing patterns to `universal-argument`.  for example :
```
(setf (variable-value 'lem/universal-argument:universal-argument-function :global)
(lambda (x) (* 4 x)))
```
in this case, `C-u` is much more granular.  the default `C-u` jumps too much for me, going from 4 to 16.  but going from 4 to 8 and then 12 is much better for me
the default is kept at exponent of 4 : `(lambda (x) (expt 4 x))`

add `editor-variable-universal-argument-function`

---

extensions/lisp-mode/file-conversion.lisp

fix typo in file-conversion.lisp. change "a" to "an" because it's in front of "alist"

fix typo in file-conversion.lisp

---

extensions/paredit-mode/paredit-mode.lisp

This pr does improve the `implementation` for `paredit-wrap-around` in `buffer-mark-p = nil` branch.
The pr contains:
1. Simplify the impl by re-use the `forward-sexp` and `backward-sexp` funciton. (The `end` is where the `forward-sexp` point at, the `start` is where the `backward-sexp` point at.)
2. Remove the handling of `following-space`. (It's handled by `backward-sexp`, after the eval of `backward-sexp`, the `current-point` are guarantee to at the first char of sexp.)
3. Support to select **the sexp at current point** as a whole **unit**.
4. Always insert **1 space** before the `first char of sexp`, and **move current-point at it**. (Now it's more smooth to chain-call functions, the space is inserted there.)
5. Treat the `open char`, `string between open-char and closed-char` and …

feature: the paredit-wrap-around now support to select sexp at point without the need to move point to the beginning of sexp

---

extensions/lisp-mode/lisp-mode.lisp

Starting/restarting slime (micros) is a common-enough task I think it makes sense for it to have default keybinds.
I used the `C-c m` prefix, so e.g. `C-c m s` to start micros, `C-c m r` to restart, etc. Originally wanted `C-c C-m` but `C-m` is reserved for return.
Side-note, we should rename the `slime-*` commands at some point to `micros-*`. I didn't want to include that here since that's a breaking change.
Also, merry christmas :christmas_tree: :santa:

Add micros keybinds to lisp-mode

---

extensions/vi-mode/README.md
extensions/vi-mode/tests/text-objects.lisp
extensions/vi-mode/text-objects.lisp

The fix is for the bug in [Issue #1657](https://github.com/lem-project/lem/issues/1657).
This affects code in operator pending mode, so the editor will freeze when using:
- v i/a "
- c i/a "
- d i/a "
- y i/a "
This occurs as when the escape character is found, it does not move the character forward/back, causing an infinite loop of finding the escape char.
As shown in this seek backward example, I have changed it to skip over 2 chars (the escape and the quote char). I did the same for when seeking forward.
```common-lisp
;; Before
((and escape-char)
(char= prev-char escape-char))
;; After 
((and escape-char 
(character-at point -2) ;; Bound check
(char= (character-at point -2) escape-char))
(character-offset point -2))
```
This behaviour to ignore escape chars, which seems intended for …

vi-mode - Bug - Fix freeze when using _i"/_a" in escaped string

---

src/internal-packages.lisp
src/key.lisp
src/keymap.lisp
tests/self-insert-command.lisp

change the word `hypher` to `hyper` in the entire lem repo.  sometimes it's spelled correctly while other times it's not.  this patch unifies the repo

change `hypher` to `hyper` across lem repo

---

src/commands/project.lisp

This is 2 small changes. When I started using `Project`, I had a hard time deciphering which folder was being saved as a project, since there are multiple files it can match on.
This change:
- Adds a message informing the user which directory was saved/removed from the project list.
- Adds a command `project-save-project` which will prompt the user for a directory to save.
This uses the existing functionality to remember the path, just gets the path from (prompt-for-directory)
The prompt invokes this:
Both saves trigger this:
And the removed:
This is just something small, I am happy to keep it in my config if not.
P.S. Take your time with any of my pull requests, no hurry! I have them in my config so I am happy :)

Project - Prompt Save + Message

---

src/ext/frame-multiplexer.lisp

only change recent frame list when switch target is different.  i find this to be very helpful because sometimes i choose the same frame either through a command or by accident, and then `frame-multiplexer-recent` becomes useless.  with this change, `frame-multiplexer-recent` will continue to be useful even after a mistake or a redundant switch
for example :
i run a command that always opens a file in frame 1.  so i run the command a few times (maybe while changing buffers on the same frame), and now when i do `frame-multiplexer-recent`, it is useless.  with this patch, `frame-multiplexer-recent` will continue to be useful in such situations

only change recent frame list when switch target is different

---

src/internal-packages.lisp
src/keymap.lisp

I noticed this here, and wasn't going to look into it. But I started getting into paredit myself, so I encountered the same issue. Now it's personal..
Issue: [feature: the undefine-key function to delete an existing key in a keymap.](https://github.com/lem-project/lem/issues/1611)
Add public function: `undefine-keys` and marco `undefine-keys`. These are very much in the same style as their `define` counterparts.
I tested both functionality in my own config:
```common-lisp
(undefine-key *paredit-mode-keymap* "C-k")
(undefine-keys *paredit-mode-keymap* ("C-k")
( "C-L"))
```
I also tested attempting to undefine keys that don't exist in the map. This is fine with no errors.
For example with paredit, you can define your own keys before or after undefining the paredit keys, as it will just …

Add (undefine-key) functionality

---

src/keymap.lisp

GUI mode had no ability to seperate ```Tab``` from ```C-i```.
```lisp
(defun parse-keyspec (string)
(labels ((fail ()
(editor-error "parse error: ~A" string))
(parse (str)
(loop :with ctrl :and meta :and super :and hyper :and shift
:do (cond
((ppcre:scan "^[cmshCMSH]-" str)
(ecase (char-downcase (char str 0))
((#\c) (setf ctrl t))
((#\m) (setf meta t))
((#\s) (setf super t))
((#\h) (setf hyper t)))
(setf str (subseq str 2)))
((ppcre:scan "^[sS]hift-" str)
(setf shift t)
(setf str (subseq str 6)))
((string= str "")
(fail))
((and (not (insertion-key-sym-p str))
(not (named-key-sym-p str)))
(fail))
(t
;; Removed this conversion
;; (cond ((and ctrl (string= str "i"))
;;        (setf ctrl nil
;;              str "Tab"))
;;       ((and ctrl (string= str "m"))
;;        (setf ctrl nil
;; …
```

removed C-i and C-m conversion from parse-keyspec

---

src/display/base.lisp
src/display/physical-line.lisp
src/ext/line-numbers.lisp
src/internal-packages.lisp

This change is fixes 2 bugs with line-numbers-mode. They are broken up into 2 commits if you wish to view the changes individually. Line numbers are looking a lot smoother now.
Currently, wrapped lines do not have the same font attributes as the line numbers and it looks very strange.
I moved the computation of the wrapped left area to a generic and removed the implementation(not needed when no line numbers). line-numbers-mode then implements this generic to allow using it's attributes to highlight the blank spaces.
I could have just exposed the attribute, but this is now matching with the unwrapped lines, and it allows more flexibility in extensions(adding icons to wrapped lines, etc.)
Before:
After:
This is a fix for my own issue: [improve: [line-numbers-mode] - Sync line format with …

Fix: [line-number-mode] - Wrapped line attributes & Uniform number width

---

extensions/python-mode/python-mode.lisp

The new indent function for Python mimics the behaviour of indent function as seen in Emacs, where hitting tab key will cycle through the following positions:
- Same indent level as last line.
- +1 indent level relative to last line.
- -1 indent level relative to last line.
There're still a flaw in this function, that I currently have no idea how to fix:
```python
v Cursor.
foo = bar|
```
after `newline-and-indent`:
```python
foo = bar
|
^ It should not have indented, since the last line is just a
top-level declaration.
```

Implemented improved Python indent function.

---

src/commands/edit.lisp
src/ext/line-numbers.lisp

Users can now set `*save-interprogram-clipboard-before-kill-p*` in package `lem-core/commands/edit` to choose whether or not to save the interprogram (system) clipboard content into killring before killing other things in Lem.
I'm a bit concerned about performance of `(string= clipboard-string (peek-killring-item (current-killring) 0)` if the clipboard data is very huge.

Add an option to control the save of clipboard content before killing.

---

frontends/sdl2/display.lisp
src/attribute.lisp
src/display/char-type.lisp
src/display/physical-line.lisp

Previously, if someone tried to open a file that contains zero-width characters, such as `U+200B`, `U+200C`, `U+200D`, and `U+FEFF`, Lem SDL2 will just refuse to display any content, leaving the user with a blank window.  This is probably because SDL2 does not like zero-width characters.
So now I try to fix this problem by adding another `char-type` dedicated for zero-width characters, and display them with a special character.
I've also created a new attribute for zero-width characters and control characters, so users won't confuse them with real contents.

Lem SDL2 can now properly display zero-width characters.

---

extensions/vi-mode/binds.lisp
extensions/vi-mode/commands.lisp
extensions/vi-mode/tests/text-objects.lisp
extensions/vi-mode/text-objects.lisp

Add the paragraph text object to vi-mode. Tested myself with the other operations: `dip`, `yap`, etc.
Passing:

vi-mode: Add paragraph text object

---

src/common/character/string-width-utils.lisp
src/display/char-type.lisp
src/display/physical-line.lisp

Since 1e42f96b44e4c2eb664100858c482a480526a4b4, if you put the cursor on the different line than the line those special characters are on, Lem will signal an error.  This issue is fixed in this PR.

Fix zero-width characters and control characters attribute issue.

---

extensions/coalton-mode/coalton-mode.lisp
extensions/coalton-mode/lem-coalton-mode.asd

* Code highlighting for `.coal` files.
* Indentation support.
* Show autodoc for Coalton functions.
* Its arguments can be different from definitions since the information is from Swank, just like Common Lisp.
Note that the indentation code is copied from lem-lisp-syntax since it doesn't take any customized rules.

Add coalton-mode for basic features.

---

extensions/coalton-mode/coalton-mode.lisp

* Prevent errors on `Space` from `autodoc`.
* Indent automatically with `Return`.

Minor fixes for coalton-mode

---

extensions/coalton-mode/coalton-mode.lisp

* Add `define-type-alias`.
* Not to show like a keyword if it's a package-prefixed one.

More minor highlighting fixes for coalton-mode.

---

flake.nix

This is a dirty first working pass.  I can build a working lem using just the dependencies provided by running `nix develop .#lem-sdl2`
I used `make sdl2`.  I have previously ran `qlot install` but I'm not sure if this is necessary.  I don't use a lot of Common Lisp.
It should be possible to make this work with pkg-config.  I just don't know how to usually convince CL to ask pkg-config.

Add dev shells to nix flake to build from source

---

flake.nix

Whoooops :o)
Thanks to eriedaberrie on Discord for mentioning this.  I was adding the ncurses shell last to be nice to ncurses people and didn't change the attribute while copying the line.

Actually use the SDL2 shell

---

src/commands/other.lisp
src/ext/prompt-window.lisp
src/internal-packages.lisp
src/prompt.lisp

Add key binding display to execute-command completion

---

flake.nix

This version includes everything necessary to build inside a pure container with just a working nix installation.
nix develop
make sdl2
make sdl
Since the extra stuff for ncurses or SDL isn't very big, it makes sense to only use one dev shell with a bit of redundancy.  Users won't have to remember to switch shells.  `nix develop` is easier to remember.

Combine Dev Shells & Fix Pure Build

---

docs/default-keybindings.md
extensions/vi-mode/commands.lisp
src/commands/window.lisp

Changed "move to the window on the up" and "move to the window on the down" to "move to the window above" and "move to the window below" respectively.

Fix grammar of window movement commands

---

src/commands/window.lisp
src/internal-packages.lisp
src/window/virtual-line.lisp

Emacs default behavior of (C-l recenter-top-bottom)

recenter-top-bottom (emacs-mode)

---

extensions/scala-mode/scala-mode.lisp
lem-tests.asd
tests/sample-code/LemScalaIndent.scala
tests/scala-mode.lisp

I found a bug in `scala-mode` `calc-indent-function`. `lem-js-node::js-calc-indent` breaks the indents in some cases. I tried to fix it in this PR.
In the following screen record I've launched two instance of Lem (without fix and with fix) and indent a file .scala that shared between them

fix: scala-mode calc-indent-function

---

extensions/lisp-mode/ext/eval.lisp

avoid crashing with a color-theme (:background nil)
cf. https://github.com/lem-project/lem/issues/1769
```
(define-color-theme "lem-dark" ("lem-default")
(:background nil))
(load-theme "lem-dark")
```
Running commands like `C-x C-e lisp-eval-at-point` under the color-theme with `(:background nil)` results in the following error.
```
The value NIL is not of type LEM/COMMON/COLOR:COLOR
Backtrace for: #<SB-THREAD:THREAD tid=268140 "editor" RUNNING {10039E86D3}>
0: (LEM-LISP-MODE/EVAL::COMPUTE-EVALUATED-BACKGROUND-COLOR)
1: (LEM-LISP-MODE/EVAL::DISPLAY-EVALUATED-MESSAGE #<LEM/BUFFER/INTERNAL:POINT (29, 0) "(define-key *global-keymap* \"C-\\\\\" 'undo)" {1006B57B13}> #<LEM/B
2: ((LAMBDA (LEM-LISP-MODE/CONNECTION:CONNECTION) :IN LEM-LISP-MODE/INTERNAL::PULL-EVENTS) …
```

let compute-evaluated-background-color handle nil background-color

---

flake.nix

I tried running `nix run github:lem-project/lem` on NixOS and macOS. On NixOS, this runs fine. However on macOS it shows this error message:
```
error: hash mismatch in fixed-output derivation '/nix/store/3sy98z0x1s7jnjnrjrx4mzhrhyhqk4px-lem-qlot-bundle-unstable.drv':
specified: sha256-NtCSBxEo/4uuhlLc9Xqlq+PM1fAbDfRBH64imMLvKYE=
got:    sha256-BV1m58fUe1zfLH5iKbDP7KTNhv1p+g3W99tFQFYxPqs=
error: 1 dependencies of derivation '/nix/store/y74flmb9scgzz5h75hqqvidb6cicwwff-sbcl-lem-ncurses-unstable.drv' failed to build
```
This commit fixes that by adding an `if` condition on checksum.

Update flake.nix to reflect checksum on macOS

---

src/ext/isearch.lisp

Hello everyone.
I have found a small bug and am trying to fix it.
When I run `query-replace`, only the first hit word is highlighted and I can't see where the word is after the second.
Looking at the current `highlight-region` implementation, only one search result is added to isearch-overlays.
It seems that the parentheses of `unless` have the wrong correspondence and it is not used to determine whether to exit the loop.
The following images show the before and after behaviour.

Fix query-replace to highlight all candidates

---

Dockerfile

Fix Couldn't execute "xdg-open": No such file or directory error (Docker)

---

extensions/vi-mode/commands.lisp
extensions/vi-mode/registers.lisp
frontends/sdl2/main.lisp

Fix broken paste in vi-mode. (https://github.com/lem-project/lem/issues/1700)
- We are not correctly handling the case when `(get-clipboard-data)` returns nil.
- `(get-clipboard-data)` was erroneously returning a SB-SYS:INT-SAP alongside the clipboard string which was being passed into `vi-paste-before/after` instead of a `:type`.
- `make`
- Open new buffer in vi-mode
- Press `p` to yank
- No more backtrace

Fix broken paste in vi-mode

---

extensions/terminal/terminal-mode.lisp
src/commands/help.lisp
src/ext/language-mode.lisp

When configuring key bindings I bumped into a few commands which were not exported properly.
Also added some more window move commands to terminal bypass list to help switching between terminal and editor windows.

Command exports for keybindings

---

src/commands/window.lisp

If any floating window is active when delete-other-windows is called the floating window remains stuck in the view and editor needs restart to recover.

Bugfix: Floating window left as the only one

---

src/ext/isearch.lisp

Vi-mode ex command s/$/whatever/ triggered the issue.

Fixed eternal loop when searching with regexp $

---

extensions/vi-mode/commands.lisp
extensions/vi-mode/commands/utils.lisp
extensions/vi-mode/core.lisp
extensions/vi-mode/states.lisp
extensions/vi-mode/tests/kbdmacro.lisp
extensions/vi-mode/tests/utils.lisp
extensions/vi-mode/vi-mode.lisp
extensions/vi-mode/visual.lisp
src/buffer/internal/basic.lisp
src/buffer/internal/buffer.lisp
src/buffer/package.lisp
src/commands/s-expression.lisp
src/display/logical-line.lisp
src/internal-packages.lisp
src/mouse.lisp
src/region.lisp

Modified the visual states in vi mode to use lem buffer mark as starting point and initiator of visual mode regions. To support synchronisation some small additions to core lem implementation was needed, mainly hooks for enabling and disabling the buffer mark.
This allows activating visual mode from any of the "mark-xxx" commands available on emacs mode side, including mouse operations.
Vi states are now buffer specific, not global. This fixes several small glitches and annoyances when switching between windows and buffers
Closes #1590

Unify vi-mode visual state with lem buffer marks

---

extensions/vi-mode/commands.lisp

Matching parenthesis highlighting was not very useful in vi insert mode, because it didn't highlight the opening parenthesis for just inserted closing parenthesis. Only after switching back to normal mode you could see the matching pair highlighted.
This patch changes insert mode behaviour to use parenthesis before the cursor as the highlighted pair in insert mode. This way it is also similar to emacs mode.
Before the patch:
After the patch:

Improved parenthesis highlighting in vi insert mode

---

src/commands/file.lisp

When a file (in linux at least) contains brackets it will make the completion dialogs fail because the output of native \*find-programs\* is not scaped in `src/commands/file.lisp`.
Specifically it will fail when trying to turn a string into a path/namestring in the function `maybe-make-pattern` (see the [SBCL source](https://github.com/sbcl/sbcl/blob/1d6df61f2368b48586a530136f3101e6c5c62322/src/code/filesys.lisp)).
I used the function `uiop:parse-native-namestring` to turn them into paths and then `namestring` to turn them into strings again because `completion-files` and `file-completion-rank` need strings.
If anything is wrong I'm happy to change/fix it.

Add parsing of native pathnames to avoid errors with some files

---

src/commands/edit.lisp

Added commands that allow the user to select regions using the shift and arrow keys.
If no mark is set, then shift + arrow-key will set the mark at point and move the cursor in the direction specified.
If the mark is set then it acts identically to the arrow key.

Added shift arrow key selection

---

flake.nix
qlfile.lock

installation through the nix flake was failing because of:
1. wrong hash output
2. old revision of `lem-extension-manager` which had references of the package `ql-http` and caused compilation issues.
this isnt a complete fix as now running `nix run github:lem-project/lem` gives `SDL Error: EGL not initialized`, but the compilation errors were fixed.

fix nix package

---

src/ext/language-mode.lisp

Fixes a problem in comment-region where lisp code was not being commented out properly (this would probably affect other languages too if they used line comments like Lisp).
Previously if there was a string in the form:
```cl
234
123
```
Then the first line would commented out properly, but then the cursor would go to the column directly below, regardless of the next line's indentation, and insert the comment there.
```cl
;; 234
12;; 3
```
This is now fixed so that it starts each line from column 0.

Fixes #1685

---

extensions/markdown-mode/interactive.lisp
extensions/markdown-mode/lem-markdown-mode.asd

This adds interactive features to markdown code blocks, like how src blocks in org-mode work.
The API consists of 3 commands: `markdown-eval-block`, `markdown-eval-block-and-insert`, and `markdown-kill-block-result`, as well as one macro, `register-block-evaluator` for users to add support for other languages (lisp and bash work by default).
`markdown-eval-block` evaluates the source block your cursor is in, and outputs the result to a popup buffer (just like `lisp-macroexpand`)
`markdown-eval-block-and-insert` evaluates the block and inserts it's result below the block.  If there was already a result there, it first deletes the old one.
`markdown-kill-block-result` deletes the result block below the code block your cursor is in, this is run automatically before …

Interactive markdown

---

src/ext/prompt-window.lisp

Minor change so that commands are sorted alphabetically.
This preserves the history so that the last n commands are shown first, followed by all the commands in alphabetical order.

Sort commands alphabetically in M-x completion window

---

src/prompt.lisp

Remove abundant closing paren

---

src/buffer/internal/basic.lisp

The main motivation for this PR is to fix the documentation for `line-offset` in `src/buffer/internal/basic.lisp`; the previous documentation was wrong. I then took the opportunity to revise the documentation of a few other functions in the same file, trying to keep the style consistent and clarifying the descriptions.

Documentation fixes and revision

---

frontends/server/main.lisp

#1953 
I am a little new to lisp images and lisp in general or I should say it's been a while. 
What I believe was happening here is at runtime, the get-dist-by-path function was using asdf to look for needed asset files for the server. As a result of asdf not being available to the runtime it would never find it thus resulting in the 404. I tested this locally and was able to get the editor working again on my Mac Silicon. 
Would love some eyes on this so that others can just get started by using the binary. Let me know if there is anything I need to change or a reason why this is a bad change. Still learning .

remove the asdf check from find dist path

---

extensions/markdown-mode/syntax-parser.lisp
src/ext/link.lisp

I tried to open a link using the `link-open` command in markdown mode, but the links did not open.
After some investigation I found a few issues:
1. markdown mode was not setting a `:link` property on the highlighted link text
2. the `lem/link::link-at` function was searching for `'link` and not `:link`
3. in `lem/link::search-url-link` and `lem/link::search-file-link`, link searches were not obeying the LIMIT parameter.  I added a check to ensure that the returned URL is bounded by LIMIT.
I fixed these issues and added code to the Markdown Mode syntax parser to add the `:link` text properties.
Lem Markdown mode adds the correct text properties to links, so they can be opened by the lem/link package.

Fixed bugs in lem/link package and added link properties in Markdown Mode

---

src/window/window.lisp

Fixes #1970.
I tested the movement manually. Everything seemed to work normally.
It looks like `lem-core::right-window` is only called by `lem-core/commands/window::move-right`, so it shouldn't mess with anything else.
I think it's logically fine that window `{ left: 0, width: 100, ... }` has window `{ left: 100, ... }` to its right.

Fix `right-window`: Find windows where `left.x + left.width == right.x`
